### DISCUSSION TITLE
Build using source from Git fails for Windows only

### DISCUSSION THREAD

**Discussion by matthewfeickert** [prefix-dev/rattler-build#1708] [Q&A] [answered]
I have a feedstock that is using [`rattler-build`'s source from Git syntax](https://rattler.build/v0.42.1/reference/recipe_file/#source-section)

```yaml
source:
  git: https://github.com/DavidMStraub/rundec-python.git
  # tag: ${{ version }}
  # Use exact commit as no tags for v0.5.1 or later (yet)
  rev: "1b3006f03098ef4c6d44200ef643fede9c426cfe"
  patches: add-pyproject-toml-for-build-system.patch
```

this works as expected for all builds _except_ Windows where it fails immediately with

```
 ╭─ Running build for recipe: rundec-0.6-py313h91f4191_0
 │
 │ ╭─ Fetching source code
 │ │ Fetching source from git repo: https://github.com/DavidMStraub/rundec-python.git
        1 file(s) copied.
Building recipe
 │ │ Fetching repository from https://github.com/DavidMStraub/rundec-python.git at 1b3006f03098ef4c6d44200ef643fede9c426cfe into D:\bld\src_cache\rundec-python.git
 │ │ × error Command failed: `git rev-parse "1b3006f03098ef4c6d44200ef643fede9c426cfe"`
 │ │
 │ ╰─────────────────── (took 2 seconds)
 │
 ╰─────────────────── (took 2 seconds)
Error:   × Failed to run git command: failed to get valid hash for rev
```

What is happening with Windows specifically that it can't execute the `git rev-parse` correctly where Linux and macOS can? Is there some additional syntax I can give, or is this a bug with `rattler-build` on Windows?

PR with example error: https://github.com/conda-forge/rundec-feedstock/pull/8

(Cross post of conda-forge Zulip chat: [#general > Build using source from Git fails for Windows only](https://conda-forge.zulipchat.com/#narrow/channel/457337-general/topic/Build.20using.20source.20from.20Git.20fails.20for.20Windows.20only/with/522500966))
