### ISSUE TITLE
Load needed variant values before first render

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#1011]
Validation and variant are sometimes a bit tricky.

If you have a recipe like this:

```yaml
package:
  name: foo
  version: ${{ FOO_VERSION }}
```

with a `variants.yaml` like so:

```
FOO_VERSION:
- "0.1.0"
- "0.2.0"
```

The recipe rendering will fail with something like:

```
Error:   × Parsing: missing field `version`
    ╭─[7:7]
  6 │     package:
  7 │ ╭─▶   name: clang-win-activation
  8 │ │     version: ${{ CLANG_VERSION }}
  9 │ │   
 10 │ ├─▶ build:
    · ╰──── add the field `version` in between here
 11 │       number: 0
    ╰────
  help: the field `version` is required for `package`
```

Because we don't inject the variant values early enough.

Similarly, the following fails:

```yaml
requirements:
  run:
    - foo ${{ FOO_VERSION }}.*
```

With an error of the sort:

```
Error:   × Parsing: failed to parse match spec: Unable to parse version spec: .*
    ╭─[18:7]
 17 │   run:
 18 │     - foo ${{ FOO_VERSION }}.*
    ·       ──────────────┬─────────────
    ·                     ╰── error parsing `foo .*` as a match spec
 19 │   run_exports:
    ╰────
```
