### ISSUE TITLE
How to setup for local development

### ISSUE THREAD

**Issue by vigneshmanick** [prefix-dev/rattler-build#1026]
Hello devs,

I have some questions with using rattler build and hope this is the right location to post.  I am testing how rattler build could work in a python c++ project which is currently being built with scikit-build-core.  

### General issues with rattler-build
1. The `RATTLER_CACHE_DIR` value is not being recognized if `XDG_CACHE_HOME` is not set, the value defaults to `~/.cache/rattler`  and this is an issue since my home folder doesn't have enough space and also is on a slower drive. To workaround, i had to set the `XDG_CACHE_HOME`  to the required value.
2. All the required dependencies are already defined in the `pyproject.toml` and i feel the effort is duplicated in having to add another reciepe.yaml. (i guess this is what you guys are trying to solve with bringing rattler build to within the pixi?)
4. My usual development setup involves running `python -m pip install -e .` do changes and finally commit and for production create a wheel with `python -m pip wheel` and use it in the production environment. What is the equivalen of this in rattler-build?
5. It would help with the development workflow if the logs are available in a file after the build is finished. Currently i have to pipe it to a file and feel this should not be necessary. In ci having logs directly is very helpful for debugging.

### Build backend issues

1. When using scikit-build-core it downloads the necessary packages automatically via pip and injects them into the environment (cmake, ninja, setuptools_scm etc.) but with rattler-build this doesn't work.
  - How do i specify dependencies in the recipe.yaml for a scikit-build-core project.  [getting started](https://scikit-build-core.readthedocs.io/en/latest/getting_started.html)  

sample from scikit documentation

   ```toml
[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "example"
version = "0.0.1"
   ````

what i specified in the recipe.yaml

```yml
requirements:
  build:
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - requests
  run:
    - python
```

i get ` │ │ ModuleNotFoundError: No module named 'scikit_build_core'`

Thanks!
