### ISSUE TITLE
fails to fetch tag from gitlab source

### ISSUE THREAD

**Issue by chaumage** [prefix-dev/rattler-build#1038]
I am trying to build a package using a private gitlab repo as a source, but git fails to fetch the tag.

In my recipe.yaml:

```
context:
  version: "0.1.0"
source:
  git: https://host/gitlab/my-repo.git
  tag: ${{ version}}
```

Output from rattler-build:

```
From https://host/gitlab/my-repo
 * tag               0.1.0      -> FETCH_HEAD
error: pathspec 'refs/tags/0.1.0' did not match any file(s) known to git
```

The repo does have the tag, and i can clone it and checkout the tag manually without problem.
I'm not sure if this is a bug or just a git configuration issue, does anyone know what's causing it ?
