### ISSUE TITLE
`generate-receipe` uses `Apache 2.0` instead of `Apache-2.0` when building open_speil

### ISSUE THREAD

**Issue by SobhanMP** [prefix-dev/rattler-build#1049]
`rattler-build generate-recipe pypi open_spiel `
generates 
```
about:
  homepage: https://github.com/deepmind/open_spiel
  summary: A Framework for Reinforcement Learning in Games
  license: Apache 2.0
```
but Apache 2.0 needs a dash between the two "words."

```
❯ rattler-build --version 
rattler-build 0.21.0
```

Thanks for the excellent package.
