### ISSUE TITLE
BUG: Binaries not found when using `cache:`

### ISSUE THREAD

**Issue by h-vetinari** [prefix-dev/rattler-build#1077]
In (a reduced form of) https://github.com/conda-forge/zlib-feedstock/pull/83, I'm running into the build not finding `cmake`, despite it clearly being there, both in the minimized `recipe.yaml`,
```yaml
context:
  version: 1.3.1
  build_num: 2

recipe:
  name: zlib-split
  version: ${{ version }}

source:
  url:
    - http://zlib.net/zlib-${{ version }}.tar.gz
    - https://gnupg.org/ftp/gcrypt/zlib/zlib-${{ version }}.tar.gz
  sha256: 9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23

build:
  number: ${{ build_num }}

cache:
  requirements:
    build:
      - cmake
      - ninja
      - ${{ compiler('c') }}
      - ${{ stdlib('c') }}
  build:
    script:
      # rattler-build figures out the {.sh,.bat} extensions
      - build_global

outputs:
  - package:
      name: libzlib

  - package:
      name: zlib
```

as well as the logs, e.g.
```
 │ │ Resolving build environment:
 │ │   Platform: win-64 [__win=0=0, __archspec=1=x86_64_v4]
 │ │   Channels: 
 │ │    - file:///D:/bld/
 │ │    - conda-forge
 │ │   Specs:
 │ │    - cmake    # <---
 │ │    - ninja
 │ │    - vs2019_win-64
 │ │    - vs_win-64
 │ │ [...]
 │ │ 'cmake' is not recognized as an internal or external command,
 │ │ operable program or batch file.
```

The `build_global` scripts here effectively just call `cmake`:
```sh
#!/bin/bash
set -ex

mkdir build
cd build

cmake -G Ninja \
    ..
```
```bat
@echo on

cmake -G "NMake Makefiles" ^
      %CMAKE_ARGS% %SRC_DIR%
if errorlevel 1 exit 1
```
