### ISSUE TITLE
git source will not inlcue link

### ISSUE THREAD

**Issue by fecet** [prefix-dev/rattler-build#1130]
If a git repo contains relative link, rattler seems cannot copy it correctly

**Comment by wolfv** [comment]
Do you maybe have a repro?

**Comment by fecet** [comment]
```yaml
context:
  name: "debug"
  git_url: https://github.com/microsoft/DeepSpeed.git
  git_tag: ${{ git.latest_tag( git_url ) }}

package:
  name: ${{ name }}
  version: ${{ git_tag[1:] }}

source:
  - git: ${{ git_url }}
    tag: ${{ git_tag }}

build:
  number: ${{ build|int + (microarch_level|int) * 100 + 1 }}
  string: py${{ python | version_to_buildstring }}_cuda${{ cuda | version_to_buildstring }}_pt${{ pytorch | replace('.', '') }}
  script:
    - ls deepspeed/accelerator
    - mkdir $PREFIX/bin
    - touch $PREFIX/bin/placeholder
```
