### ISSUE TITLE
Rust bindgen passing BINDGEN_EXTRA_CLANG_ARGS

### ISSUE THREAD

**Issue by neeldugar** [prefix-dev/rattler-build#1134]
Hi,

I'm trying to package a Rust binary that depends on some FFI bindings using bindgen, I would like to link against the zlib dependency I have from rattler's dependency which seems to insert the header and library in the correct place, the main issue I'm having at the moment is it seems to include/link against the system headers/libs. What I currently have for the build script section is something like so:

```yaml
build:
  script:
    - export BINDGEN_EXTRA_CLANG_ARGS ='-I{BUILD_PREFIX}/include -L$BUILD_PREFIX/lib -lz'
    - BUILD_PREFIX/bin/cargo install --features mimalloc --locked --bins --root ${PREFIX} --path foo

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - zlib
  run:
    - zlib
```

I'm having issues where the build shows:

`fatal error: zlib.h: No such file or directory`, I do see the header is present within `${BUILD_PREFIX}/include` when I follow the script failure path, is there anything I can do to remedy this?

**Comment by wolfv** [comment]
I think you should write it like this:

```yaml
build:
  script:
    - cargo install --features mimalloc --locked --bins --root ${PREFIX} --path foo --no-track

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
  host:
    - zlib
```
