### ISSUE TITLE
Implement source_files and files for `test` section

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#115]
Both are a list of globs of files that should be copied into the test directory.

**Comment by dhirschfeld** [comment]
I think this is the issue I just ran into?
```
thread 'main' panicked at 'not yet implemented: Test files is not yet implemented!', src/packaging.rs:611:13
```
With a test section in my `recipe.yaml`:
```yaml
test:
  files:
    - ./tests/
  commands:
    - tree ./
    - pytest
```
