### ISSUE TITLE
BUG: problems with `package_contents: lib:` tests

### ISSUE THREAD

**Issue by h-vetinari** [prefix-dev/rattler-build#1153]
In, the libaries are not named according to the usual pattern, but using the `package_contents` tests apparently is not compatible with selectors?

For [zlib](https://github.com/conda-forge/zlib-feedstock/pull/83), I'm currently using
```yaml
    tests:
      - package_contents:
          include:
            - zlib.h
          lib:
            # naming pattern doesn't match `lib<foo>.so` (unix) & `foo.dll` (win)
            - if unix:
              then:
                - z
              else:
                - zlib
```
which causes
```
Error:   × Parsing: expected a scalar value.
     ╭─[102:22]
 101 │                 # naming pattern doesn't match `lib<foo>.so` (unix) & `foo.dll` (win)
 102 │ ╭─▶             - if unix:
 103 │ │                 then:
 104 │ │                   - z
 105 │ │                 else:
 106 │ ├─▶                 - zlib
     · ╰──── expected a string value for `globs`
```

Also "expected a scalar value" sounds bad, because some packages contain several libraries (and so obviously it needs to be possible to put a list under `lib:`).
