### ISSUE TITLE
ENH: support `elif:` with selectors

### ISSUE THREAD

**Issue by h-vetinari** [prefix-dev/rattler-build#1154]
Sometimes we need to distinguish things in more than two ways, the most common case being linux-osx-win. It should be possible to write
```yaml
        files:
          - if: linux
            then:
              - something_linux
            elif: osx               # <--
            then:
              - something_osx
            else:
              - something_win
```
rather than having to slice things into repeated if-conditions.
