### ISSUE TITLE
Idea for better (non-redundant, more compact) branching syntax for selectors?

### ISSUE THREAD

**Issue by h-vetinari** [prefix-dev/rattler-build#1155]
While thinking about #1154, it occurred to me that it would be even nicer if we could do a match-style syntax that doesn't have to choose a single branch but could apply several!
```yaml
        files:
          - match: linux
              - something_linux
            match: osx
              - something_osx
            match: unix         # e.g. on linux, this should be taken
              - something_unix  # _in addition_ to the linux-only case
            match: win
              - something_win
            match: unix or win
              - something_that_applies_to_everything
            # no more `else:`, only explicit matches!
```

I guess it might be a bit late for such deep syntactic changes, but IMO this would make it much nicer to write recipes, rather than having to constantly restart `if:` branches to avoid exhaustivity-problems.

It would allow writing using a single `match:` (or whatever you want to call it, like the old `sel:` before it turned into `if:`) block for every section of the recipe, which would be much nicer IMO if we're looking at translating things like

<details>
<summary>examples</summary>

[this](https://github.com/conda-forge/mayavi-feedstock/blob/main/recipe/meta.yaml)
```yaml
    - cython                              # [build_platform != target_platform]
    - vtk =*=osmesa_*                     # [build_platform != target_platform and build_variant == "noqt"]
    - vtk =*=qt_*                         # [build_platform != target_platform and build_variant != "noqt"]
    - qt-main                             # [build_platform != target_platform and build_variant == "pyqt"]
    - qt6-main                            # [build_platform != target_platform and build_variant == "pyside6"]
```
or [this](https://github.com/conda-forge/polars-feedstock/blob/main/recipe/meta.yaml)
```yaml
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.3.2,<2                  # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}               # [win]
    - {{ compiler('rust') }}
    - posix                               # [build_platform == "win-64"]
    - cmake
    - make                                # [unix]
    - cargo-feature                       # [build_platform != target_platform and target_platform == "win-64"]
```
etc.

</details>

The more dimensions (unix vs win, native vs. cross, python version, CUDA or not, implementation variants for openmpi/BLAS/QT/etc.) we need to cover in a given recipe, the harder it gets to do that with simple `if: else:` branches. Consider something like
```yaml
        build:
          - match: build_platform != target_platform
              # cross-compilation
            match: build_platform != target_platform and cuda_version
              # cross-compiled CUDA
            match: match(cuda, "<12")
              # CUDA 11.x
            match: match(cuda, ">=12.0")
              # CUDA 12.x
            match: linux
              # linux
            match: osx
              # osx
            match: unix
              # unix
            match: win
              # win
            match: blas_impl == "mkl"
              # mkl
```
It would be a much lower mental overhead to be able to freely shuffle around lines based on which sections they apply to, e.g. not having to restructure the following into a correctly (non-)overlapping `if:` statements, only adding lines to the selector where they are supposed to be applied.

**Comment by wolfv** [comment]
It's completely impossible because duplicate keys are forbidden :(

**Comment by h-vetinari** [comment]
> It's completely impossible because duplicate keys are forbidden :(

Well, how about making each `- match:` a separate list entry? That's also how multiple `if:`'s work IIUC.

In other words, the following (note the extra `- ` everywhere)

```yaml
        build:
          - match: build_platform != target_platform
              # cross-compilation
          - match: build_platform != target_platform and cuda_version
              # cross-compiled CUDA
          - match: match(cuda, "<12")
              # CUDA 11.x
          - match: match(cuda, ">=12.0")
              # CUDA 12.x
          - match: linux
              # linux
          - match: osx
              # osx
          - match: unix
              # unix
          - match: win
              # win
          - match: blas_impl == "mkl"
              # mkl
```
... should be desugared to the same list as the impossible variant that has multiple `match:`. The only thing the desugaring would need to learn is to ignore empty lists (for a `match:` that doesn't apply), though I guess that's already covered by the existing infra (e.g. for an `if:` without `else:`)

**Comment by baszalmstra** [comment]
Why not use a top level `match` with nested `case`s?

**Comment by h-vetinari** [comment]
> Why not use a top level `match` with nested `case`s?

I'd be happy with that too!

**Comment by wolfv** [comment]
But how is it different from multiple if statements?

**Comment by baszalmstra** [comment]
You dont need to repeat the negation of the if clauses.

You can more easily write something specific for win, macos, unix without having to repeat not win, etc.

Sorry, im on a phone so its a bit hard to type a proper example.

**Comment by wolfv** [comment]
For the record, it's actually possible to use arbitrary Jinja in multi-line YAML strings. I am not sure if we want to keep it, but the following works (after a small bug fix from #1156):

```yaml
build:
  script: |
    echo "Is ${{ target_platform == "linux-64" }}"
    {% if target_platform == "linux-64" %}
      echo "I AM A LINUX"
    {% elif osx %}
      echo "I AM A MAC"
    {% endif %}
```

And of course, you could just as well use bash.

So I am not sure if it's worth it to make our syntax more complicated or not ... 

Right now it's also possible to do arbitrary things with set and for loops btw. - it just has to be encapsulated in a multi-line string :)

**Comment by baszalmstra** [comment]
One of the design goals was to make the recipe easier to parse for machines. I think what you are suggesting is taking a step back. Having a match-kinda statement seems like a great (and logical) building block.

**Comment by wolfv** [comment]
Yeah but we've never semantically understood the contents of the scripts themselves so I'm not sure if we need that. This doesn't affect the "everything is pure YAML" property.

**Comment by baszalmstra** [comment]
Sure but just as you mentioned in another issue you just closed, we _can_ validate the control flow statements using the schema. That would become harder and harder the more jinja we start using.

**Comment by wolfv** [comment]
If we build our own LSP though .. :) I think I do get your point, but I don't see it super different from e.g. people having issues with their bash scripts inside the script tag.

**Comment by wolfv** [comment]
Where did you set `qemu_bins`?  The `context` has a behvior where it casts everything to a string. 

But if you do:

```
          {% set qemu_bins = ["foo", "bar"] %}
          {% for bin in qemu_bins %}
            test -f ${QEMU_LD_PREFIX}/{{ bin }}
          {% endfor %}

```

It has a chance of working :)

**Comment by h-vetinari** [comment]
> Why not use a top level `match` with nested `case`s?

Actually, one reason why I do have a preference for bare `match:`, is that `match: - case ... -case` suggests disjoint conditions again (at least based on how pattern matching works in most languages), whereas I'd like to not match _one specific thing_ to various disjoint cases, but rather freely match conditions for different quantities that may overlap. Using a different syntax there would avoid triggering some unhelpful muscle memory.

**Comment by wolfv** [comment]
@h-vetinari sorry, not following. What's the difference of `match` then to a number of `if` clauses if the match' clauses are disjoint? I think what we had in mind so far would be a match that breaks after it finds the first matching entry, e.g.

```
match:
  - case: unix
    then: 
      - bla
  - case: win and arm64
    then: 
      - foobar
  - case: win
    then:
      - foobar-win64 # NOT happening on arm64
```
