### ISSUE TITLE
`cmd.exe` stops execution prematurely

### ISSUE THREAD

**Issue by moritzwilksch** [prefix-dev/rattler-build#1165]
## Problem
I have a recipe using `pnpm` (wip over [here](https://github.com/conda-forge/pyright-feedstock/pull/184)) with a build script that calls a pnpm command. For the windows builds (on a local windows machine), the execution during the build process always stops after the first invocation of `pnpm`. For some reason, the issue can be circumvented by `&&`-ing all commands. I already tried messing with different end-of-line sequences but to no avail. The equivalent script on works on linux.

## MRE
```
recipe/
  recipe.yaml
  build.bat
```

```yaml
# build.bat 
pnpm --help

echo "Hello" > %PREFIX%\test.txt
```

```yaml
# recipe.yaml
build:
  number: 0

package:
  name: mypackage
  version: 1.0.0

requirements:
  build:
    - pnpm
  host:
    - nodejs

tests:
  - package_contents:
      files:
        - test.txt
```

results in this (broken?) `conda_build.bat`:

```bat

@chcp 65001 > nul
@echo on
IF "%CONDA_BUILD%" == "" (
    @rem special behavior from conda-build for Windows
    call C:\Users\Administrator\mre\output\bld\rattler-build_mypackage_1730911077\work\build_env.bat
)
@rem re-enable echo because the activation scripts might have messed with it
@echo on

pnpm --help

echo "Hello" > %PREFIX%\test.txt
```

## Fix?
```yaml
# build.bat 
pnpm --help && echo "Hello" > %PREFIX%\test.txt
```
Results in this `conda_bulid.bat`:

```bat

@chcp 65001 > nul
@echo on
IF "%CONDA_BUILD%" == "" (
    @rem special behavior from conda-build for Windows
    call C:\Users\Administrator\mre\output\bld\rattler-build_mypackage_1730911013\work\build_env.bat
)
@rem re-enable echo because the activation scripts might have messed with it
@echo on

pnpm --help && echo "Hello" > %PREFIX%\test.txt
```
