### ISSUE TITLE
Python tests should allow custom requirements

### ISSUE THREAD

**Issue by hadim** [prefix-dev/rattler-build#1168]
I think the python tests should allow custom deps spec. For example, in [this feedstock]() I need to set the python version of a noarch package and it is not allowed:

```yaml 
tests:
  - python:
      imports:
        - pptx
      requirements:
        run:
          - python =${{ python_min }}
 ```

so I had to replace it with:

```yaml 
tests:
  - script:
      - python -c "import pptx"
    requirements:
      run:
        - python =${{ python_min }}
 ```

---

What do you think is the best way to address this?

1) allow `requirements` or `requirements.run`?
2) add `python_version` so only the python version can be customized?

Let me know, what you think is best here and I can submit a PR if you want.
