### ISSUE TITLE
recipe pins appear to be implemented incorrectly relative to conda-build

### ISSUE THREAD

**Issue by beckermr** [prefix-dev/rattler-build#1174]
It appears that for a bit of yaml like this

```yaml
requirements
  run:
    - python ${{ python_min }}
```

with `python_min=3.10`, rattler produces a different spec than conda-build. 

For rattler-build, I see 

```yaml
requirements:
  run:
    - python ==3.10
```

See this CI job (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1075636&view=logs&jobId=7b6f2c87-f3a7-5133-8d84-7c03a75d9dfc&j=7b6f2c87-f3a7-5133-8d84-7c03a75d9dfc&t=9eb77fd2-8ddd-5444-8fc0-71cb28dcb736)

conda-build adds an implicit `.*` like this

```yaml
requirements:
  run:
    - python 3.10.*
```

For a pin like 3.10, the net effect of `.*` for conda-build is to pull the latest version that is less than the next minor version (i.e., 3.11.0). An equivalent syntax, I think, is `python =3.10` (i.e., a single `=`). rattler-build could use a single `=` if it does not handle `.*`
