### ISSUE TITLE
rattler-build creates empty packages with pip install script

### ISSUE THREAD

**Issue by llohse** [prefix-dev/rattler-build#1200]
I have been trying out rattler-build. My goal is to eventually run it in Gitlab CI to build new conda packages for our Python module whenever a new tag is pushed.

Running `rattler-build build --experimental --recipe conda/recipe.yaml --output-dir ~/rattler-cache/` produces conda packages (I tried .conda and .tar.bz2) with all the metadata **but without the actual Python modules**.
It runs through and reports success.
Running `pip install` manually works fine as expected, using setuptools and PEP 517: it installs the Python module. Disabling build isolation also works.

Im a running rattler-build 0.30.0 from a vanilla micromamba environment that contains only rattler-build (and its dependencies) on Fedora 40:
`rattler-build build --experimental --recipe conda/recipe.yaml --output-dir ~/rattler-cache/`
(It is called from within a clone of the project repository, so the most recent pyproject.toml is in the current working directory).

The outcome is the same with source from git or from a local path (manually cloned repository).

It looks like somehow the new-file detection fails.

Please advice.

The recipe looks like this.
```YAML
# conda/recipe.yaml
context:
  git_repo_url: ${{ load_from_file("pyproject.toml").project.urls.repository }}
#  latest_tag: ${{ git.latest_tag( git_repo_url ) }}
#  version: ${{ latest_tag[1:] }} # drop leading v 
  version: ${{ load_from_file("pyproject.toml").project.version }}

package:
  name: ${{ load_from_file("pyproject.toml").project.name }} 
  version: ${{ version }}

source:
#  path: ..
#  use_gitignore: true
  git: ${{ git_repo_url }}
  tag: "v${{ version }}"

build:
  noarch: python
#  script: python -m pip install --no-deps --no-build-isolation --ignore-installed -vv .
  script: python -m pip install --no-deps --ignore-installed -vv .

requirements:
  build:
    - pip
    - wheel # for --no-build-isolation
    - setuptools # for --no-build-isolation
  host:
    - python
  run:
    - numpy < 2

about:
  homepage:  ${{ load_from_file("pyproject.toml").project.urls.homepage }}
  repository: ${{ git_repo_url }}
  license: GPL-3.0-or-later 
  summary: ${{ load_from_file("pyproject.toml").project.description }}
```
