### ISSUE TITLE
cache: variant computation produces too few variants

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#1223]
Something like:

```
cache:
  requirements:
    host:
      - python

...
```

With a variants file of 

```
python: ['3.9', '3.10']
```

should create 2 x N-outputs variants.
