### ISSUE TITLE
Allow to exclude test files from conda package

### ISSUE THREAD

**Issue by borchero** [prefix-dev/rattler-build#1228]
Currently, whenever a recipe specifies test files, these test files end up in the final conda package. For example,

```yaml
source:
  path: ../
build:
  number: 0
  noarch: python
package:
  name: test
  version: v1
requirements:
  run:
    - python >=3.9
tests:
  - script: test -f foo.txt
    files:
      source:
        - foo.txt
```

causes `foo.txt` to end up in `/etc/conda/test-files/test/0` of the final package.

In some cases, it would be desirable to not include these test files into the final package. Would it be possible to introduce a flag to prevent this behavior?

---

@pavelzw suggested that this might even make sense to do when `--no-include-recipe` is specified, I personally can't comment on that in detail :smile:
