### ISSUE TITLE
Add strict mode for `package_contents` tests

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#1258]
As discussed in [https://github.com/conda/ceps/pull/57#issuecomment-1842373079](https://github.com/conda/ceps/pull/57#issuecomment-1842373079), [https://github.com/conda/ceps/pull/84](https://github.com/conda/ceps/pull/84), it would be nice if rattler-build supported a `strict` mode for package contents tests.

Under the strict mode, any non-matched files or any missing files would trigger an error.

The strict mode could look like:

```
package_contents:
  strict: true / false (default to false)
  files:
    - include/xtensor/*
```

With this example, any extra files would error.
