### ISSUE TITLE
Allow `MatchSpec` in `run_exports.from_package`

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#1264]
Currently we don't allow matchspecs in the `run_exports.from_package` list. We only allow literal `PackageName`.

Sometimes when templating it's easier to just use a matchspec, for example:

```
requirements:
  ignore_run_exports:
    from_package:
       - ${{ compiler('cxx') }}
```

To support this, we should consider to also allow MatchSpecs in this section.
