### ISSUE TITLE
Multi-output file selection not working

### ISSUE THREAD

**Issue by carterbox** [prefix-dev/rattler-build#1290]
As described [in the docs](https://rattler.build/latest/multiple_output_cache/#the-cache-for-multiple-outputs), I should be able to split a cache package with globs using `build.files`. However, my outputs is empty.

```
(rattler) bash-5.2$ rattler-build --version
rattler-build 0.33.1

```

Recipe [in a fork of the dav1d-feedstock.](https://github.com/carterbox/dav1d-feedstock/tree/rattler)

**Comment by wolfv** [comment]
Strange! 
I just tried to replicate your situation as accurately as possible (I am on macOS):

```yaml
recipe:
  name: foo
  version: 0.1.0

cache:
  build:
    script:
      - mkdir -p $PREFIX/lib
      - mkdir -p $PREFIX/include
      - touch $PREFIX/include/test.h
      - touch $PREFIX/lib/libtest.so
      - touch $PREFIX/lib/libtest.so.2
      - touch $PREFIX/lib/libtest.so.2.1.4
      - touch $PREFIX/lib/libdav1d.so.7.0.0
      - ln -s $PREFIX/lib/libdav1d.so.7.0.0 $PREFIX/lib/libdav1d.so.7
      - ln -s $PREFIX/lib/libdav1d.so.7 $PREFIX/lib/libdav1d.so


outputs:
  - package:
      name: testlib-so-version
      version: 2.1.4
    build:
      files:
        include:
          - if: osx  # NOTE: change here to linux if you are on Linux
            then: lib/*.so.*
```

And this produces the expected packages for me:

```
 │ ╭─ Packaging new files
 │ │ Copying done!
 │ │ Post-processing done!
 │ │ Writing test files
 │ │ Writing metadata for package
 │ │ Copying license files
 │ │ Copying recipe files
 │ │ Creating entry points
 │ │ 
 │ │ Files in package:
 │ │   - lib/libdav1d.so.7
 │ │   - lib/libdav1d.so.7.0.0
 │ │   - lib/libtest.so.2
 │ │   - lib/libtest.so.2.1.4
 │ │   - info/about.json
 │ │   - info/hash_input.json
 │ │   - info/index.json
 │ │   - info/paths.json
 │ │   - info/recipe/recipe.yaml
 │ │   - info/recipe/rendered_recipe.yaml
 │ │   - info/recipe/variant_config.yaml
 │ │   - info/tests/tests.yaml
 │ │ Creating target folder '/Users/wolfv/Programs/rattler-build/output/osx-arm64'
 │ │ Compressing archive...
 │ │ Archive written to '/Users/wolfv/Programs/rattler-build/output/osx-arm64/testlib-so-version-2.1.4-h60d57d3_0.conda'
 │ │
 │ ╰─────────────────── (took 0 seconds)
```

**Comment by carterbox** [comment]
```yaml
recipe:
  name: foo
  version: 0.1.0

cache:
  build:
    script:
      - mkdir -p $PREFIX/lib
      - mkdir -p $PREFIX/include
      - touch $PREFIX/include/test.h
      - touch $PREFIX/lib/libtest.so
      - touch $PREFIX/lib/libtest.so.2
      - touch $PREFIX/lib/libtest.so.2.1.4
      - touch $PREFIX/lib/libdav1d.so.7.0.0
      - ln -s $PREFIX/lib/libdav1d.so.7.0.0 $PREFIX/lib/libdav1d.so.7
      - ln -s $PREFIX/lib/libdav1d.so.7 $PREFIX/lib/libdav1d.so
  requirements:
    build:
      # Files not included correctly when compiler template added here
      # - ${{ compiler('c') }}
      - ninja

outputs:
  - package:
      name: testlib-so-version
      version: 2.1.4
    build:
      files:
        include:
          - lib/*.so.*
```
