### ISSUE TITLE
Broken Windows packaging of python libraries

### ISSUE THREAD

**Issue by stefdoerr** [prefix-dev/rattler-build#1297]
Building [my python package](https://github.com/acellera/moleculekit) on Windows fails because the "Packaging new files" section does not copy the actual files into the package. It works correctly on Linux and OSX though with the identical command. Something is broken in how the files are copied in Windows. This of course produces a broken build since the archive does not contain the python module and the tests do not pass.

```sh
rattler-build build --recipe ./package/moleculekit/recipe.yaml --output-dir ../pkg/ --no-include-recipe -c acellera -c conda-forge
```

![Image](https://github.com/user-attachments/assets/a2137d8c-44e8-4467-b140-9a5a1ef3e46c)
![Image](https://github.com/user-attachments/assets/962b911d-a9df-4773-a0c2-5931b1cace8a)

```yaml
about:
  homepage: https://software.acellera.com/moleculekit/
  license: LicenseRef-HTMD
  license_file: LICENSE
  summary: 
build:
  script:
  - pip install . -vv
extra:
  recipe-maintainers:
  - stefdoerr
package:
  name: moleculekit
  version: 1.9.26+2.g85b183a.dirty
requirements:
  build:
  - ${{ compiler('c') }}
  - ${{ compiler('cxx') }}
  - cython >=0.29.21
  - pip
  - python
  - versioneer==0.29
  - setuptools
  - python-build
  - numpy >=2.0.0rc1
  run:
  - python
  - numpy>=1.23.5
  - pandas>=1.1.2
  - networkx
  - tqdm
  - msgpack-python
  - requests
source:
  path: ../..
tests:
- python:
    imports:
    - moleculekit
    pip_check: false
```
