### ISSUE TITLE
Multiple output cache conflicts with the --keep-build option

### ISSUE THREAD

**Issue by fecet** [prefix-dev/rattler-build#1301]
```yaml
recipe:
  name: foo
  version: 0.1.0

cache:
  build:
    script:
      - mkdir -p $PREFIX/lib
      - mkdir -p $PREFIX/include
      - touch $PREFIX/include/test.h
      - touch $PREFIX/lib/libdav1d.so.7.0.0
      - ln -s $PREFIX/lib/libdav1d.so.7.0.0 $PREFIX/lib/libdav1d.so.7
      - ln -s $PREFIX/lib/libdav1d.so.7 $PREFIX/lib/libdav1d.so

  requirements:
    build:
      - ${{ compiler('c') }}

outputs:
  - package:
      name: testlib-so-version

    build:
      files:
        include:
          - lib/*.so.*
  - package:
      name: testlib-headers

    build:
      files:
        include:
          - include/*.h
```
