### ISSUE TITLE
Cross-compilation fails with `ERROR: CONDA_BUILD_WINSDK has to be set for cross-compiling`

### ISSUE THREAD

**Issue by MartinJepsen** [prefix-dev/rattler-build#1303]
Possibly related to #812.

### Context

I am cross-compiling a mixed Python-Rust project using Pyo3 and maturin. I want to cross compile from WSL Ubuntu 24-04 to Windows.

#### Set-up steps I've done

- Add Windows target for the Rust compiler with

  ```shell
  rustup target add x86_64-pc-windows-gnu
  ```

- Install Windows compilation tools:

  ```shell
  sudo apt install mingw-w64
  ```

- Run the build with 

  ```shell
  rattler-build build --recipe-dir $REPO_ROOT/pyanif/build --output-dir $BUILD_OUTPUT
  ```

  where `$REPO_ROOT` is the root of this repository and `$BUILD_OUTPUT` is the a directory containing the generated conda package(s).

#### Build recipe

`recipe.yaml`:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: pyanif
  version: "0.1.0"
  build_str: ${{ env.get("COMMIT_HASH") }}

package:
  name: ${{ name }}
  version: ${{ version }}

build:
  number: 0
  string: ${{ build_str }}


# Relative file-system paths are resolved with respect to the recipe's parent directory
source:
  path: ../../


requirements:
  build:
  - ${{ compiler('rust') }}
  - maturin
  host:
  - python
  - setuptools
  - pip
  run:
  - python>=3.9
```

`variants.yaml`:

```yaml
python:
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"
```

`build.sh`:

```bash
#! /usr/bin/env bash

# Run this from the pyanif/ directory
#
# This build script only runs if the host platform is linux
# For windows as host platform, see the build.bat file if it exists.



echo "Building on $(rustc --version)"
echo "Python version: $($PYTHON --version)"
echo "Build platform: ${build_platform}"
echo "Target platform: ${target_platform}"

# if [[ "{$target_platform}" == "linux-64" ]]; then
#     echo Building for linux-64
# fi

if [[ ("{$target_platform}" == "win-64" && "${build_platform}" == "linux-64") ]]; then
    maturin build --release --target x86_64-pc-windows-gnu
    pip install target/wheels/pyanif*.whl --target $PREFIX/lib/site-packages --platform win_amd64
else
    maturin build --release
    pip install target/wheels/pyanif*.whl --target $PREFIX/lib/site-packages
fi
```

### The problem

The build fails with this error message:

```raw
 │ Installing build environment
 │ ✔ Successfully updated the build environment
 │ 
 │ Installing host environment
 │ ✔ Successfully updated the host environment
 │
 │ ╭─ Running build script
 │ │ ERROR: CONDA_BUILD_WINSDK has to be set for cross-compiling
 │ │ INFO: activate-clang_win-64.sh made the following environmental changes:
 │ │ +AR=$BUILD_PREFIX/bin/llvm-ar
 │ │ +AS=$BUILD_PREFIX/bin/x86_64-pc-windows-msvc19.42.34433-as
 │ │ +CC=x86_64-pc-windows-msvc19.42.34433-clang
 │ │ +CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fstack-protector-strong -O2 -ffunction-sections -pipe -D_CRT_SECURE_
 │ │ NO_WARNINGS --target=x86_64-pc-windows-msvc19.42.34433 -nostdlib -fms-runtime-lib=dll -fuse-ld=lld -fno-aligned-allocation
 │ │ +CLANG=$BUILD_PREFIX/bin/x86_64-pc-windows-msvc19.42.34433-clang
 │ │ +CMAKE_PREFIX_PATH=$PREFIX/include;/msvc-14.42.34433/include;/winsdk-10.0.22621.0/include/ucrt;/winsdk-10.0.22621.0/include
 │ │ /shared;/winsdk-10.0.22621.0/include/um;/winsdk-10.0.22621.0/include/winrt;$PREFIX/lib;/winsdk-10.0.22621.0/lib/ucrt/x64;/w
 │ │ insdk-10.0.22621.0/lib/um/x64;/msvc-14.42.34433/lib/x64
 │ │ +CPPFLAGS=-D_CRT_SECURE_NO_WARNINGS --target=x86_64-pc-windows-msvc19.42.34433 -nostdlib -fms-runtime-lib=dll -fuse-ld=lld 
 │ │ -fno-aligned-allocation
 │ │ +HOST=x86_64-pc-windows-msvc19.42.34433
 │ │ +INCLUDE=$PREFIX/include;/msvc-14.42.34433/include;/winsdk-10.0.22621.0/include/ucrt;/winsdk-10.0.22621.0/include/shared;/w
 │ │ insdk-10.0.22621.0/include/um;/winsdk-10.0.22621.0/include/winrt
 │ │ +LD=$BUILD_PREFIX/bin/lld-link
 │ │ +LDFLAGS=--target=x86_64-pc-windows-msvc19.42.34433 -nostdlib -Wl,-defaultlib:$BUILD_PREFIX/lib/clang/19/lib/windows/clang_
 │ │ rt.builtins-x86_64.lib
 │ │ +LIB=$PREFIX/lib;/winsdk-10.0.22621.0/lib/ucrt/x64;/winsdk-10.0.22621.0/lib/um/x64;/msvc-14.42.34433/lib/x64
 │ │ +LT_CV_DEPLIBS_CHECK_METHOD=pass_all
 │ │ +NM=$BUILD_PREFIX/bin/llvm-nm
 │ │ +RANLIB=$BUILD_PREFIX/bin/llvm-ranlib
 │ │ -INCLUDE=$PREFIX/Library/include;
 │ │ -LIB=$PREFIX/Library/lib;
 │ │ CONDA_BUILD_WINSDK is not set.
 │ │ CONDA_BUILD_WINSDK is not set.
 │ │ × error Script failed with status 1
 │ │ × error Work directory: '/home/majp/rattler-build/channel/bld/rattler-build_pyanif_1736115126/work'
 │ │ × error To debug the build, run it manually in the work directory (execute the `./conda_build.sh` or `conda_build.bat` scrip
 │ │ × error t)
 │ │
 │ ╰─────────────────── (took 0 seconds)
 │
 ╰─────────────────── (took 3 seconds)
Error: 
  × Script failed
```

Please let me know if you need further insights into the scripts in the build directory.

I did notice that there are some references to `--target=x86_64-pc-windows-msvc19.42.34433`, but I'm using `--target x86_64-pc-windows-gnu` for the Rust target. Could this be the problem?
