### ISSUE TITLE
variant env vars not set for test scripts

### ISSUE THREAD

**Issue by minrk** [prefix-dev/rattler-build#1317]
In conda-build, variant values are set as env vars in build and test scripts. #1056 reported this for build scripts which appears to be fixed by #1088, but only for build scripts. Test scripts appear to still lack these env vars.

I can work around this with:

```yaml
test:
  script:
    file: script-name
    env:
      name: ${{ name }}
```

for any variables I use in the test, but I'm not sure if the inconsistency is intentional.
