### ISSUE TITLE
Builds run but test fails when package name has a mixed-case name

### ISSUE THREAD

**Issue by zachcp** [prefix-dev/rattler-build#1329]
- Initial issue [here](https://discord.com/channels/1082332781146800168/1327290073124962324/1327290073124962324)

```yaml
# good
package:
  name: pypept
  version: "1.0"


# no good
package:
  name: pyPept
  version: "1.0"
```
