### ISSUE TITLE
` error Command failed: git rev-parse "refs/tags/v1.15.3"` error during c-f Windows Azure CI build

### ISSUE THREAD

**Issue by hadim** [prefix-dev/rattler-build#1376]
When using a git source:

```yaml
source:
  git: https://github.com/lightvector/KataGo.git
  tag: v${{ version }}
```

There is an error on the c-f Windows Azure CI:

```
│ ╭─ Fetching source code
 │ │ Fetching source from git repo: https://github.com/lightvector/KataGo.git
 │ │ Fetching repository from https://github.com/lightvector/KataGo.git at refs/tags/v1.15.3 into D:\bld\src_cache\KataGo.git
 │ │ × error Command failed: `git rev-parse "refs/tags/v1.15.3"`
```

Note that the other platforms works fine. I also tested with a different github repo and tag and it fails as well.

See the original PR on the feedstock at https://github.com/conda-forge/katago-feedstock/pull/11
