### ISSUE TITLE
How to generate cuda variant?

### ISSUE THREAD

**Issue by hadim** [prefix-dev/rattler-build#1377]
I am trying to build a cuda recipe (without c-f logic) but using a subset of the cbc that I have converted to rattler-build:

```yaml
# Sync with https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

# zip keys: https://rattler.build/latest/variants/#zip-keys

zip_keys:
  # C/CXX/CUDA compilers
  - - ${{ "c_compiler_version" if unix }}
    - ${{ "cxx_compiler_version" if unix }}
    - if: env.get("CF_CUDA_ENABLED", default="False") == "True"
      then:
        - ${{ "cuda_compiler" if linux }}
        - ${{ "cuda_compiler_version" if linux }}

  # C/CXX/CUDA compilers on Windows
  - if: (win and x86_64) and env.get("CF_CUDA_ENABLED", default="False") == "True"
    then:
      - cuda_compiler
      - cuda_compiler_version

  # Python
  - - python
    - numpy
    - python_impl

# stdlib

c_stdlib:
  - ${{ "sysroot" if linux }}
  - ${{ "macosx_deployment_target" if osx }}
  - ${{ "vs" if win }}

c_stdlib_version:
  - ${{ "2.17" if linux }}
  - ${{ "10.13" if osx and x86_64 }}
  - ${{ "11.0" if osx and arm64 }}

# C compiler

c_compiler:
  - ${{ "gcc" if linux }}
  - ${{ "clang" if osx }}
  - ${{ "vs2019" if win and x86_64 }}
  - ${{ "vs2022" if win and arm64 }}

c_compiler_version:
  - ${{ "13" if linux }}
  - ${{ "18" if osx }}
  - if: env.get("CF_CUDA_ENABLED", default="False") == "True"
    then:
      - ${{ "11" if linux }}
      - ${{ "12" if linux and ppc64le }}
      - ${{ "13" if linux and not ppc64le }}

# CXX compiler

cxx_compiler:
  - ${{ "gxx" if linux }}
  - ${{ "clangxx" if osx }}
  - ${{ "vs2019" if win and x86_64 }}
  - ${{ "vs2022" if win and arm64 }}

cxx_compiler_version:
  - ${{ "13" if linux }}
  - ${{ "18" if osx }}
  - if: env.get("CF_CUDA_ENABLED", default="False") == "True"
    then:
      - ${{ "11" if linux }}
      - ${{ "12" if linux and ppc64le }}
      - ${{ "13" if linux and not ppc64le }}

# Cuda compiler

cuda_compiler:
  - None
  - if: env.get("CF_CUDA_ENABLED", default="False") == "True"
    then:
      - ${{ "nvcc" if linux or (win and x86_64) }}
      - ${{ "cuda-nvcc" if linux or (win and x86_64) }}

cuda_compiler_version:
  - None
  - if: env.get("CF_CUDA_ENABLED", default="False") == "True"
    then:
      - ${{ "11.8" if linux or (win and x86_64) }}
      - ${{ "12.4" if linux and ppc64le }}
      - ${{ "12.6" if (linux and not ppc64le) or (win and x86_64) }}

# Rust compiler

rust_compiler:
  - rust

# Python

python:
  # part of a zip_keys: python, python_impl, numpy
  - 3.12.* *_cpython

python_impl:
  # part of a zip_keys: python, python_impl, numpy
  - cpython

python_min:
  # minimum supported python version per CFEP-25
  # bump to next minor version when we drop python versions
  - "3.12"

# we build for the oldest version possible of numpy for forward compatibility
# we roughly follow NEP29 in choosing the oldest version
numpy:
  # part of a zip_keys: python, python_impl, numpy
  - 1.26
```

As you can see, the cuda logic relies on `CF_CUDA_ENABLED` being set. While I can find the logic in `conda-smithy`:

https://github.com/conda-forge/conda-smithy/blob/2fd6afc0c78de475a82b153810e7ab7b3cc957d9/conda_smithy/configure_feedstock.py#L1044-L1048

I cannot find it in `rattler-build`.

My guess is that `CF_CUDA_ENABLED` is specific to c-f. If it is, do you know what would the best way to enable cuda variants in the above variant file?

**Comment by wolfv** [comment]
Do you need the logic with env variables? You could probably get it to work without.

Since the latest few releases we also have a `conda_build_config.yaml` parser so potentially even upstream conda-forge pins "work".

I had this code at some point: https://github.com/prefix-dev/ai-forge/pull/2

Which relied on

```
        - if: cuda
          then:
            - ${{ compiler('cuda') }}
```

**Comment by hadim** [comment]
I think I am confused how `${{ compiler('cuda/c/cxx/etc') }}` can works without being set in a variant file somewhere? How does rattler-build know which package to use? I feel I am missing a very obvious point here :-)


I am also trying to use the same compiler version as the ones in c-f.

**Comment by hadim** [comment]
My bad here as I think I just got confused by this `CF_CUDA_ENABLED` variable but indeed it seems to be very c-f specific and is not really needed.

So the below variant file works just fine and generate all the correct cuda variants:

```yaml
# Sync with https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

# zip keys: https://rattler.build/latest/variants/#zip-keys

zip_keys:
  # C/CXX/CUDA compilers
  - - ${{ "c_compiler_version" if unix }}
    - ${{ "cxx_compiler_version" if unix }}
    - ${{ "cuda_compiler" if linux }}
    - ${{ "cuda_compiler_version" if linux }}

  # C/CXX/CUDA compilers on Windows
  - if: win and x86_64
    then:
      - cuda_compiler
      - cuda_compiler_version

  # Python
  - - python
    - numpy
    - python_impl

# stdlib

c_stdlib:
  - ${{ "sysroot" if linux }}
  - ${{ "macosx_deployment_target" if osx }}
  - ${{ "vs" if win }}

c_stdlib_version:
  - ${{ "2.17" if linux }}
  - ${{ "10.13" if osx and x86_64 }}
  - ${{ "11.0" if osx and arm64 }}

# C compiler

c_compiler:
  - ${{ "gcc" if linux }}
  - ${{ "clang" if osx }}
  - ${{ "vs2019" if win and x86_64 }}
  - ${{ "vs2022" if win and arm64 }}

c_compiler_version:
  - ${{ "13" if linux }}
  - ${{ "18" if osx }}
  - ${{ "11" if linux }}
  - ${{ "12" if linux and ppc64le }}
  - ${{ "13" if linux and not ppc64le }}

# CXX compiler

cxx_compiler:
  - ${{ "gxx" if linux }}
  - ${{ "clangxx" if osx }}
  - ${{ "vs2019" if win and x86_64 }}
  - ${{ "vs2022" if win and arm64 }}

cxx_compiler_version:
  - ${{ "13" if linux }}
  - ${{ "18" if osx }}
  - ${{ "11" if linux }}
  - ${{ "12" if linux and ppc64le }}
  - ${{ "13" if linux and not ppc64le }}

# Cuda compiler

cuda_compiler:
  - None
  - ${{ "nvcc" if linux or (win and x86_64) }}
  - ${{ "cuda-nvcc" if linux or (win and x86_64) }}

cuda_compiler_version:
  - None
  - ${{ "11.8" if linux or (win and x86_64) }}
  - ${{ "12.4" if linux and ppc64le }}
  - ${{ "12.6" if (linux and not ppc64le) or (win and x86_64) }}

# Rust compiler

rust_compiler:
  - rust

# Python

python:
  # part of a zip_keys: python, python_impl, numpy
  - 3.11.* *_cpython
  - 3.12.* *_cpython

python_impl:
  # part of a zip_keys: python, python_impl, numpy
  - cpython
  - cpython

# we build for the oldest version possible of numpy for forward compatibility
# we roughly follow NEP29 in choosing the oldest version
numpy:
  # part of a zip_keys: python, python_impl, numpy
  - 1.26
  - 1.26

python_min:
  # minimum supported python version per CFEP-25
  # bump to next minor version when we drop python versions
  - "3.12"
```
