### ISSUE TITLE
WHL Files seem not to be available in the test environment.

### ISSUE THREAD

**Issue by zachcp** [prefix-dev/rattler-build#1422]
```yaml
package:
  name: bpy
  version: "4.3.0"

source:
  - if: win64
    then:
      url: "https://files.pythonhosted.org/packages/7f/da/c255b626cab58c69c49f4a65d0410b36aa1086dc63862d1c3de653f0a5a0/bpy-4.3.0-cp311-cp311-win_amd64.whl"
      sha256: 1a7b2c516aa7a95c31fcaae8842addd07fa86c1ce4768e88a34b480d17e2e93a
  - if: linux64
    then:
      url: "https://files.pythonhosted.org/packages/9c/4d/897bf3c247d7c6a4e75397f4c5dd5d201fb147981d2271ac35ac955959ab/bpy-4.3.0-cp311-cp311-manylinux_2_28_x86_64.whl"
      sha256: 1620199392a7e7aab58672aa47c50b3c5b1e4d39d46af5a7f9bbe2af561ea942
  - if: osx and x86_64
    then:
      url: "https://files.pythonhosted.org/packages/81/39/4e763b150ff05412ab25d5eae91da7f0ade474b5d66509b39a67066d35ec/bpy-4.3.0-cp311-cp311-macosx_11_0_x86_64.whl"
      sha256: 490aa94699664a99eee755047485a3ad70470fc6267c55a73459660f52299ade
  - if: osx and arm64
    then:
      url: "https://files.pythonhosted.org/packages/c1/fc/5902fa508a13f4f1669bc2e2cd8f37adf1caeeed0a344f627c0ffc3bdc40/bpy-4.3.0-cp311-cp311-macosx_11_0_arm64.whl"
      sha256: 82c3486e9762e8cfce4bbc1d6752f5625da8515f6b217e02810350627d693897

build:
  number: 0
  script: pip install --no-deps *.whl -v

requirements:
  build:
    - python =3.11
    - pip
    - wheel
  host:
    - python =3.11
    - pip
    - wheel
  run:
    - python =3.11

tests:
  - python:
      imports:
        - bpy

about:
  homepage: https://pypi.org/project/bpy/
  license: GPL-3.0
  summary: Blender as a Python Module
```

Yields: 

```sh
rattler-build build

...

 │ Installing build environment
 │ ✔ Successfully updated the build environment
 │
 │ Installing host environment
 │ ✔ Successfully updated the host environment
 │
 │ ╭─ Running build script
 │ │ + pip install --no-deps bpy-4.3.0-cp311-cp311-macosx_11_0_arm64.whl -v
 │ │ Using pip 25.0.1 from $BUILD_PREFIX/lib/python3.11/site-packages/pip (python 3.11)
 │ │ Processing ./bpy-4.3.0-cp311-cp311-macosx_11_0_arm64.whl
 │ │ Installing collected packages: bpy
 │ │ Successfully installed bpy-4.3.0
 │ │
 │ ╰─────────────────── (took 10 seconds)
 │
 │ ╭─ Packaging new files
 │ │ Copying done!
 │ │ ⚠ warning Overdepending against python_abi
 │ │ Post-processing done!
 │ │ Writing test files
 │ │ Writing metadata for package
 │ │ Copying license files
 │ │ Copying recipe files
 │ │ Ignoring output dir in recipe folder: /Users/zcpowers/Documents/Projects/staged-recipes/recipes/bpy/output
 │ │ Creating entry points
 │ │
 │ │ Files in package:
 │ │   - info/about.json
 │ │   - info/hash_input.json
 │ │   - info/index.json
 │ │   - info/paths.json
 │ │   - info/recipe/recipe.yaml
 │ │   - info/recipe/rendered_recipe.yaml
 │ │   - info/recipe/variant_config.yaml
 │ │   - info/tests/tests.yaml
 │ │ Creating target folder '/Users/zcpowers/Documents/Projects/staged-recipes/recipes/bpy/output/osx-arm64'
 │ │ Compressing archive...
 │ │ Archive written to '/Users/zcpowers/Documents/Projects/staged-recipes/recipes/bpy/output/osx-arm64/bpy-4.3
 │ │ .0-h60d57d3_0.conda'
 │ │
 │ ╰─────────────────── (took 1 second)
 │
 ╰─────────────────── (took 13 seconds)
 Removing previously cached package '/Users/zcpowers/Library/Caches/rattler/cache/pkgs/bpy-4.3.0-h60d57d3_0'
 Creating test environment in '/Users/zcpowers/Documents/Projects/staged-recipes/recipes/bpy/output/bld/rattler
 -build_bpy_1739295577/work/test'
 Collecting tests from '/Users/zcpowers/Library/Caches/rattler/cache/pkgs/bpy-4.3.0-h60d57d3_0'

 ╭─ Running python test(s)
 │
 │ ╭─ Testing with default python version
 │ │
 │ │ Resolving test environment:
 │ │   Platform: osx-arm64 [__unix=0=0, __osx=15.3=0, __archspec=1=m1]
 │ │   Channels:
 │ │    - file:///var/folders/5m/nnqc8qr11hbglqw0j763vtv80000gn/T/.tmpe765F5/
 │ │    - file:///Users/zcpowers/Documents/Projects/staged-recipes/recipes/bpy/output/
 │ │    - conda-forge
 │ │   Specs:
 │ │    - bpy ==4.3.0 h60d57d3_0
 │ │    - pip
 │ │
 │ │ ╭─────────────────┬───────────┬────────────────────┬─────────────┬────────────╮
 │ │ │ Package         ┆ Version   ┆ Build              ┆ Channel     ┆ Size       │
 │ │ ╞═════════════════╪═══════════╪════════════════════╪═════════════╪════════════╡
 │ │ │ bpy             ┆ 4.3.0     ┆ h60d57d3_0         ┆ .tmpe765F5  ┆ 4.50 KiB   │
 │ │ │ bzip2           ┆ 1.0.8     ┆ h99b78c6_7         ┆ conda-forge ┆ 120.03 KiB │
 │ │ │ ca-certificates ┆ 2025.1.31 ┆ hf0a4a13_0         ┆ conda-forge ┆ 154.71 KiB │
 │ │ │ libexpat        ┆ 2.6.4     ┆ h286801f_0         ┆ conda-forge ┆ 63.18 KiB  │
 │ │ │ libffi          ┆ 3.4.6     ┆ h1da3d7d_0         ┆ conda-forge ┆ 35.52 KiB  │
 │ │ │ liblzma         ┆ 5.6.4     ┆ h39f12f2_0         ┆ conda-forge ┆ 96.63 KiB  │
 │ │ │ libsqlite       ┆ 3.48.0    ┆ h3f77e49_1         ┆ conda-forge ┆ 832.84 KiB │
 │ │ │ libzlib         ┆ 1.3.1     ┆ h8359307_2         ┆ conda-forge ┆ 45.35 KiB  │
 │ │ │ ncurses         ┆ 6.5       ┆ h5e97a16_3         ┆ conda-forge ┆ 778.35 KiB │
 │ │ │ openssl         ┆ 3.4.0     ┆ h81ee809_1         ┆ conda-forge ┆ 2.80 MiB   │
 │ │ │ pip             ┆ 25.0.1    ┆ pyh8b19718_0       ┆ conda-forge ┆ 1.20 MiB   │
 │ │ │ python          ┆ 3.11.11   ┆ hc22306f_1_cpython ┆ conda-forge ┆ 13.97 MiB  │
 │ │ │ python_abi      ┆ 3.11      ┆ 5_cp311            ┆ conda-forge ┆ 6.16 KiB   │
 │ │ │ readline        ┆ 8.2       ┆ h92ec313_1         ┆ conda-forge ┆ 244.48 KiB │
 │ │ │ setuptools      ┆ 75.8.0    ┆ pyhff2d567_0       ┆ conda-forge ┆ 757.42 KiB │
 │ │ │ tk              ┆ 8.6.13    ┆ h5083fa2_1         ┆ conda-forge ┆ 3.00 MiB   │
 │ │ │ tzdata          ┆ 2025a     ┆ h78e105d_0         ┆ conda-forge ┆ 120.04 KiB │
 │ │ │ wheel           ┆ 0.45.1    ┆ pyhd8ed1ab_1       ┆ conda-forge ┆ 61.46 KiB  │
 │ │ ╰─────────────────┴───────────┴────────────────────┴─────────────┴────────────╯
 │ │
 │ │ Installing test environment
 │ │ ✔ Successfully updated the test environment
 │ │ + python $SRC_DIR/conda_build_script.py
 │ │ Traceback (most recent call last):
 │ │   File "$SRC_DIR/conda_build_script.py", line 1, in <module>
 │ │     import bpy
 │ │ ModuleNotFoundError: No module named 'bpy'
 │ │ × error Script failed with status 1
 │ │ × error Work directory: '/var/folders/5m/nnqc8qr11hbglqw0j763vtv80000gn/T/.tmp7WcM2c'
 │ │ × error To debug the build, run it manually in the work directory (execute the `./conda_build.sh` or `conda
 │ │ × error _build.bat` script)
 │ │
 │ ╰─────────────────── (took 1 second)
 │
 ╰─────────────────── (took 1 second)
Error:
  × failed to run test: Script failed

```

Note the bpy files show up as ~5KB but are actually ~350MB binaries.

**Comment by zachcp** [comment]
Looks like the WHL-install steps are documented here:
https://docs.conda.io/projects/conda-build/en/stable/user-guide/wheel-files.html

**Comment by zachcp** [comment]
```yaml
build:
  number: 0
  script:
    - if: win64
      then: pip install --no-deps https://files.pythonhosted.org/packages/7f/da/c255b626cab58c69c49f4a65d0410b36aa1086dc63862d1c3de653f0a5a0/bpy-4.3.0-cp311-cp311-win_amd64.whl
    - if: linux64
      then: pip install --no-deps https://files.pythonhosted.org/packages/9c/4d/897bf3c247d7c6a4e75397f4c5dd5d201fb147981d2271ac35ac955959ab/bpy-4.3.0-cp311-cp311-manylinux_2_28_x86_64.whl
    - if: osx and x86_64
      then: pip install --no-deps https://files.pythonhosted.org/packages/81/39/4e763b150ff05412ab25d5eae91da7f0ade474b5d66509b39a67066d35ec/bpy-4.3.0-cp311-cp311-macosx_11_0_x86_64.whl
    - if: osx and arm64
      then: pip install --no-deps https://files.pythonhosted.org/packages/c1/fc/5902fa508a13f4f1669bc2e2cd8f37adf1caeeed0a344f627c0ffc3bdc40/bpy-4.3.0-cp311-cp311-macosx_11_0_arm64.whl

```

Avoiding the `sources` results in the same issue. The WHL is not imported into the build/test environment.

```
 │ │ bpy             ┆ 4.3.0     ┆ h60d57d3_0         ┆ .tmp1QNkte  ┆ 4.53 KiB   │
```

**Comment by wolfv** [comment]
Hey @zachcp I apologize for taking so long to get back to you. 

The `build` environment takes precedence over the `host` environment, but the Python files need to be installed into the `host` environment to end up in the package. 

For this reason, just remove everything you have under `requirements.build` and it should work.

```yaml
build:
  number: 0
  script: pip install --no-deps *.whl -v

requirements:
  host:
    - python =3.11
    - pip
    - wheel
  run:
    - python =3.11
```

If you want to cross-compile later (which I don't think you want), then you can use the more complicated `cross-python` toolchain from conda-forge. Or potentially, you could have a setup where you use `uv` in the build env and point it to your `Python` installation in your `host` env, e.g.


```
build:
  script: uv pip install --python ${{ PYTHON }} --no-deps -v

requirements:
  build:
     - uv
  host:
     - python =3.11
```
