### ISSUE TITLE
Add support for entry_points in Rattler build configuration

### ISSUE THREAD

**Issue by looooo** [prefix-dev/rattler-build#1430]
When attempting to define entry_points in a Rattler build configuration file (e.g., recipe.yaml), the build fails with the error:
```
× invalid field `entry_points`.  
  ╭─[20:3]  
19 │   script: ${{ PYTHON }} -m pip install ./tryton --no-deps -vv  
20 │   entry_points:  
   ·   ──────┬─────  
   ·         ╰── here  
21 │     - tryton = tryson.__main__:main  
```

## Problem:
The entry_points field is currently not recognized by Rattler, despite being a critical feature for Python packages to define console scripts and other entry points. This prevents proper installation of executables (e.g., tryton in this case) when building packages.

## Example Configuration Causing the Error:
```
build:  
  script:  
    script: ${{ PYTHON }} -m pip install ./tryton --no-deps -vv  
  entry_points:  # Rattler does not support this field  
    - tryton = tryton.__main__:main  
```
