### ISSUE TITLE
rattler-build does not copy directories unless the file path ends in /

### ISSUE THREAD

**Issue by AaronOpfer** [prefix-dev/rattler-build#1434]
Found this discrepency between how `rattler-build` and `conda build` handle file paths specified as test-time source dependencies.

recipe.yaml
```yaml
package:
  name: bug_reproduction
  version: 0

source:
  path: .

build:
  script:
    - echo hi

tests:
  - files:
      source:
        - subdirectory
    script:
      - test -f subdirectory/file
```
source tree
```
$ find -type f
./subdirectory/file
./recipe.yaml
```
`rattler-build build --recipe recipe.yaml --output-dir /some/other/place`
```
... snip ...
 │ Installing test environment
 │ ✔ Successfully updated the test environment
 │ Testing commands:
 │ + test -f subdirectory/file
 │ × error Script failed with status 1
 │ × error Work directory: '/tmp/.tmpPel2kW'
 │ × error To debug the build, run it manually in the work directory (execute the `./conda_build.sh` or `conda_build.bat` script)
 │
 ╰─────────────────── (took 1 second)
```

# Expected Result
`subdirectory`'s content to be copied into the test work directory and the build passes.

# Actual Result
Build fails.

Workaround is possible: append a `/` to the path in the `recipe.yaml` i.e
```yaml
tests:
  - files:
      source:
        - subdirectory/
```
tested on rattler-build 0.35.9
