### ISSUE TITLE
test environment not activated when running the `python` test type

### ISSUE THREAD

**Issue by beckermr** [prefix-dev/rattler-build#1437]
When running the python import tests, it appears rattler-build is not activating the test environment. This is causing tests to fail incorrectly for packages that need activation scripts to be run.

**Comment by wolfv** [comment]
Duplicate of #1440 

Also I extended the test script to this:

```yaml
package:
  name: actiscript
  version: 0.1.0

build:
  script:
    # Write an activation script to $PREFIX/etc/conda/activate.d/actiscript.sh that sets an env var
    - mkdir -p $PREFIX/etc/conda/activate.d
    - echo "export ACTI_ACTIVE=yeppa" > $PREFIX/etc/conda/activate.d/actiscript.sh
    # Create a Python module directory in $PREFIX/lib/python3.x/site-packages
    - mkdir -p $PREFIX/lib/python3.11/site-packages/actiscript
    # Write a simple Python module to $PREFIX/lib/python3.11/site-packages/actiscript/__init__.py
    - |
      cat <<EOF > $PREFIX/lib/python3.11/site-packages/actiscript/__init__.py
      def get_active_status():
          return "Activated successfully"
      EOF


requirements:
  run:
    - python 3.11.*

tests:
  - script:
      # Check that the env var is set
      - if [[ "$ACTI_ACTIVE" != "yeppa" ]]; then echo "ACTI_ACTIVE is not set correctly"; exit 1; fi
      - echo "ACTI_ACTIVE is set correctly"
      # Test importing and using the Python module
      - |
        python -c "from actiscript import get_active_status; print(get_active_status())" > output.txt
        if ! grep -q "Activated successfully" output.txt; then
          echo "Python module import or execution failed"
          exit 1
        fi
        echo "Python module imported and executed successfully"

  - python:
      imports:
        - actiscript
```

And everything seems to pass fine :)
