### ISSUE TITLE
test env not properly activated in another case

### ISSUE THREAD

**Issue by beckermr** [prefix-dev/rattler-build#1440]
I have a test section like this

```
    tests:
      - script:
        - python -c "import lsst"
        - python -c "import lsst.sconsUtils"
        - eups -h
        - eups list
        - if [[ ! ${STACKVANA_ACTIVATED} ]]; then exit 1; fi
```

and it appears in this case as well that the test environment is not properly activated.

cc @wolfv

**Comment by wolfv** [comment]
@beckermr I just tested this recipe:

```
package:
  name: actiscript
  version: 0.1.0

build:
  script:
    # write a activation script to $PREFIX/etc/conda/activate.d/actiscript.sh that sets an env var
    - mkdir -p $PREFIX/etc/conda/activate.d
    - echo "export ACTI_ACTIVE=yeppa" > $PREFIX/etc/conda/activate.d/actiscript.sh

tests:
  - script: 
      # check that the env var is set
      - if [[ "$ACTI_ACTIVE" != "yeppa" ]]; then echo "ACTI_ACTIVE is not set correctly"; exit 1; fi
      - echo "ACTI_ACTIVE is set correctly"
```

And it works as expected. Do you have a minimal reproducer?
