### ISSUE TITLE
Automatically add `.*` to requirements with `<pkg> <version>`

### ISSUE THREAD

**Issue by jakirkham** [prefix-dev/rattler-build#1444]
When adding a requirement of the form `<pkg> <version>`, `conda-build` would intuit this as `<pkg> <version>.*`. It looks like `rattler-build` does not do this and expects it to be specified.

For example with syntax like this...

```yaml
requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
```

...`rattler-build` produces the following error...

```
Error: 
  × an unspecified error occurred.
    ╭─[recipe/recipe.yaml:21:7]
 20 │   host:
 21 │     - python ${{ python_min }}
    ·       ────────────┬───────────
    ·                   ╰── This match spec is ambiguous. Do you mean `python ==3.9` or `python 3.9.*`?
 22 │     - pip
    ╰────
```
