### ISSUE TITLE
`ignore_run_exports` doesn't work with `${{ compiler('cxx') }}`

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#1445]
```yml
context:
  name: mypkglibtool
  version: '2.5.4'

package:
  name: mypkg
  version: '0.1.0'

build:
  number: 0

requirements:
  ignore_run_exports:
    from_package:
    - ${{ compiler('cxx') }}
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
```

```
c_compiler:
- clang
c_compiler_version:
- '16'
c_stdlib:
- macosx_deployment_target
c_stdlib_version:
- '11.0'
cxx_compiler:
- clangxx
cxx_compiler_version:
- '16'

```

```
❯ rattler-build build -r recipe/ -m recipe/variant.yml

 ╭─ Finding outputs from recipe
 │ Loading variant config file: "recipe/variant.yml"
 │
 ╰─────────────────── (took 0 seconds)
Error:   × Failed to parse recipe

Error:
  × failed to parse package name: 'clangxx_osx-arm64 =16' is not a valid package name. Package names can only contain 0-9, a-z, A-Z, -, _, or .
    ╭─[recipe/recipe.yaml:15:7]
 14 │     from_package:
 15 │     - ${{ compiler('cxx') }}
    ·       ───────────┬──────────
    ·                  ╰── here
 16 │   build:
    ╰────
```
