### ISSUE TITLE
Conditional evaluation changed unexpectedly since v0.36.0

### ISSUE THREAD

**Issue by maresb** [prefix-dev/rattler-build#1446]
I'm working on a [CUDA-enabled staged recipe](https://github.com/conda-forge/staged-recipes/pull/28931), using rattler-build v0.36.0. The following is a MWE of the strange behavior I'm experiencing:

```
context:
  use_cuda: ${{ "true" if cuda_compiler_version != "None" else "false" }}

package:
  name: vllm
  version: 0.7.2

requirements:
  host:
  - if: use_cuda == "true"
    then:
    - use_cuda_is_true
    else:
    - use_cuda_not_true ==${{ cuda_compiler_version }}-${{ use_cuda }}
  - if: use_cuda == "false"
    then:
    - use_cuda_is_false
    else:
    - use_cuda_not_false
```

When I run with the [staged-recipes cuda118 variant](https://github.com/conda-forge/staged-recipes/blob/main/.ci_support/linux64_cuda118.yaml), I expect `use_cuda == "true"` to evaluate to true, and `use_cuda == "false"` to evaluate to false. Instead, both evaluate to false, even though the variables are set to their expected values as evidenced by the version number I constructed:

```
$ rattler-build build -m ../../.ci_support/linux64_cuda118.yaml

╭─ Finding outputs from recipe
 │ Loading variant config file: "../../.ci_support/linux64_cuda118.yaml"
 │ Loading variant config file: "/home/gcpuser/staged-recipes/recipes/vllm/conda_build_config.yaml"
 │ Loading variant config file: "../../.ci_support/linux64_cuda118.yaml"
 │ Found 1 variants
 │ 
 │ Build variant: vllm-0.7.2-h00ab004_0
 │ 
 │ ╭───────────────────────┬────────────╮
 │ │ Variant               ┆ Version    │
 │ ╞═══════════════════════╪════════════╡
 │ │ cuda_compiler_version ┆ "11.8"     │
 │ │ target_platform       ┆ "linux-64" │
 │ ╰───────────────────────┴────────────╯
 │
 ╰─────────────────── (took 0 seconds)

 ╭─ Running build for recipe: vllm-0.7.2-h00ab004_0
 │
 │ ╭─ Fetching source code
 │ │ No sources to fetch
 │ │
 │ ╰─────────────────── (took 0 seconds)
 │
 │ ╭─ Resolving environments
 │ │ 
 │ │ Resolving host environment:
 │ │   Platform: linux-64 [__unix=0=0, __linux=6.8.0=0, __glibc=2.35=0, __cuda=12.2=0, __archspec=1=cascadelake]
 │ │   Channels: 
 │ │    - file:///home/gcpuser/staged-recipes/recipes/vllm/output/
 │ │    - conda-forge
 │ │   Specs:
 │ │    - use_cuda_not_true ==11.8-true
 │ │    - use_cuda_not_false
 │ │
 │ ╰─────────────────── (took 1 second)
 │
 ╰─────────────────── (took 1 second)
Error:   × Failed to resolve dependencies: Cannot solve the request because of: No candidates were found for use_cuda_not_true ==11.8-
  │ true.
  │ 
  ╰─▶ Cannot solve the request because of: No candidates were found for use_cuda_not_true ==11.8-true.
```

If I downgrade to v0.35.9, then I get the expected behavior:

```
 │ │   Specs:
 │ │    - use_cuda_is_true
 │ │    - use_cuda_not_false
```
