### ISSUE TITLE
rattler-build does not prevent using nonexistent context variables

### ISSUE THREAD

**Issue by vyasr** [prefix-dev/rattler-build#1449]
Consider this recipe:

```yaml
context:
  name: fizzbuzz
  version: 1.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: .

build:
  number: 0
  script:
    - echo "${{ mystring }}"
```

This builds successfully and shows
```
 │ ╭─ Running build script
 │ │ + echo ''
 │ │
 │ ╰─────────────────── (took 0 seconds)
```

Should using a nonexistent variable be considered an error?
