### ISSUE TITLE
Could not find a version that satisfies the requirement polars (from version: none)

### ISSUE THREAD

**Issue by svm-zhang** [prefix-dev/rattler-build#1459]
Hello,

I was trying to set up a recipe to build my package using rattler-build. 

### Setup

Below is a snippet of the `recipe.yml` I was using:

```
context:
  version: "0.1.1"
  name: myapp

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - path: ./scripts

build:
  string: "stable"
  skip:
    - win

requirements:
  host:
    - python >=3.10
  run:
     ...

```

And this is a snippet of my `build.sh`:

```
#!/bin/bash

set -e

mkdir -p "$PREFIX/bin"
mkdir -p "$PREFIX/lib"

pip install polars
```

### Error

when I ran `rattler-build build -r recipe.yaml`, I got the error:

```
 │ ╭─ Running build script
 │ │ + set -e
 │ │ + mkdir -p $PREFIX/bin
 │ │ + mkdir -p $PREFIX/lib
 │ │ + pip3 install polars
 │ │ ERROR: Could not find a version that satisfies the requirement polars (from versions: none)
 │ │ ERROR: No matching distribution found for polars
```

It is strange that

- `pip install polars` worked just fine if I ran it manually from the command line.
- `$PREFIX/bin/pip install polars` worked also just fine. `$PREFIX` is the path to the build environment (located under `conda-bld/bld` within my local miniforge3).

And this is not only for the `polars` package. I was trying to install for instance, `pysam`, and I got the same problem. I believe both packages are compatible with `python >= 3.10`.

I was using rattler-build v0.37.0, and the target platform is `osx-arm64`. I think I missed something somewhere and was not able to find similar issues with rattler-build (I could be wrong). Could you please provide some insights on why this is the case and how should I fix it? Appreciate any help. Thanks.

Simo
