### ISSUE TITLE
Add the ability for requirements for python packages

### ISSUE THREAD

**Issue by hmaarrfk** [prefix-dev/rattler-build#1460]
On certain recipes, it may be useful to have different variants that are built against a common shared library.

For example, I use this for the av feedstock

https://github.com/conda-forge/av-feedstock/blob/main/recipe/meta.yaml#L54

to ensure that when built against `lgpl` it works for the `gpl` and `lgpl` variant of ffmpeg.

Is there a way to do this with rattle-build recipe syntax?

Thanks for your help!

**Comment by wolfv** [comment]
Sorry for the late reply.

You can have multiple, entirely independent tests with `rattler-build`:

```yaml
tests:
  - script:
      - bla bla
    requirements:
      run:
        - foo =1234 *gpl
  - script:
      - bla bla
    requirements:
      run:
        - foo =1234 *nogpl
```

You can also include / exclude entire tests based on the variant:

```yaml
tests:
  - if: match(python, "3.12.*")
    then:
      script:
        - bla bla
      requirements:
        run:
          - foo =1234 *gpl
```

Lastly, this should also work:

```yaml
  - script:
      - bla bla
    requirements:
      run:
        - ${{ "foo =1234 *nogpl" if match(python, "3.12.*") else "foo =1234 *gpl" }}
  ```
