### ISSUE TITLE
BUG: run_exports only includes last item when it is a list

### ISSUE THREAD

**Issue by minrk** [prefix-dev/rattler-build#1468]
When `run_exports` is a list, it only results in a package with a single `run_exports` item, the last item in the list.

When `run_exports` specifies `weak`, the list works correctly.

Sample recipe:

```yaml
schema_version: 1

package:
  name: test
  version: 1.0.0

source:
  url: https://example.org
  sha256: 88c0d465a3bd688cb17ebf06a17c06d6e9cc457fa6b9643d217389424e6bd795

build:
  number: 1

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - libblas
  run:
    - python
  run_exports:
    - export1
    - export2

about:
  summary: test recipe
```

which produces:

```yaml
run_exports:
  weak:
    - export2
```

entirely missing the run_export on `export1`.

If `run_exports`  are specified explicitly under `weak`, it appears to be correct.
