### ISSUE TITLE
question: can I use a list defined in `context` to define shared requirements?

### ISSUE THREAD

**Issue by theavey** [prefix-dev/rattler-build#1472]
I have a `recipe.yaml` that defines a bunch of outputs. They all have the same host requirements, but I think currently I have to define them separately for each subpackage output. This is particularly annoying when I want to change them because I have to change it for each.

With the new (experimental) feature of lists defined in `context`, can I define a list of host requirements there and then use the list for each of the outputs? Alternatively, can I define a "global" set of host requirements that get inherited by each output (95% sure not currently supported, but I kinda like the idea)

<details>
<summary>current simplified recipe</summary>

```yaml
context:
  version: ${{ env.get("VERSION") }}
  build_num: ${{ env.get("BUILD_NUM") }}

source:
  path: ../
  use_gitignore: true

build:
  number: ${{ build_num }}
  noarch: python

outputs:
  - package:
      name: thing_a
      version: ${{ version }}
    requirements:
      host:
        - pip
        - poetry-core >=2.0.0
        - tomlkit
        - python
        - python-build
        - ruamel.yaml
      run:
        - python>=3.9
        - requests

  - package:
      name: thing_b
      version: ${{ version }}
    requirements:
      host:
        - pip
        - poetry-core >=2.0.0
        - tomlkit
        - python
        - python-build
        - ruamel.yaml
      run:
        - python>=3.9
        - pandas
```
</details>

<details>
<summary>simplified recipe using list in context</summary>

```yaml
context:
  version: ${{ env.get("VERSION") }}
  build_num: ${{ env.get("BUILD_NUM") }}
  host_requirements:
    - pip
    - poetry-core >=2.0.0
    - tomlkit
    - python
    - python-build
    - ruamel.yaml

source:
  path: ../
  use_gitignore: true

build:
  number: ${{ build_num }}
  noarch: python

outputs:
  - package:
      name: thing_a
      version: ${{ version }}
    requirements:
      host: ${{ host_requirements }}
      run:
        - python>=3.9
        - requests

  - package:
      name: thing_b
      version: ${{ version }}
    requirements:
      host: ${{ host_requirements }}
      run:
        - python>=3.9
        - pandas
```
</details>

<details>
<summary>simplified recipe using inherited requirements</summary>

```yaml
context:
  version: ${{ env.get("VERSION") }}
  build_num: ${{ env.get("BUILD_NUM") }}

source:
  path: ../
  use_gitignore: true

build:
  number: ${{ build_num }}
  noarch: python

requirements:
  host:
    - pip
    - poetry-core >=2.0.0
    - tomlkit
    - python
    - python-build
    - ruamel.yaml
  run:
    - python>=3.9

outputs:
  - package:
      name: thing_a
      version: ${{ version }}
    requirements:
      # host:  # purely inherited here
      run:
        # maybe inherited as a union, or if overriding at all, need to also specifiy the things listed in the "base"
        # - python>=3.9
        - requests

  - package:
      name: thing_b
      version: ${{ version }}
    requirements:
      # host:  # purely inherited here
      run:
        # maybe inherited as a union, or if overriding at all, need to also specifiy the things listed in the "base"
        # - python>=3.9
        - pandas
```
</details>

**Comment by mgorny** [comment]
> With the new (experimental) feature of lists defined in `context`, can I define a list of host requirements there and then use the list for each of the outputs?

I'm afraid that's not possible, and I can't think of a way of making it possible, short of changing how Jinja is used. However, that is likely to break some tooling.

**Comment by theavey** [comment]
> I'm afraid that's not possible, and I can't think of a way of making it possible, short of changing how Jinja is used. However, that is likely to break some tooling.

Yeah, kinda expected so, but was hopeful :) Thank you for the quick reply, and from the implementer of the feature!

**Comment by wolfv** [comment]
We actually do flatten lists in requirements to make things like `if/else` work. 

So I think if you format the Jinja correctly, it might work.

E.g. this should work I believe:

```yaml
requirements:
  build:
    - [bla, bli, blub]
```

You just need to get your Jinja formatted in that way.
