### ISSUE TITLE
[bug] rpath subdirectories on linux

### ISSUE THREAD

**Issue by christianbator** [prefix-dev/rattler-build#1498]
### Description
I'm having an issue with the rpath relocation on linux:

I have a dynamic library at this location: `$PREFIX/lib/mosaic/libcodec.so`, and I've specified:

```
rpaths:
  - lib/mosaic/
```

However, I get this output for new relative paths:
<img width="723" alt="Image" src="https://github.com/user-attachments/assets/666fdbf6-2688-4d1d-9962-4bce7c7dab57" />

Then the test files can't `dlopen()` the dynamic library.

On macOS with `@loader_path` it all works fine. It also works on linux if I remove the subdirectory `mosaic/` and put `libcodec.so` directly into `$PREFIX/lib/` without specifying `rpaths`.

### Source
My guess is there's something here in `src/linux/link.rs` (https://github.com/prefix-dev/rattler-build/blob/a45ea2665b666cbc2d63f8dff5f8c133ce60704b/src/linux/link.rs#L185C56-L185C70) that needs an update.

**Comment by wolfv** [comment]
Hi @Christian Bator I am trying to take a look at this issue. Do you have the recipe somewhere?

And / or can you tell me more about the layout of shared libraries?

Does your binary link only against libraries in lib/mosaic/*.so?

A reproducer would be super helpful.

**Comment by christianbator** [comment]
#### Background
Yeah this is from my project here: https://github.com/christianbator/mosaic, but I've made changes since that issue, so the pasted recipe from a previous commit should reproduce it with the usage command below.

If you look at the project at this commit: https://github.com/christianbator/mosaic/tree/ca9c685b34fab20b7b2f22ada8a0563af363bcd5, there are two top-level directories that get built into shared libs to be used by the mojo package via `dlopen()`:
```
libcodec/
libvisualizer/ (mac only)
```
and they get placed in the pixi env's `lib/mosaic/` directory.

If you run the recipe below, you should see the tests all pass on macOS, but then see them fail on linux with a `dlopen() can't find the libcodec.so file`.

Hope that helps.

#### Usage
``` bash
rattler-build build --recipe recipe.yaml -c https://conda.modular.com/max-nightly -c https://conda.modular.com/max -c conda-forge
```

#### Recipe
```yaml
context:
  version: "0.0.1"

package:
  name: mosaic
  version: ${{ version }}

source:
  - git: https://github.com/christianbator/mosaic
    rev: ca9c685b34fab20b7b2f22ada8a0563af363bcd5

build:
  number: 0
  script: build/build.sh
  dynamic_linking:
    rpaths:
    - lib/mosaic/
    missing_dso_allowlist:
      - if: osx
        then:
          - /usr/lib/swift/libswift*.dylib

requirements:
  build:
    - clang
  host:
    - max ~=25.1
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script: mojo test
    files:
      source:
        - test/*.mojo
        - data/

about:
  homepage: https://mosaiclib.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Open source computer vision library in Mojo
  repository: https://github.com/christianbator/mosaic
  documentation: https://mosaiclib.org/docs

extra:
  project_name: Mosaic
  maintainers:
    - christianbator
```
