### ISSUE TITLE
Set modified SP_DIR during package_contents tests?

### ISSUE THREAD

**Issue by h-vetinari** [prefix-dev/rattler-build#1509]
I maintain a couple of recipes that ensure that the version as recognized by pip does not contain spurious suffixes. The best way to test this that I've discovered so far is:
```yaml
  commands:
    # ensure that the package metadata did not mangle in the git hash
    - test -f $SP_DIR/torchdata-{{ version }}.dist-info/METADATA                # [unix]
    - if not exist %SP_DIR%\torchdata-{{ version }}.dist-info\METADATA exit 1   # [win]
```

Some other places use `pip list | grep <package> | grep {{ version }}`, but that doesn't work if the version (say 2.5.1) is a subset of the spurious version, e.g.
```
lib/python3.9/site-packages/torchaudio-2.5.1a0+d6d4767.dist-info/METADATA
```

If I translate those to `package_contents` tests in rattler, I need to formulate those paths relative to `$PREFIX`, but I don't want to have to recompute `lib/python3.9/site-packages` for each python version -- SP_DIR is a nice convenience there. Of course, I could just pack this under `script:` tests (with a unix/windows distinction), but nicer would be something like

```yaml
  - package_contents:
      files:
        - <SP_DIR_magic>/torchdata-${{ version }}.dist-info/METADATA
```

**Comment by h-vetinari** [comment]
Argh, this exists already, I just didn't see it under the [testing](https://rattler.build/dev/testing/) docs... It's only in the recipe [spec](https://rattler.build/dev/reference/recipe_file/#check-for-package-contents)

**Comment by h-vetinari** [comment]
Short follow-up: The docs don't really tell the full story about what `site_packages:` does or can do. It only shows a case that does a path transformation (why? shouldn't that be covered by the import tests?)
```yaml
      # checks for the existence of `mamba/api/__init__.py` inside of the
      # Python site-packages directory (note: also see Python import checks)
      site_packages:
        - mamba.api
```

However, I've tried it with
```yaml
  - package_contents:
      site_packages:
        # ensure that the package metadata did not mangle in the git hash
        - torchaudio-${{ version }}.dist-info/METADATA
```
in https://github.com/conda-forge/torchaudio-feedstock/pull/15, and it works 🥳
