### ISSUE TITLE
Add `tests` `python` example with `python_version`

### ISSUE THREAD

**Issue by jakirkham** [prefix-dev/rattler-build#1534]
Currently `tests`' `python`'s `python_version` value is not documented in [the test page]( http://rattler.build/latest/testing/#testing-packages ) or elsewhere. It would be helpful to have this documented and in an example for reference and learning

Something like this could be helpful

```yaml
tests:
  - python:
      imports:
        - <...>
      pip_check: true
      python_version: ${{ python_min }}.*
```
