### ISSUE TITLE
generate-recipe produces bad pypi imports

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#1544]
```
❯ rattler-build generate-recipe pypi pydiverse-common
Generating recipe for pydiverse-common
context:
  version: 0.1.0

package:
  name: pydiverse-common
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/p/pydiverse-common/pydiverse_common-${{ version }}.tar.gz
  sha256: 19208ce0d7646c2acf6db6c17e4947e61f4da306e928c3ddee3bbc9c2e2b4d19

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
  - python >=3.9
  - hatchling
  - pip
  run:
  - python >=3.9

tests:
- python:
    imports:
    - pydiverse-common <---- this should be pydiverse.common
    pip_check: true

about:
  summary: Common functionality shared between pydiverse libraries
...
```
