### ISSUE TITLE
Conda selectors failure

### ISSUE THREAD

**Issue by amgcc** [prefix-dev/rattler-build#1568]
I'm trying to include a package with selector for `mkl` but it fails with error:

```
failed to parse match spec: the build string '=*mkl' is not valid, it can only contain alphanumeric characters and underscores
```

```
requirements:
  host: [python=3.11, pip, setuptools]
  run:
    - libblas=*=*mkl
```

Is this a limitation of rattler, rattler-build, or am I doing something wrong?
