### ISSUE TITLE
Repackaging `.exe` file harder than it should be

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#1576]
There seems to be a little bug when using a `.exe` file as the source for a package.

I have tried the following recipe to repackage a simple `.exe` file as a Conda package but it fails to find the file in the work-dir.

The same recipe used to work with `conda-build`.

```yaml
context:
  version: "3.1.7"

package:
  name: vswhere
  version: ${{ version }}

source:
  url: https://github.com/microsoft/vswhere/releases/download/${{ version }}/vswhere.exe
  sha256: c54f3b7c9164ea9a0db8641e81ecdda80c2664ef5a47c4191406f848cc07c662
  file_name: vswhere.exe  # this didn't change anything

build:
  number: 0
  script: MOVE vswhere.exe %LIBRARY_BIN%\vswhere.exe  # here it fails to find `vswhere.exe`
  skip: not win

tests:
  - script:
      - vswhere

about:
  homepage: https://github.com/microsoft/vswhere
  license: MIT
  license_file: LICENSE.txt
  summary: CLI tool to locate Visual Studio 2017 and newer installations
  description: |
    vswhere is designed to be a redistributable, single-file executable that
    can be used in build or deployment scripts to find where Visual Studio
    - or other products in the Visual Studio family - is located.

extra:
  recipe-maintainers:
    - wolfv
```
