### ISSUE TITLE
Inconsistency with the treatment of leading zeroes in version number

### ISSUE THREAD

**Issue by dillon-cullinan** [prefix-dev/rattler-build#1580]
Recipe contents don't matter really, it looks like `rattler-build` is removing leading zeroes from version numbers. In the below example, I set `version` to `1.01.01`. When the recipe is built, the supposed output says `1.01.01`, but then it says running build for `1.1.1`. The resulting package information is using `1.1.1` for all metadata as well.

I would expect an error or warning and for the output to also be labeled as `1.1.1`.

```yaml
package:
  name: test-meta-env
  version: 1.01.01

source:
  git: https://github.com/python/cpython
  branch: main

build:
  number: 0
  string: abcdef54321
  dynamic_linking:
    overdepending_behavior: ignore

requirements:
  run:
    - python 3.10.*

tests:
  - script:
      - echo "Hello World"

about:
  homepage: https://github.com/python
```

```
$ rattler-build build --recipe recipe.yaml --channel conda-forge

 ╭─ Finding outputs from recipe
 │ Found 1 variants
 │ 
 │ Build variant: test-meta-env-1.01.01-abcdef54321
 │ 
 │ ╭─────────────────┬────────────╮
 │ │ Variant         ┆ Version    │
 │ ╞═════════════════╪════════════╡
 │ │ target_platform ┆ "linux-64" │
 │ ╰─────────────────┴────────────╯
 │
 ╰─────────────────── (took 0 seconds)

 ╭─ Running build for recipe: test-meta-env-1.1.1-abcdef54321
```
