### ISSUE TITLE
How to set python version in the test environment

### ISSUE THREAD

**Issue by amgcc** [prefix-dev/rattler-build#1600]
When building my package, the test environment resolves python 3.12 though I want to constrain this to python 3.11 only.  At first I tried applying version constraints in the `host`/`run` sections but this didn't help during testing.  Next, I tried using a variant file but this too seemed to have no effect.  Is this possible?

## recipe.yaml
```
schema_version: 1
context:
  name: mypkg
package:
  name: ${{ name|lower }}
  version: 0.1
source:
  - path: ../../setup.py
  - path: ../../lib
    target_directory: ./lib
build:
  string: 0
  noarch: python
  script:
    - $PYTHON -m pip install . --no-deps --ignore-installed -vv
requirements:
  host: [python, pip, setuptools]
  run:
    - click
    - python
tests:
  - python:
      imports:
        - mypkg.util.cli
```

## variants
```
python:
  - "3.11"
```

## output
```
 │ ╭─ Resolving environments
 │ │ 
 │ │ Resolving host environment:
 │ │   Platform: linux-64 [__unix=0=0, __linux=5.14.0=0, __glibc=2.34=0, __archspec=1=cascadelake]
 │ │   Channels: 
 │ │    - file:///home/.../mypkg/
 │ │    - conda-forge
 │ │   Specs:
 │ │    - python
 │ │    - pip
 │ │    - setuptools
 │ │ 
 │ │ ╭──────────────────┬───────────┬────────────────────┬─────────────┬────────────╮
 │ │ │ Package          ┆ Version   ┆ Build              ┆ Channel     ┆       Size │
 │ │ ╞══════════════════╪═══════════╪════════════════════╪═════════════╪════════════╡
 │ │ │ _libgcc_mutex    ┆ 0.1       ┆ conda_forge        ┆ conda-forge ┆   2.50 KiB │
 │ │ │ _openmp_mutex    ┆ 4.5       ┆ 2_gnu              ┆ conda-forge ┆  23.07 KiB │
 │ │ │ bzip2            ┆ 1.0.8     ┆ h4bc722e_7         ┆ conda-forge ┆ 246.86 KiB │
 │ │ │ ca-certificates  ┆ 2025.4.26 ┆ hbd8a1cb_0         ┆ conda-forge ┆ 148.71 KiB │
 │ │ │ ld_impl_linux-64 ┆ 2.43      ┆ h712a8e2_4         ┆ conda-forge ┆ 655.51 KiB │
 │ │ │ libexpat         ┆ 2.7.0     ┆ h5888daf_0         ┆ conda-forge ┆  72.68 KiB │
 │ │ │ libffi           ┆ 3.4.6     ┆ h2dba641_1         ┆ conda-forge ┆  56.09 KiB │
 │ │ │ libgcc           ┆ 14.2.0    ┆ h767d61c_2         ┆ conda-forge ┆ 828.01 KiB │
 │ │ │ libgcc-ng        ┆ 14.2.0    ┆ h69a702a_2         ┆ conda-forge ┆  52.50 KiB │
 │ │ │ libgomp          ┆ 14.2.0    ┆ h767d61c_2         ┆ conda-forge ┆ 449.08 KiB │
 │ │ │ liblzma          ┆ 5.8.1     ┆ hb9d3cd8_0         ┆ conda-forge ┆ 110.07 KiB │
 │ │ │ libmpdec         ┆ 4.0.0     ┆ h4bc722e_0         ┆ conda-forge ┆  87.88 KiB │
 │ │ │ libsqlite        ┆ 3.49.1    ┆ hee588c1_2         ┆ conda-forge ┆ 897.13 KiB │
 │ │ │ libuuid          ┆ 2.38.1    ┆ h0b41bf4_0         ┆ conda-forge ┆  32.81 KiB │
 │ │ │ libzlib          ┆ 1.3.1     ┆ hb9d3cd8_2         ┆ conda-forge ┆  59.53 KiB │
 │ │ │ ncurses          ┆ 6.5       ┆ h2d0b736_3         ┆ conda-forge ┆ 870.74 KiB │
 │ │ │ openssl          ┆ 3.5.0     ┆ h7b32b05_0         ┆ conda-forge ┆   2.98 MiB │
 │ │ │ pip              ┆ 25.1      ┆ pyh145f28c_0       ┆ conda-forge ┆   1.19 MiB │
 │ │ │ python           ┆ 3.13.3    ┆ hf636f53_101_cp313 ┆ conda-forge ┆  31.73 MiB │
 │ │ │ python_abi       ┆ 3.13      ┆ 7_cp313            ┆ conda-forge ┆   6.82 KiB │
 │ │ │ readline         ┆ 8.2       ┆ h8c095d6_2         ┆ conda-forge ┆ 275.86 KiB │
 │ │ │ setuptools       ┆ 79.0.1    ┆ pyhff2d567_0       ┆ conda-forge ┆ 769.08 KiB │
 │ │ │ tk               ┆ 8.6.13    ┆ noxft_h4845f30_101 ┆ conda-forge ┆   3.17 MiB │
 │ │ │ tzdata           ┆ 2025b     ┆ h78e105d_0         ┆ conda-forge ┆ 120.09 KiB │
 │ │ ╰──────────────────┴───────────┴────────────────────┴─────────────┴────────────╯
 │ │ 
 │ │ Finalized run dependencies:
 │ │ ╭──────────────────┬────────────────────────╮
 │ │ │ Name             ┆ Spec                   │
 │ │ ╞══════════════════╪════════════════════════╡
 │ │ │ Run dependencies ┆                        │
 │ │ │ click            ┆                        │
 │ │ │ python           ┆                        │
 │ │ │ python           ┆ (RE of [host: python]) │
 │ │ ╰──────────────────┴────────────────────────╯
 │ │
 │ ╰─────────────────── (took 8 seconds)
```

**Comment by wolfv** [comment]
You are building a `noarch` package and need to set the constraints yourself (they are not propagated from the Python variant).

You can either set the run dependency properly, e.g.

```
requirements:
  host: [python, pip, setuptools]
  run:
    - click
    - python 3.11.*
```

Or you can add an additional requirement at test time using:

```
tests:
  - python:
      imports: ...
      python_version: 3.11.*
```
