### ISSUE TITLE
proposal: use matrix style variants config to avoid using `zip_keys`?

### ISSUE THREAD

**Issue by trim21** [prefix-dev/rattler-build#1604]
like github actions, would is better to use variants config like this to replace `zip_keys`?

```yaml
pairs:
  - { python: '3.8', numpy: '1.12' }
  - { python: '3.9', numpy: '1.14' }
```

```yaml
zip_keys: ["python", "numpy"]
python: ["3.8", "3.9"]
numpy: ["1.12", "1.14"]
```
