### ISSUE TITLE
SHA256 not matching for rich example

### ISSUE THREAD

**Issue by raybellwaves** [prefix-dev/rattler-build#161]
Steps to reproduce:

```
git clone https://github.com/prefix-dev/rattler-build.git
cd rattler-build/examples/rich
rattler-build build --recipe recipe.yaml
```

I can't work out why running the rich example (https://github.com/prefix-dev/rattler-build/blob/main/examples/rich/recipe.yaml) I get

```
ERROR rattler_build::source: SHA256 values of downloaded file not matching!
Downloaded = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, should be d653d6bccede5844304c605d5aac802c7cf9621efd700b46c7ec2b51ea914898
ERROR rattler_build::source: Checksum validation failed!
ERROR rattler_build: Error: Download could not be validated with checksum!
```

The sha should match (https://pypi.org/project/rich/#copy-hash-modal-2010ddfe-5e36-4f05-9a00-6ce880fc7e80) e.g. d65... Not sure where e3b... is coming from.

I made a slight modification to the file to match the latest feedstock (https://github.com/conda-forge/rich-feedstock/blob/main/recipe/meta.yaml)

```
context:
  name: "rich"
  min_python: ">=3.7.0"
  version: "13.4.2"

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d653d6bccede5844304c605d5aac802c7cf9621efd700b46c7ec2b51ea914898

build:
  # Thanks to `noarch: python` this package works on all platforms
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ min_python }}
  run:
    # sync with normalized deps from poetry-generated setup.py
    - markdown-it-py >=2.2.0
    - pygments >=2.13.0,<3.0.0
    - python {{ min_python }}
    - typing_extensions >=4.0.0,<5.0.0

test:
  imports:
    - rich
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Textualize/rich
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Render rich text, tables, progress bars, syntax highlighting, markdown and more to the terminal
  description: |
    Rich is a Python library for rich text and beautiful formatting in the terminal.

    The Rich API makes it easy to add color and style to terminal output. Rich
    can also render pretty tables, progress bars, markdown, syntax highlighted
    source code, tracebacks, and more — out of the box.
  doc_url: https://rich.readthedocs.io
  dev_url: https://github.com/Textualize/rich
```

and I run the command `rattler-build build --recipe recipe.yaml`. The full output is

❯ rattler-build build --recipe recipe.yaml
 INFO rattler_build: Starting the build process
Found variants:
╭─────────────────┬─────────╮
│ Variant         ┆ Version │
╞═════════════════╪═════════╡
│ target_platform ┆ noarch  │
╰─────────────────┴─────────╯

 INFO rattler_build::source: Fetching source from URL: https://pypi.io/packages/source//rich/rich-13.4.2.tar.gz
ERROR rattler_build::source: SHA256 values of downloaded file not matching!
Downloaded = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, should be d653d6bccede5844304c605d5aac802c7cf9621efd700b46c7ec2b51ea914898
ERROR rattler_build::source: Checksum validation failed!
ERROR rattler_build: Error: Download could not be validated with checksum!
