### ISSUE TITLE
Package `build/string` ignored `PKG_` variables

### ISSUE THREAD

**Issue by jakirkham** [prefix-dev/rattler-build#1622]
When writing `build/string`, it is quite common to use `PKG_` variables to define the string (for example [conda-forge's `python` recipe]( https://github.com/conda-forge/python-feedstock/blob/a9c2dde0e7719d4517d198fe8f8420933a51c5c7/recipe/meta.yaml#L121 ))

However it looks like the `build/string` is not getting filled out in cases like these. Have included a simple example below demonstrating this issue

```yaml
schema_version: 1

context:
  version: ${{ "0.1.0" }}
  number: ${{ 0 }}
  py_version: ${{ "3.12" }}
  py_buildstring: ${{ py_version | version_to_buildstring }}

package:
  name: mypkg
  version: ${{ version }}

build:
  number: ${{ number }}
  string: py${{ py_buildstring }}_${{ PKG_BUILDNUM }}_h${{ PKG_HASH }}

requirements:
  host:
    - python =${{ py_version }}
  run:
    - python
```

The resulting package is named: `mypkg-0.1.0-py312__h.conda`
