### ISSUE TITLE
Version number dependent on platform

### ISSUE THREAD

**Issue by matthewfeickert** [prefix-dev/rattler-build#1685]
In https://github.com/conda-forge/mpfun90-feedstock/pull/3 I updated to the v1 recipe format, which uses `rattler-build`. The package version is [set as](https://github.com/conda-forge/mpfun90-feedstock/blob/caee5f59e8e8c446260ae43eecc86b0a555cded4/recipe/recipe.yaml#L7)

```yaml
context:
  name: "mpfun90"
  version: "2024-12-06"

package:
  name: ${{ name }}
  version: ${{ version | replace('-', '.') }}
```

Following this, the `linux` builds correctly have versions of `2024.12.06` (https://anaconda.org/conda-forge/mpfun90/files?version=2024.12.06) but the `osx` builds have all dropped the `0` in `06` and are now `2024.12.6` (https://anaconda.org/conda-forge/mpfun90/files?version=2024.12.6).

This is not the intended effect, and I want `2024.12.06` for all package versions.

Why is `version` being handled differently across operating systems? Did I miss something that is causing a bug in the PR I made?
