### ISSUE TITLE
nodejs -- issues with testing

### ISSUE THREAD

**Issue by vigneshmanick** [prefix-dev/rattler-build#1694]
Hello devs, 

I am facing the following issues when building+testing nodejs packages, please let me know if i am doing something wrong.

- the tests are not being copied from the `source` section 
- only the first command in the tests is being run

### To reproduce

1. Create recipe at `conda.recipe/recipe.yaml`

`recipe.yaml`

```yaml
context:
  version: "1.14.0"

package:
  name: bibtex-tidy
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/bibtex-tidy/-/bibtex-tidy-${{ version }}.tgz
  sha256: 0a2c1bb73911a7cee36a30ce1fc86feffe39b2d39acd4c94d02aac6f84a00285
  # we do not extract the source code and install the tarball directly as that works better
  file_name: bibtex-tidy-${{ version }}.tgz

build:
  number: 0
  script:
    # we use NPM to globally install the bibtex-tidy package
    - npm install -g bibtex-tidy-${{ version }}.tgz --prefix ${{ PREFIX }}

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
    - bibtex-tidy --version
    - bibtex-tidy tests/references.bib
    files:
      recipe:
          - tests/
  - script:
    - bibtex-tidy src_tests/references.bib
    files:
      source:
        - src_tests/
```

2. Copy the following file to 

`src_tests/references.bib` and  `conda.recipe/tests/references.bib`

```
@ARTICLE {feinberg1983technique,
  title={A technique for radiolabeling DNA restriction endonuclease fragments to high specific activity},
author={Feinberg, Andrew P. and Vogelstein, Bert},
  journal    = {Analytical biochemistry},
  volume = 132,
  number=1,
  pages={6--13},
  year=1983,
  publisher={Elsevier},}
@article{miles1984qualitative,
    title={Qualitative data analysis: A sourcebook},
    author={Miles, Matthew B. and Huberman, A. Michael and Saldana, J.},
    journal={Beverly Hills},
    year=1984
}
```

3. Run build `rattler-build build --recipe conda.recipe`
4. The recipe tests only runs the first test (printing out the version)
5. the src_tests errors out since the files are not found

**Comment by wolfv** [comment]
Hey @vigneshmanick are the `src_tests` part of the tarball that you download or are they generated / created during recipe execution time?

**Comment by wolfv** [comment]
I just tested this and it doesn't error when nothing is selected (which is not great). Could it be that there is a typo where you are creating the tests?<br><br>But this worked:

```
context:
  version: 1.14.0

package:
  name: bibtex-tidy
  version: ${{ version }}

build:
  number: 0
  script:
    - mkdir -p $SRC_DIR/tests
    - echo "foobar" > $SRC_DIR/tests/references.bib

tests:
  - script:
     - ls tests/
    # - bibtex-tidy --version
    # - bibtex-tidy tests/references.bib
    files:
      recipe:
          - tests/
  - script:
    - ls tests
    files:
      source:
        - tests/
```

**Comment by wolfv** [comment]
The output in the terminal should show you copied test files, e.g.:

```
 │ │ 
 │ │ Files in package:
 │ │   - etc/conda/test-files/bibtex-tidy/0/tests/bla.txt
 │ │   - etc/conda/test-files/bibtex-tidy/1/tests/references.bib
 │ │   - info/about.json
 │ │   - info/hash_input.json
...
```

**Comment by wolfv** [comment]
The test files for the 2nd test should go under `/etc/tests/1/…`

**Comment by vigneshmanick** [comment]
ok, i have combined both the systems to be able to use URL and tests

with the following folder structure

```
.
├── conda.recipe
│   ├── recipe.yaml
│   └── tests
│       └── references.bib
└── src
    └── src_tests
        └── references.bib
```

and the following configuration,
```
source:
  - url: https://registry.npmjs.org/bibtex-tidy/-/bibtex-tidy-${{ version }}.tgz
    sha256: 0a2c1bb73911a7cee36a30ce1fc86feffe39b2d39acd4c94d02aac6f84a00285
    file_name: bibtex-tidy-${{ version }}.tgz

  - path: ../src/
```

i am able to both use the source from an URL and also add extra test data to the build.
