### ISSUE TITLE
aarch64 and arm64 selectors behave differently

### ISSUE THREAD

**Issue by janjagusch** [prefix-dev/rattler-build#1702]
According to the [documentation](https://rattler.build/latest/selectors/#available-variables) they should behave identically:

> aarch64, arm64	64-bit Arm (these are the same but are both supported for legacy)

But they don't.

With the `aarch64` selector the source is found.

```
  - if: linux and aarch64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-linux-arm64.tar.gz
      sha256: 13eb5e281c93080a5a0cbb807892e675d98e9ccd5144a9d4dd39533977b94a32
      target_directory: code-server
```

```
╭─ Fetching source code
 │ │ Fetching source from url: https://github.com/coder/code-server/releases/download/v4.100.2/code-server-4.100.2-linux-arm64.tar.gz
...
```

[link](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1258870&view=logs&j=60238c3a-ba84-5ca5-39dc-717fbb421dbc&t=9cf66154-4ecc-5714-a3ee-b77d4233a250)

Wit the `arm64` selector the source is not found.

```
  - if: linux and arm64
    then:
      url: https://github.com/coder/code-server/releases/download/v${{ version }}/code-server-${{ version }}-linux-arm64.tar.gz
      sha256: 13eb5e281c93080a5a0cbb807892e675d98e9ccd5144a9d4dd39533977b94a32
      target_directory: code-server
```

```
│ ╭─ Fetching source code
 │ │ No sources to fetch
```

[link](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1258867&view=logs&jobId=60238c3a-ba84-5ca5-39dc-717fbb421dbc&j=60238c3a-ba84-5ca5-39dc-717fbb421dbc&t=9cf66154-4ecc-5714-a3ee-b77d4233a250)

Ref.: https://github.com/conda-forge/code-server-feedstock/pull/116
