### ISSUE TITLE
`license_url` doesn't do anything

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#1730]
```
context:
  name: yap
  version: 1.0.2
package:
  name: ${{ name }}
  version: ${{ version }}
about:
  license_url: https://raw.githubusercontent.com/finnvoor/${{ name }}/refs/tags/${{ version }}/LICENSE
```

build logs:

```
...
 │ │ Files in package:
 │ │   - info/about.json
 │ │   - info/hash_input.json
 │ │   - info/index.json
 │ │   - info/paths.json
 │ │   - info/recipe/recipe.yaml
 │ │   - info/recipe/rendered_recipe.yaml
 │ │   - info/recipe/variant_config.yaml
 │ │   - info/tests/tests.yaml
```

No license to be found here. We should still include the license.

(this field is in the schema)
