### ISSUE TITLE
`SP_DIR` not set during build and test time

### ISSUE THREAD

**Issue by hadim** [prefix-dev/rattler-build#1733]
See the below recipe:

```yaml
package:
  name: test-sp-dir
  version: 0.0.1

build:
  number: 0
  noarch: python
  script:
    - echo "hello world"
    - echo "SP_DIR 1 = $SP_DIR"
    - echo "SP_DIR 2 = ${{ SP_DIR }}"
    - export SP_DIR=$(python -c "import site; print(site.getsitepackages()[0])")
    - echo "SP_DIR 3 = $SP_DIR"
requirements:
  build:
    - python
  run:
    - python

tests:
  - script:
      - echo "hello world"
      - echo "SP_DIR 1 = $SP_DIR"
      - echo "SP_DIR 2 = ${{ SP_DIR }}"
      - export SP_DIR=$(python -c "import site; print(site.getsitepackages()[0])")
      - echo "SP_DIR 3 = $SP_DIR"
```

and the relevant logs

```bash
 │ Installing build environment
 │ ✔ Successfully updated the build environment
 │ 
 │ Installing host environment
 │ ✔ Successfully updated the host environment
 │
 │ ╭─ Running build script
 │ │ hello world
 │ │ SP_DIR 1 = 
 │ │ SP_DIR 2 = 
 │ │ SP_DIR 3 = $BUILD_PREFIX/lib/python3.13/site-packages
 │ │
 │ ╰─────────────────── (took 0 seconds)

#####

 │ Installing test environment
 │ ✔ Successfully updated the test environment
 │ Testing commands:
 │ hello world
 │ SP_DIR 1 = 
 │ SP_DIR 2 = 
 │ SP_DIR 3 = $SRC_DIR_run_env/lib/python3.13/site-packages
```
