### ISSUE TITLE
Python 3.14 example fails to link despite -headerpad_max_install_names

### ISSUE THREAD

**Issue by rationalis** [prefix-dev/rattler-build#1758]
When building the example `recipe.yaml` for Python 3.14 from https://prefix.dev/:

```
package:
  name: python
  version: 3.14.0a7

source:
  - url: https://github.com/python/cpython/archive/refs/tags/v3.14.0a7.tar.gz
    sha256: ad83cda00a8a30adbad263d8e25455397be0641ded65d731b78ec178ed74570c

build:
  script:
    - export LDFLAGS="-headerpad_max_install_names $LDFLAGS"
    - ./configure --enable-shared --prefix $PREFIX
    - make -j${CPU_COUNT}
    - make install

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - make
    - libtool
    - pkg-config
    - llvm-tools
    - python 3.13.*
```

I get the following error:

```
 │ │ ⚠ warning Builtin relink failed BuiltinRelinkFailed, trying install_name_tool
 │ │ install_name_tool for "/var/folders/m6/tjblvt614pg32dmxjsw7_lkc0000gn/T/pythonRu3jVS/lib/python3.14/config-3.14-darwin/python.o":
 │ │  - add rpath "@loader_path/../.."
 │ │ × error install_name_tool failed: error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /var/folders/m6/tjb
 │ │ × error lvt614pg32dmxjsw7_lkc0000gn/T/pythonRu3jVS/lib/python3.14/config-3.14-darwin/python.o (for architecture arm64) because larger updated load commands do not fit (the progr
 │ │ × error am must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
```

I'm not sure what's going wrong; the error message suggests using `-headerpad_max_install_names` but the build already includes this in the `LDFLAGS`.

(I also get the same error when using 3.14.0b3 instead of 3.14.0a7)
