### ISSUE TITLE
Support local archive as source

### ISSUE THREAD

**Issue by beenje** [prefix-dev/rattler-build#176]
It would be nice to support local sdist as source.

Using:

```yaml
source:
  - url: file:///build/rich/rich-{{ version }}.tar.gz
    sha256: fb9d6c0a0f643c99eed3875b5377a184132ba9be4d61516a55273d3554d75a39
```

raises:

```
INFO rattler_build::source: Fetching source from URL: file:///build/rich/rich-13.5.2.tar.gz
ERROR rattler_build: Error: Failed to download source from url: builder error for url (file:///build/rich/rich-13.5.2.tar.gz): URL scheme is not allowed
```
