### ISSUE TITLE
Add `package.name` and `package.version` implicitly to `context`

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#208]
When `name` and `version` are not given in the context, I think it could be good to append them to the `context` from the package dictionary.

I often see code like:

```yaml
context:
   name: "bla"
   version: "1.2.3"

package:
   name: ${{ bla }}
   version: ${{ version }}
```

which seems a bit double
