### ISSUE TITLE
Guard against unknown keys 

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#214]
In the following sections unknown keys lead to a panic:

```yaml
build:
  asldd: asdad
```

```yaml
requirements:
  asldjaskjda:
    - adszd
```

And toplevel keys such as:

```yaml
extras:
  asdadd:
    - asdd
```
