### ISSUE TITLE
Adapt variant config loading to new if / then / else syntax

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#222]
We are currently still using the `sel( ... )` syntax in the variant config parsing. We should also adopt the new syntax for these files. 

Example config:

```yaml
test:
  - if: 
    then: test
  - if: win
    then: other

second:
  - if: unix
    then: test
  - if: win
    then: other

third:
  - - if: unix
      then: test
    - if: win
      then: other

fourth:
  - if: unix
    then:
      - test
      - anothertest
```

### Desired result for "unix":

```yaml
test:
  - test

second:
  - test

third:
  - - test

fourth:
  - test
  - anothertest

```
