### ISSUE TITLE
Documentation is for the main branch, not the main release

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [prefix-dev/rattler-build#231]
Hello, it looks like the documentation is currently pointing at the tip of main. It's a little bit confusing for new users to look at the docs, particularly today since the new docs use `${{ }}` while 0.4.0 doesn't support that syntax yet.

**Comment by wolfv** [comment]
Yeah, I agree that is not great. I hope we'll have a release out by next week though :)

**Comment by wolfv** [comment]
The release is out! We still need to figure out how to publish two books or so to decouple main from release docs.

**Comment by swarnimarun** [comment]
This is fairly easy to fix with the current deployment we just need to use destination-dir for main branch.


```yaml
      - name: Deploy stable
        uses: peaceiris/actions-gh-pages@v3
        if: startswith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: startswith(github.ref, 'refs/heads/main')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: "main"
```

Docs for subdir deployment https://github.com/peaceiris/actions-gh-pages/issues/324
