### ISSUE TITLE
Random test failures due to invalid prefix replacement

### ISSUE THREAD

**Issue by beenje** [prefix-dev/rattler-build#264]
We are testing replacing `conda mambabuild` with `rattler-build` in our internal gitlab ci pipelines.

We are testing for simple noarch python packages. The recipe is generated with grayskull and converted with boa and looks like:

```
context:
  name: sardana-restarter
  version: 2.4.1.dev1+g38ea727
package:
  name: '{{ name|lower }}'
  version: '{{ version }}'
source:
  url: file:///builds/kits-maxiv/app-maxiv-sardanarestarter/dist/sardana-restarter-2.4.1.dev1+g38ea727.tar.gz
  sha256: 679533ee101897c05bd5d1d7345afab3d25280badf4373eef8b19107ca1a8bd6
build:
  entry_points:
    - sardana-restart = sardanarestarter.sardanarestarter:main
  noarch: python
  script: 'python -m pip install . -vv'
  number: 0
requirements:
  host:
    - python
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python
    - pytango
    - pyqt
test:
  imports:
    - sardanarestarter
  commands:
    - pip check
    - sardana-restart --help
  requires:
    - pip
about:
  home: https://gitlab.maxiv.lu.se/kits-maxiv/app-maxiv-sardanarestarter
  summary: Sardana restarter to restart Pool and MacroServer or any device server using tango
  license: LGPL-3.0
  license_file: LICENSE
```

We had already 2 or 3 occurrences where the test phase failed. For example:

```
✔ Successfully updated the environment
Collecting tests from "/var/lib/containers/.cache/rattler/cache/pkgs/sardana-restarter-2.4.1.dev1+g38ea727-pyh4616a5c_0"
Testing commands:
+ pip check
No broken requirements found.
+ sardana-restart --help
/var/lib/containers/.cache/rattler/cache/pkgs/sardana-restarter-2.4.1.dev1+g38ea727-pyh4616a5c_0/info/test/run_test.sh: /tmp/rattler-build_sardana-restarter_1699362325375/work/test/bin/sardana-restart: /tmp/rattler-buil/tmp/rattler-build_sardana-restarter_1699362325375/work/test/: bad interpreter: No such file or directory
2023-11-07T13:05:54.635951Z ERROR rattler_build: Error: failed to run test
```

If we run the pipeline again, it passes:

```
✔ Successfully updated the environment
Collecting tests from "/var/lib/containers/.cache/rattler/cache/pkgs/sardana-restarter-2.4.1.dev1+g38ea727-pyh4616a5c_0"
Testing commands:
+ pip check
No broken requirements found.
+ sardana-restart --help
usage: sardana-restart [-h] [--all] [--pool] [--macroserver] [--widget]
                       [--device-server DEVICESERVER]
Sardana restarter to restart Pool and MacroServer or any device server using
tango
options:
  -h, --help            show this help message and exit
...
Testing Python imports:
import sardanarestarter
✔ all tests passed!
```

The path `/tmp/rattler-buil/tmp/rattler-build_sardana-restarter_1699362325375/work/test/` looks suspicious.
Any idea where this could come from?

We are using version 0.4.0.
