### ISSUE TITLE
Package is accepted in top-level in multi-output recipe

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#283]
We should throw an error when encountering something like this:

```yaml
package:
  name: test
  version: 1.0.0

recipe:
  name: test
  version: 1.0.0

outputs:
  - package:
      name: hello
  - package:
      name: world
```
