### ISSUE TITLE
Make `lfs` requirement specific?

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#285]
Github Actions (checkout action) has a extra config field to ask for lfs or not.

E.g. 

```yaml
source:
   git_url: https://blalba
   lfs: true  # (defaults to false)
```
