### ISSUE TITLE
`build.number` not correctly merged into outputs?

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#288]
I tried the following `zlib` example and had to replicate the `build.number` value manually into each output:

```yaml
# yaml-language-server: $schema=../../schema.json

context:
  version: 1.2.13
  build_number: 5

recipe:
  name: zlib-split
  version: ${{version}}

source:
  url: http://zlib.net/zlib-${{ version }}.tar.gz
  sha256: d5a89e26beae0bc03ad18a0b0d1d3d75f87c32047879d25da11970cb5c4662a3

build:
  number: ${{ build_number }}

outputs:
  - package:
      name: libzlib
    build:
      run_exports:
        - ${{ pin_subpackage('libzlib', max_pin='x.x') }}
      script:
        - echo "build libzlib"
      number: ${{ build_number }}
    requirements:
      build:
        - ${{ compiler('c') }}
      host:
        - openssl
      run:
      run_constrained:
        - zlib ${{ version }} *_${{ build_number }}

    test:
      commands:
      - if: unix
        then:
          - test ! -f ${PREFIX}/lib/libz.a            
          - test ! -f ${PREFIX}/lib/libz${SHLIB_EXT}  
          - test ! -f ${PREFIX}/include/zlib.h        
      - if: win
        then:
          - if not exist %LIBRARY_BIN%\zlib.dll exit 1 
          - if not exist %PREFIX%\zlib.dll exit 1 

  - package:
      name: libzlib-wapi
    build:
      skip: 
        - not win
      run_exports:
        - ${{ pin_subpackage('libzlib-wapi', max_pin='x.x') }}
      number: ${{ build_number }}

    requirements:
      build:
        - ${{ compiler('c') }}
      host:
      run:
      run_constrained:
        - zlib ${{ version }} *_${{ build_number }}
        - zlib-wapi ${{ version }} *_${{ build_number }}
    # files:
    #   - Library/bin/zlibwapi.dll   # [win]
    test:
      commands:
        - if not exist "%LIBRARY_BIN%\zlibwapi.dll" exit 1

  - package:
      name: zlib
    build:
      run_exports:
        - ${{ pin_subpackage('libzlib', max_pin='x.x') }}
      script:
        - echo "build zlib"
      number: ${{ build_number }}

    requirements:
      build:
        - ${{ compiler('c') }}
      host:
        - ${{ pin_subpackage('libzlib', exact=True) }}
      run:
        - ${{ pin_subpackage('libzlib', exact=True) }}

    test:
      commands:
        - test -f ${PREFIX}/lib/libz.a

about:
  homepage: http://zlib.net/
  # http://zlib.net/zlib_license.html
  license: Zlib
  summary: Massively spiffy yet delicately unobtrusive compression library
  license_file: license.txt
  description: |
    zlib is designed to be a free, general-purpose, lossless data-compression
    library for use on virtually any computer hardware and operating system.
  repository: https://github.com/madler/zlib
```
