### ISSUE TITLE
Give nice error messages if `if-condition` Jinja doesn't parse properly

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#309]
```yaml
requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - if: unix =123=32 213=123
      then: make
```

We try to extract "used variables" from the if condition and Jinja parsing into an AST fails. 
Our error message is not great like the others, though.
