### ISSUE TITLE
rattler-build login

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#334]
There is currently no way of logging into private channels using rattler-build without using `pixi auth login`. Would be nice to have a standalone way of doing this.

**Comment by pavelzw** [comment]
This actually got more important for us now.
The workaround with using `pixi auth login` only works when there is no keychain.
In CI on `macos-latest`, I have the following situation:

```yml
    runs-on: macos-latest
    timeout-minutes: 5
...
      - name: Install rattler-build
        uses: mamba-org/setup-micromamba@54d4d5980e1a4aa7cdc8b050cf2d19b7e262ce18
        with:
          environment-name: build
          create-args: >-
            rattler-build=0.6.0
          cache-environment: true
      - uses: prefix-dev/setup-pixi@ccc5c07ed948b849df4b3578d785f3afd7465c67
        with:
          run-install: false
          auth-host: https://my-quetz-instance.com
          auth-conda-token: ${{ secrets.QUETZ_API_KEY }}
      - name: Build conda package
        run: >-
          rattler-build build
          --recipe conda.recipe/recipe.yaml
          -c conda-forge
          -c https://my-quetz-instance.com/get/private-channel
```

Looking at the logs of this workflow, I can see the following:

```
Copied ...

Resolving for environment specs:
 - clang_osx-64 15.*


Error: The operation was canceled.
```

What's happening is that `pixi` writes the secret to the keychain and `rattler-build` tries to read the secret from the keychain. This triggers an interactive auth prompt and the workflow gets canceled after `timeout-minutes`.
