### ISSUE TITLE
Indescriptive error message when `sha256` is not set

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#345]
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  name: polarify
  version: 0.1.3

source:
  url: https://github.com/quantco/polarify/archive/refs/tags/v${{ version }}.tar.gz
  # sha256: 93441164c23b764d72c8a66d14b11d5bbd353ed6112ccf3b35efda2a98f9df02

outputs:
  - package:
      name: ${{ name }}
      version: ${{ version }}
    build:
      noarch: python
      script:
        - python -m pip install . --no-deps --ignore-installed -vv --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - python >=3.9
        - pip
        - hatchling
      run:
        - python >=3.9
        - polars >=0.14.24,<0.20
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - polarify

about:
  homepage: https://github.com/quantco/polarify
  license: BSD-3-Clause
```

```
❯ rattler-build build -r conda.recipe/recipe.yaml -c conda-forge
No target platform specified, using current platform
Found variants:

polarify-v0.1.3-pyh60d57d3
╭─────────────────┬───────────╮
│ Variant         ┆ Version   │
╞═════════════════╪═══════════╡
│ target_platform ┆ osx-arm64 │
╰─────────────────┴───────────╯

Fetching source from URL: https://github.com/quantco/polarify/archive/refs/tags/v0.1.3.tar.gz
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /private/tmp/rattler-build-20231117-58371-xlqe8m/src/source/mod.rs:87:82
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
