### ISSUE TITLE
Indescriptive error message when `pin_subpackage` is not correctly specified

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#346]
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  name: polarify
  version: 0.1.3

source:
  url: https://github.com/quantco/polarify/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 93441164c23b764d72c8a66d14b11d5bbd353ed6112ccf3b35efda2a98f9df02

outputs:
  - package:
      name: ${{ name }}
      version: ${{ version }}
    build:
      noarch: python
      script:
        - python -m pip install . --no-deps --ignore-installed -vv --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - python >=3.9
        - pip
        - hatchling
      run:
        - python >=3.9
        - polars >=0.14.24,<0.20
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - polarify
  
  - package:
      name: ${{ name }}-2
      version: ${{ version }}
    requirements:
      run:
        - ${{ pin_subpackage('this-does-not-exist', exact=True) }}
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - polarify

about:
  homepage: https://github.com/quantco/polarify
  license: BSD-3-Clause
```

```
❯ rattler-build build -r conda.recipe/recipe.yaml -c conda-forge
No target platform specified, using current platform
thread 'main' panicked at 'no entry found for key', src/variant_config.rs:504:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
