### ISSUE TITLE
`PathSource` file doesn't work

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#374]
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  name: polarify
  version: 0.1.3

source:
  - url: https://github.com/quantco/polarify/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 93441164c23b764d72c8a66d14b11d5bbd353ed6112ccf3b35efda2a98f9df02
  - path: abc.sh

outputs:
  - package:
      name: ${{ name }}
      version: ${{ version }}
    build:
      noarch: python
      script:
        - ls -lah
        - cd test && python -m pip install . --no-deps --ignore-installed -vv --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - python >=3.9
        - pip
        - hatchling
      run:
        - python >=3.9
        - polars >=0.14.24,<0.20
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - polarify

about:
  homepage: https://github.com/quantco/polarify
  license: BSD-3-Clause
```

```bash
$ echo 'echo hi' >> conda.recipe/abc.sh
$ rattler-build build --recipe conda.recipe/recipe.yaml

No target platform specified, using current platform
Found variants:

polarify-0.1.3-pyh4616a5c_0
╭─────────────────┬─────────╮
│ Variant         ┆ Version │
╞═════════════════╪═════════╡
│ target_platform ┆ noarch  │
╰─────────────────┴─────────╯

Fetching source from URL: https://github.com/quantco/polarify/archive/refs/tags/v0.1.3.tar.gz
Validated SHA256 values of the downloaded file!
Found valid source cache file.
Extracted to "/Users/pavel/test/output/bld/rattler-build_polarify_1701258218/work"
Copying source from path: "/Users/pavel/test/conda.recipe/abc.sh"
Error:   × FileSystem error: 'Path "/Users/pavel/test/output/bld/rattler-build_polarify_1701258218/work/" exists'
```
