### ISSUE TITLE
Source `folder` doesn't work

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#375]
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  name: polarify
  version: 0.1.3

source:
  url: https://github.com/quantco/polarify/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 93441164c23b764d72c8a66d14b11d5bbd353ed6112ccf3b35efda2a98f9df02
  folder: test

outputs:
  - package:
      name: ${{ name }}
      version: ${{ version }}
    build:
      noarch: python
      script:
        - ls -lah
        - cd test && python -m pip install . --no-deps --ignore-installed -vv --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - python >=3.9
        - pip
        - hatchling
      run:
        - python >=3.9
        - polars >=0.14.24,<0.20
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - polarify

about:
  homepage: https://github.com/quantco/polarify
  license: BSD-3-Clause
```

```
✔ Successfully updated the environment
Work dir: "/Users/pavel/test/output/bld/rattler-build_polarify_1701257743/work"
Build script: "/Users/pavel/test/output/bld/rattler-build_polarify_1701257743/work/conda_build.sh"
total 24
drwxr-xr-x  4 pavel  staff   128B Nov 29 12:35 .
drwxr-xr-x  5 pavel  staff   160B Nov 29 12:35 ..
-rw-r--r--  1 pavel  staff   6.7K Nov 29 12:35 build_env.sh
-rw-r--r--  1 pavel  staff   259B Nov 29 12:35 conda_build.sh
```
