### ISSUE TITLE
Make almost all keys "optional"?

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#379]
When evaluating Jinja we can arrive at the empty value. However, the parser complains when trying to convert a `Null` value to e.g. a number or a string:

```yaml
package:
  name: blib
  version: 0.1.0

build:
  number: ${{ 5 if false }}
```

Should we instead just fallback to the default / ignore the `Null` value here?
The other workaround is for the user to add the `else`: `${{ 5 if false else 0 }}`.

For many options I don't expect this to make "sense" but there might be some options that should only be conditionally activated e.g. on Windows.
