### ISSUE TITLE
`.zip` file in sources is not extracted

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#403]
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
package:
  name: test-package
  version: 0.1.0
source:
  - url: https://cache-redirector.jetbrains.com/download.jetbrains.com/idea/jdbc-drivers/web/snowflake-3.13.27.zip
    sha256: 6a15e95ee7e6c55b862dab9758ea803350aa2e3560d6183027b0c29919fcab18

build:
  script:
    - ls -lah
    - ls -lah | grep snowflake-jdbc-3.13.27.jar
  number: 0
```

```bash
$ rattler-build build --recipe conda-recipe/recipe.yaml
+ ls -lah
total 24
drwxr-xr-x  4 pavel  staff   128B Dec  6 13:37 .
drwxr-xr-x  5 pavel  staff   160B Dec  6 13:37 ..
-rw-r--r--  1 pavel  staff   6.9K Dec  6 13:37 build_env.sh
-rw-r--r--  1 pavel  staff   300B Dec  6 13:37 conda_build.sh
+ ls -lah
+ grep snowflake-jdbc-3.13.27.jar
Error:   × Build failed
```
