### ISSUE TITLE
Version can't be determined from a tag? 

### ISSUE THREAD

**Issue by mariusvniekerk** [prefix-dev/rattler-build#404]
Given this minimal recipe

```yaml
# ./recipe/foo/recipe.yaml
context:
  version: ${{ env['GIT_DESCRIBE_TAG'] | replace('v', '') }}${{ 'dev' if env['GIT_DESCRIBE_NUMBER'] == 0 }}

package:
  version: "${{ version }}"
  name: foo
  
source:
  git: "../../"
```

rattler-build will fail with

```
o target platform specified, using current platform
Error:   × Parsing: missing field `version`
   ╭─[4:1]
 4 │     package:
 5 │ ╭─▶   version: "${{ version }}"
 6 │ │     name: foo
 7 │ │     
 8 │ ├─▶ source:
   · ╰──── here
 9 │       git: "../../"
   ╰────
  help: the field `version` is required for `package`
```

conda-build works for this (boa also fails)
