### ISSUE TITLE
rattler-build `tar` error in `windows-latest` CI

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#409]
```yml
name: CI

on:
  push

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test
          create-args: rattler-build=0.6.0
          init-shell: powershell
      - run: rattler-build build -r conda.recipe/recipe.yaml 
        shell: powershell
```

with `conda.recipe/recipe.yaml`:
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  name: polarify
  version: 0.1.3

source:
  - url: https://github.com/quantco/polarify/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 93441164c23b764d72c8a66d14b11d5bbd353ed6112ccf3b35efda2a98f9df02

outputs:
  - package:
      name: ${{ name }}
      version: ${{ version }}
    build:
      noarch: python
      script:
        - python -m pip install . --no-deps --ignore-installed -vv --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - python >=3.9
        - pip
        - hatchling
      run:
        - python >=3.9
        - polars >=0.14.24,<0.20
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - polarify

about:
  homepage: https://github.com/quantco/polarify
  license: BSD-3-Clause
```

Has the CI error:

```
No target platform specified, using current platform
Found variants:

polarify-0.1.3-pyh4616a5c_0
╭─────────────────┬─────────╮
│ Variant         ┆ Version │
╞═════════════════╪═════════╡
│ target_platform ┆ noarch  │
╰─────────────────┴─────────╯

Fetching source from URL: https://github.com/quantco/polarify/archive/refs/tags/v0.1.3.tar.gz
Validated SHA256 values of the downloaded file!
Error:   × Failed to extract archive: Failed to extract archive: D:\a\ci-test\ci-
  │ test\output\src_cache\v0.1.3_93441164.tar.gz.
  │ Stdout:
  │ Stderr: /usr/bin/tar: Cannot connect to D: resolve failed
  │ 

Error: Process completed with exit code 1.
```

See also https://github.com/pavelzw/ci-test/actions/runs/7151774641/job/19476405561
