### ISSUE TITLE
zip files are sort of still broken

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#427]
I tried out #425 in CI and stumbled into the following issues:

```yml
name: CI

on:
  push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test
          create-args: rattler-build=0.6.2rc1 -c conda-forge/label/rattler-build_rc -c conda-forge
      - run: rattler-build build -r conda.recipe/recipe.yaml
        shell: bash -el {0}
```

(`rattler-build=0.6.2rc1` is a build based on https://github.com/prefix-dev/rattler-build/commit/fa672b934b4c6519f774d721dd4e8bf3746ebd29)

```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
package:
  name: test-package
  version: 0.1.0
source:
  - url: https://cache-redirector.jetbrains.com/download.jetbrains.com/idea/jdbc-drivers/web/snowflake-3.13.27.zip
    sha256: 6a15e95ee7e6c55b862dab9758ea803350aa2e3560d6183027b0c29919fcab18

build:
  script:
    - ls -lah
    - ls -lah | grep snowflake-jdbc-3.13.27.jar
  number: 0
```

Ubuntu:
```
rattler-build build -r conda.recipe/recipe.yaml
  shell: /usr/bin/bash -el {0}
  env:
    MAMBA_ROOT_PREFIX: /home/runner/micromamba
    MAMBA_EXE: /home/runner/micromamba-bin/micromamba
    CONDARC: /home/runner/micromamba-bin/.condarc
No target platform specified, using current platform
Found variants:

test-package-0.1.0-hb0f4dca_0
╭─────────────────┬──────────╮
│ Variant         ┆ Version  │
╞═════════════════╪══════════╡
│ target_platform ┆ linux-64 │
╰─────────────────┴──────────╯

Fetching source from URL: https://cache-redirector.jetbrains.com/download.jetbrains.com/idea/jdbc-drivers/web/snowflake-[3](https://github.com/pavelzw/ci-test/actions/runs/7249269606/job/19746910697#step:4:3).13.27.zip
Validated SHA2[5](https://github.com/pavelzw/ci-test/actions/runs/7249269606/job/19746910697#step:4:5)[6](https://github.com/pavelzw/ci-test/actions/runs/7249269606/job/19746910697#step:4:6) values of the downloaded file!
Error:   × Failed to extract archive: Failed to extract archive with "/usr/bin/
  │ tar": /home/runner/work/ci-test/ci-test/output/src_cache/snowflake-
  │ 3.13.2[7](https://github.com/pavelzw/ci-test/actions/runs/7249269606/job/19746910697#step:4:7)_6a15e[9](https://github.com/pavelzw/ci-test/actions/runs/7249269606/job/19746910697#step:4:10)5e.zip.
  │ Stdout:
  │ Stderr: /usr/bin/tar: This does not look like a tar archive
  │ /usr/bin/tar: Skipping to next header
  │ /usr/bin/tar: Exiting with failure status due to previous errors
  │ 

Error: Process completed with exit code 1.
```

Windows
```
rattler-build build -r conda.recipe/recipe.yaml
  shell: C:\Program Files\Git\usr\bin\bash.EXE -el {0}
  env:
    MAMBA_ROOT_PREFIX: C:\Users\runneradmin\micromamba
    MAMBA_EXE: C:\Users\runneradmin\micromamba-bin\micromamba.exe
    CONDARC: C:\Users\runneradmin\micromamba-bin\.condarc
No target platform specified, using current platform
Found variants:

test-package-0.1.0-h9490d1a_0
╭─────────────────┬─────────╮
│ Variant         ┆ Version │
╞═════════════════╪═════════╡
│ target_platform ┆ win-64  │
╰─────────────────┴─────────╯

Fetching source from URL: https://cache-redirector.jetbrains.com/download.jetbrains.com/idea/jdbc-drivers/web/snowflake-[3](https://github.com/pavelzw/ci-test/actions/runs/7249269606/job/19746911389#step:4:3).13.27.zip
Validated SHA2[5](https://github.com/pavelzw/ci-test/actions/runs/7249269606/job/19746911389#step:4:5)[6](https://github.com/pavelzw/ci-test/actions/runs/7249269606/job/19746911389#step:4:6) values of the downloaded file!
Error:   × Failed to extract archive: Failed to extract archive with "C:
  │ \\Program Files\\Git\\usr\\bin\\tar.exe": D:\a\ci-test\ci-
  │ test\output\src_cache\snowflake-3.13.2[7](https://github.com/pavelzw/ci-test/actions/runs/7249269606/job/19746911389#step:4:7)_6a15e[9](https://github.com/pavelzw/ci-test/actions/runs/7249269606/job/19746911389#step:4:10)5e.zip.
  │ Stdout:
  │ Stderr: /usr/bin/tar: Cannot connect to D: resolve failed
  │ 

Error: Process completed with exit code 1.
```

On `macos-latest` and `macos-latest-xlarge` (the M1 paid github runners), it actually worked.

See also [this run](https://github.com/pavelzw/ci-test/actions/runs/7249269606)
