### ISSUE TITLE
Add `binary_relocation: false`

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#428]
Would be nice to be able to disable binary relocation.

**Comment by brad-jones** [comment]
So I started playing around with pixi that other day, attempting to put together a dev env for my team.
One of the packages we use lefthook didn't seem to to be published on conda-forge so I figured I'd have a go at building a conda package with rattler myself.

This is my recipe.

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "1.5.4"

package:
  name: lefthook
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://github.com/evilmartians/lefthook/releases/download/v${{ version }}/lefthook_${{ version }}_Linux_x86_64
      sha256: 1a359b807fe6dec3f796a62c436348749697571a992cd24c3f646529e20bce71
  - if: osx and x86_64
    then:
      url: https://github.com/evilmartians/lefthook/releases/download/v${{ version }}/lefthook_${{ version }}_MacOS_x86_64
      sha256: c26d50de48d3c4e70fb5ba629f0906b5a3effbb73f7daef2688ff4f4625cc8d2
  - if: osx and arm64
    then:
      url: https://github.com/evilmartians/lefthook/releases/download/v${{ version }}/lefthook_${{ version }}_MacOS_arm64
      sha256: 358be965ed88a52c53e7cdc8d8d4f5e95d592f07d9ab1015483ac2c9520d2490
  - if: win and x86_64
    then:
      url: https://github.com/evilmartians/lefthook/releases/download/v${{ version }}/lefthook_${{ version }}_Windows_x86_64.exe
      sha256: 5e27ecf5a78b13f8b3b23faf938da2f28a7310a98475a60bfc782fe1becb5132

build:
  script:
    - mkdir -p $PREFIX/bin
    - mv ./lefthook* $PREFIX/bin/lefthook
    - chmod +x $PREFIX/bin/lefthook

test:
  commands:
    - test "$(lefthook version)" = "1.5.4"
```

But I get this error from patchelf: `2023-12-23T10:36:08.599972Z ERROR rattler_build::linux::link: patchelf failed: patchelf: cannot find section '.dynamic'. The input file is most likely statically linked`

Now perhaps the manner in which I have written my recipe is not the typical workflow. ie: I'm not building anything just downloading an already built binary. But I guess the outcome would be the same if I had done the go build myself & set `CGO_ENABLED=0` right?

So yeah the ability to disable this binary relocation step seems sensible. That is whats causing my problem right?
