### ISSUE TITLE
OSX arch identifer. Which is it arm64 or aarch64?

### ISSUE THREAD

**Issue by brad-jones** [prefix-dev/rattler-build#444]
Your docs have this example.
![image](https://github.com/prefix-dev/rattler-build/assets/2754772/ef86fa9f-9089-4690-90c9-d65b314b22f7)

Yet with this recipe file.

```yaml
context:
  version: "1.5.4"

package:
  name: lefthook
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      url: https://github.com/evilmartians/lefthook/releases/download/v${{ version }}/lefthook_${{ version }}_Linux_x86_64
      sha256: 1a359b807fe6dec3f796a62c436348749697571a992cd24c3f646529e20bce71
  - if: osx and x86_64
    then:
      url: https://github.com/evilmartians/lefthook/releases/download/v${{ version }}/lefthook_${{ version }}_MacOS_x86_64
      sha256: c26d50de48d3c4e70fb5ba629f0906b5a3effbb73f7daef2688ff4f4625cc8d2
  - if: osx and arm64
    then:
      url: https://github.com/evilmartians/lefthook/releases/download/v${{ version }}/lefthook_${{ version }}_MacOS_arm64
      sha256: 358be965ed88a52c53e7cdc8d8d4f5e95d592f07d9ab1015483ac2c9520d2490
  - if: win and x86_64
    then:
      url: https://github.com/evilmartians/lefthook/releases/download/v${{ version }}/lefthook_${{ version }}_Windows_x86_64.exe
      sha256: 5e27ecf5a78b13f8b3b23faf938da2f28a7310a98475a60bfc782fe1becb5132

build:
  script:
    - mkdir -p $PREFIX/bin
    - if: unix
      then: mv ./lefthook* $PREFIX/bin/lefthook
      else: mv ./lefthook* $PREFIX/bin/lefthook.exe
    - if: unix
      then: chmod +x $PREFIX/bin/lefthook
```

And this command: `rattler-build build -r ./src/recipe.yaml --target-platform osx-arm64` ran on a Linux host. I get the following.

```
Found variants:

lefthook-1.5.4-hcf6ef32_0
╭─────────────────┬───────────╮
│ Variant         ┆ Version   │
╞═════════════════╪═══════════╡
│ build_platform  ┆ linux-64  │
│ target_platform ┆ osx-arm64 │
╰─────────────────┴───────────╯

Work dir: "/home/brad.jones/Projects/Personal/pixi-play/output/bld/rattler-build_lefthook_1703378139/work"
Build script: "/home/brad.jones/Projects/Personal/pixi-play/output/bld/rattler-build_lefthook_1703378139/work/conda_build.sh"
+ mkdir -p /home/brad.jones/Projects/Personal/pixi-play/output/bld/rattler-build_lefthook_1703378139/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin
+ mv './lefthook*' /home/brad.jones/Projects/Personal/pixi-play/output/bld/rattler-build_lefthook_1703378139/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/lefthook
mv: cannot stat './lefthook*': No such file or directory
Error:   × Build failed
```

ie: The source file was not downloaded.

Yet if I change `if: osx and arm64` to `if: osx and aarch64` and re-run the same command I get a good conda package.

I feel like there is some work to be done to standardize these identifiers. As `x86_64 != 64`. ie: My first instinct when I attempted to supply a value to `--target-platform` was to combine `linux and x86_64` into `linux-x86_64`. But that fails & you are given this list of valid platforms: `Valid platforms are 'noarch', 'unknown', 'linux-32', 'linux-64', 'linux-aarch64', 'linux-armv6l', 'linux-armv7l', 'linux-ppc64le', 'linux-ppc64', 'linux-s390x', 'linux-riscv32', 'linux-riscv64', 'osx-64', 'osx-arm64', 'win-32', 'win-64', 'win-arm64', 'emscripten-wasm32', 'wasi-wasm32'`

It just feels like there is a bit of a disconnect between this list & what you actually have to use in the recipe file.
