### ISSUE TITLE
Cross-testing fails with rattler-build 0.7.0

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#487]
This is working with rattler-build `0.6.*` with `--target-platform=linux-64` (when on `osx-arm64`)

```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: '0.0.1'

package:
  name: test-package
  version: ${{ version }}

build:
  number: 0
  script:
    - echo "Hello world!"

test:
  commands:
    - echo "Hello testing world!"
```

This is failing with rattler-build `0.7.0` with `--target-platform=linux-64` (when on `osx-arm64`)

```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: '0.0.1'

package:
  name: test-package
  version: ${{ version }}

build:
  number: 0
  script:
    - echo "Hello world!"

tests:
  - script:
    - echo "Hello testing world!"
```

```
Resolving environment for:

  Platform: linux-64
  Channels: 
   - /home/runner/work/test-project/test-project/output
   - conda-forge
  Specs:
   - test-package ==0.0.1 he8cfe8b_0


2024-01-12T15:02:47.157476Z ERROR rattler_repodata_gateway::fetch: error=repodata not found
Error:   × Failed to setup test environment: Cannot solve the request because of: No
  │ candidates were found for test-package ==0.0.1 he8cfe8b_0.
  │ 
  ╰─▶ Cannot solve the request because of: No candidates were found for test-
      package ==0.0.1 he8cfe8b_0.
```

We should add unit tests to make sure this doesn't break again.
