### ISSUE TITLE
Conditional list in script doesn't evaluate to "file" 

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#516]
We had a list like:

```
- if: unix
  then:
    - cmd.sh
- if: win
  then:
	- cmd.bat
```

This was evaluated to a "script" and not a "file". Workaround is:

```
- ${{ "cmd.sh" if unix else "cmd.bat" }}
```
