### ISSUE TITLE
Implement `variant` section

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#521]
The `variant` section contains two entries: `use_keys` and `ignore_keys`.

Was: `force_ignore_keys` and `force_use_keys`.

These are used to forcibly add new variants (`use_keys`) or ignore a key from the hash computation. We would need to look up the exact semantics used in `conda-build` (does this _only_ affect the hash computation?).

```yaml
build:
  variant:
    # Keys to forcibly use for the variant computation (even if they are not in the dependencies)
    use_keys: [string]

    # Keys to forcibly ignore for the variant computation (even if they are in the dependencies)
    ignore_keys: [string]
```

https://github.com/search?q=org%3Aconda-forge+force_ignore_keys+language%3AYAML&type=code
https://github.com/search?q=org%3Aconda-forge+force_use_keys+language%3AYAML&type=code
