### ISSUE TITLE
Implement the `use_python_app_entrypoint`

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#523]
Was `osx_is_app` in `conda-build`

This is a seldomly used option that changes the shebang to `python.app` instead of `python` on macOS .

I am not sure what it does exactly, but conda-forge uses it in a few places: https://github.com/search?q=org%3Aconda-forge+osx_is_app+language%3AYAML&type=code

```yaml
build:
  python:
    # Specifies if python.app should be used as the entrypoint on macOS
    # was `osx_is_app`
    use_python_app_entrypoint: bool (defaults to false)  # macOS only!
```
