### ISSUE TITLE
Implement `preserve_egg_dir`

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#524]
Was `preserve_egg_dir` in `conda-build`.

Preserve the `egg` dir for Python packages.

> This is needed for some packages that use features specific to setuptools. The default is False.

Used a couple of times on conda-forge: https://github.com/search?q=org%3Aconda-forge+preserve_egg_dir+language%3AYAML&type=code

```yaml
build:
  python:
    # used on conda-forge, still needed?
    preserve_egg_dir: bool (default false)
```
