### ISSUE TITLE
Implement `skip_pyc_compilation`

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#525]
Was: `skip_compile_pyc` in `conda-build`.

And also implement `pyc` compilation for non-noarch packages.

> [!NOTE]
> This only applies to non noarch packages.

After building a package with `python` code inside, we usually attempt to compile any non-compiled `py` files to `pyc` in order to improve startup times and make installation & removal more deterministic (since we then know about all files in existence).

For this purpose a post-processing step finds all `py` files without corresponding `pyc` files and tries to compile them (not implemented yet!).

Sometimes, however, this is unwanted (and sometimes the `.py` files just do not compile properly). With this option, the `pyc` compilation can be skipped for some files.

```yaml
build:
  python:
    # skip compiling pyc for some files (was `skip_compile_pyc`)
    skip_pyc_compilation: [glob]
```

Usage on conda-forge: https://github.com/search?q=org%3Aconda-forge+skip_compile_pyc+language%3AYAML&type=code
