### ISSUE TITLE
Implement `prefix_detection` in build section

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#526]
Files are detected as either "binary" or "text" files based on the appearance of `\0` in the first couple of bytes.

When installing a text- or binary file, the prefix is replaced in different ways (for binary files it is padded with `\0`).

`conda-build` has an option to override wether a file should be detected as binary or text file.

https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#binary-has-prefix-files

```yaml
build:
  # settings concerning the prefix detection in files
  prefix_detection:
    # force the file type of the given files to be TEXT or BINARY
    # for prefix replacement
    force_file_type:
      # force TEXT file type
      # was `???`
      text: [glob]
      # force binary file type
      # was `???`
      binary: [glob]

    # ignore all or specific files for prefix replacement
    # was `ignore_prefix_files`
    ignore: bool | [path] (defaults to false)

    # wether to detect binary files with prefix or not
    # was `detect_binary_files_with_prefix` (note: logic reversed!).
    ignore_binary_files: bool (defaults to false on Unix and (always) true on Windows)
```

- https://github.com/search?q=org%3Aconda-forge+binary_has_prefix_files+language%3AYAML&type=code
- https://github.com/search?q=org%3Aconda-forge+has_prefix_files+language%3AYAML&type=code
- https://github.com/search?q=org%3Aconda-forge+ignore_prefix_files+language%3AYAML&type=code
- https://github.com/search?q=org%3Aconda-forge+detect_binary_files_with_prefix+language%3AYAML&type=code
