### ISSUE TITLE
rattler doesn't set rpath for binaries

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#529]
The following recipe fails on linux-64

```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: mssql-tools
  version: '18.2.1.1'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://packages.microsoft.com/rhel/7/prod/${{ name }}18-${{ version }}-1.x86_64.rpm
    sha256: 98758f29f1b1aad13c5ce32a5cf1e849d35a97054d030ee5dccdab6aefd2aef9

build:
  number: 0
  script:
    - bsdtar xf mssql-tools18-${{ version }}-1.x86_64.rpm
    - mkdir -p $PREFIX/bin
    - cp opt/mssql-tools18/bin/* $PREFIX/bin

requirements:
  build:
    - libarchive

tests:
  - package_contents:
      bin:
        - sqlcmd
        - bcp
  - script:
      - patchelf --print-rpath $CONDA_PREFIX/bin/bcp | grep -q \$ORIGIN/../lib
      - patchelf --print-rpath $CONDA_PREFIX/bin/sqlcmd | grep -q \$ORIGIN/../lib
    requirements:
      run:
        - patchelf
```

The corresponding conda-build recipe succeeds with `conda-build`
```yml
package:
  name: mssql-tools
  version: '18.2.1.1'

source:
  - url: https://packages.microsoft.com/rhel/7/prod/mssql-tools18-18.2.1.1-1.x86_64.rpm
    sha256: 98758f29f1b1aad13c5ce32a5cf1e849d35a97054d030ee5dccdab6aefd2aef9

build:
  number: 0
  script:
    # bsdtar not relevant because conda-build extracts it automatically
    - mkdir -p $PREFIX/bin
    - cp opt/mssql-tools18/bin/* $PREFIX/bin

test:
  commands:
  - patchelf --print-rpath $CONDA_PREFIX/bin/bcp | grep -q \$ORIGIN/../lib
  - patchelf --print-rpath $CONDA_PREFIX/bin/sqlcmd | grep -q \$ORIGIN/../lib
  requires:
    - patchelf
```

Would be nice to have this example as a unit test

**Comment by pavelzw** [comment]
A side note which i found strange:
When running `bcp` in the rattler-build tests, it worked (you need some other msodbc18 package as a run dependency) but when installing this package with `micromamba`, it doesn't work anymore... Then, it complained that it couldn't find `libodbc.so.2`.

Any idea why it could have worked in rattler-build but not outside?

**Comment by wolfv** [comment]
We recently changed the default "patchelf" implementation to use the builtin Rust version (#501 ). I wonder if you have the same problem with earlier rattler-build versions?

Also, do you have the logs somewhere? It should mention something about changing the rpath.

**Comment by 0xbe7a** [comment]
![image](https://github.com/prefix-dev/rattler-build/assets/6232980/1f6f4375-b363-478c-ac6d-d7a2ac25d7fd)

**Comment by pavelzw** [comment]
> I wonder if you have the same problem with earlier rattler-build versions?

This issue occurs both with rattler-build 0.7.0 and with rattler-build 0.7.1rc5 (latest main commit as of now)

**Comment by wolfv** [comment]
Argh, ok, so these binaries don't have an rpath and that's why our patching doesn't work... and also won't work with our current Rust implementation (not such a big deal since we can still use `patchelf`).

But looks like we need to force the `$PREFIX/lib` as an RPATH into the binary if no RPath is set to make these work.

**Comment by orhun** [comment]
I think it is closely related to the `rpath` option mentioned in #527:

```yaml
  # settings for shared libraries and executables
  dynamic_linking:
    # linux only, list of rpaths (was rpath)
    rpaths: [path] (defaults to ['lib/'])
```

> But looks like we need to force the $PREFIX/lib as an RPATH into the binary if no RPath is set to make these work.

Absolutely.

I started to work on the implementation.
