### ISSUE TITLE
Ordering outputs doesn't seem to work right for this example

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#550]
```yaml
context:
  name: emscripten_emscripten-wasm32
  version: 3.1.45

recipe:
  name: '${{ name|lower }}'
  version: '${{ version }}'


build:
  number: 15


outputs:
  - package:
      name: emscripten-abi
      version: '${{ version }}'
    build:
      noarch: generic
      script:
        - echo "emscripten abi is built."

  # TODO make run_exports work with boa
  - package:
      name: '${{ name | lower }}'
      version: '${{ version }}'

    build:
      script: build_compiler_package.sh

    requirements:
      build:
        - gettext
      run:
        - python
      run_exports:
        strong:
          - "${{ pin_compatible('emscripten-abi', min_pin='x.x.x', max_pin='x.x.x') }}"

```

Looks liek we might miss adding an edge from the run exports.
