### ISSUE TITLE
Flaky `Missing output: my-package (used in pin_subpackage)` error

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#553]
Let's take a look at this recipe:

```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: my-package
  version: '0.1.0'

outputs:
  - package:
      name: ${{ name }}
      version: ${{ version }}
    build:
      noarch: generic

  - package:
      name: ${{ name | replace('-', '_') }}
      version: ${{ version }}
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage(name, exact=true) }}
```

Often, the output is this as expected:

```
❯ rattler-build build -r r/recipe.yaml
No target platform specified, using current platform
Found variants:

my-package-0.1.0-h4616a5c_0
╭─────────────────┬─────────╮
│ Variant         ┆ Version │
╞═════════════════╪═════════╡
│ target_platform ┆ noarch  │
╰─────────────────┴─────────╯

my_package-0.1.0-h831704a_0
╭─────────────────┬──────────────────╮
│ Variant         ┆ Version          │
╞═════════════════╪══════════════════╡
│ my-package      ┆ 0.1.0 h4616a5c_0 │
│ target_platform ┆ noarch           │
╰─────────────────┴──────────────────╯

Work dir: "/private/tmp/rattler-test/output/bld/rattler-build_my-package_1706476231/work"
Build script: "/private/tmp/rattler-test/output/bld/rattler-build_my-package_1706476231/work/conda_build.sh"
Copying done!
Relink done!

Files in package:

  - info/about.json
  - info/hash_input.json
  - info/index.json
  - info/paths.json
  - info/recipe/recipe.yaml
  - info/recipe/rendered_recipe.yaml
  - info/recipe/variant_config.yaml
Creating target folder "/private/tmp/rattler-test/output/noarch"

Output: my-package-0.1.0-h4616a5c_0

Variant configuration:
┌─────────────────┬─────────┐
│ Variant         ┆ Version │
╞═════════════════╪═════════╡
│ target_platform ┆ noarch  │
└─────────────────┴─────────┘




Running tests
Removing previously cached package "/Users/pavel/Library/Caches/rattler/cache/pkgs/my-package-0.1.0-h4616a5c_0"
Creating test environment in "/private/tmp/rattler-test/output/bld/rattler-build_my-package_1706476231/work/test"
Collecting tests from "/Users/pavel/Library/Caches/rattler/cache/pkgs/my-package-0.1.0-h4616a5c_0"
Work dir: "/private/tmp/rattler-test/output/bld/rattler-build_my_package_1706476231/work"
Build script: "/private/tmp/rattler-test/output/bld/rattler-build_my_package_1706476231/work/conda_build.sh"
Copying done!
Relink done!

Files in package:

  - info/about.json
  - info/hash_input.json
  - info/index.json
  - info/paths.json
  - info/recipe/recipe.yaml
  - info/recipe/rendered_recipe.yaml
  - info/recipe/variant_config.yaml
Creating target folder "/private/tmp/rattler-test/output/noarch"

Output: my_package-0.1.0-h831704a_0

Variant configuration:
┌─────────────────┬──────────────────┐
│ Variant         ┆ Version          │
╞═════════════════╪══════════════════╡
│ my-package      ┆ 0.1.0 h4616a5c_0 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ target_platform ┆ noarch           │
└─────────────────┴──────────────────┘

Run dependencies:
╭────────────┬─────────────────────────╮
│ Name       ┆ Spec                    │
╞════════════╪═════════════════════════╡
│ my-package ┆ ==0.1.0 h4616a5c_0 (PS) │
╰────────────┴─────────────────────────╯




Running tests
Removing previously cached package "/Users/pavel/Library/Caches/rattler/cache/pkgs/my_package-0.1.0-h831704a_0"
Creating test environment in "/private/tmp/rattler-test/output/bld/rattler-build_my_package_1706476231/work/test"
Collecting tests from "/Users/pavel/Library/Caches/rattler/cache/pkgs/my_package-0.1.0-h831704a_0"
```

But sometimes, I get this error:

```
❯ rattler-build build -r r/recipe.yaml
No target platform specified, using current platform
Error:   × Missing output: my-package (used in pin_subpackage)
```

When I replace `${{ pin_subpackage(name, exact=true) }}` with `${{ pin_subpackage('my-package', exact=true) }}`, I cannot replicate the error.

I unfortunately couldn't find other patterns to reproduce this...
