### ISSUE TITLE
`recipe.build.number` doesn't throw an error

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#559]
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

recipe:
  version: '0.1.1'
  build:
    number: 1

outputs:
  - package:
      name: my-package
    build:
      noarch: generic
```

the build number part should be on the root level. rattler-build should throw an error instead of ignoring this issue

```
❯ rattler-build build -r r/recipe.yaml
No target platform specified, using current platform
Found variants:

my-package-0.1.1-h4616a5c_0
╭─────────────────┬─────────╮
│ Variant         ┆ Version │
╞═════════════════╪═════════╡
│ target_platform ┆ noarch  │
╰─────────────────┴─────────╯

Work dir: "/private/tmp/rattler-test/output/bld/rattler-build_my-package_1706548434/work"
Build script: "/private/tmp/rattler-test/output/bld/rattler-build_my-package_1706548434/work/conda_build.sh"
Copying done!
Relink done!

Files in package:

  - info/about.json
  - info/hash_input.json
  - info/index.json
  - info/paths.json
  - info/recipe/recipe.yaml
  - info/recipe/rendered_recipe.yaml
  - info/recipe/variant_config.yaml
Creating target folder "/private/tmp/rattler-test/output/noarch"

Output: my-package-0.1.1-h4616a5c_0

Variant configuration:
┌─────────────────┬─────────┐
│ Variant         ┆ Version │
╞═════════════════╪═════════╡
│ target_platform ┆ noarch  │
└─────────────────┴─────────┘




Running tests
Creating test environment in "/private/tmp/rattler-test/output/bld/rattler-build_my-package_1706548434/work/test"
Collecting tests from "/Users/pavel/Library/Caches/rattler/cache/pkgs/my-package-0.1.1-h4616a5c_0"
```
