### ISSUE TITLE
Add sha256 for local files

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#560]
It would be nice to be able to specify the `sha256` even for local files with
```yml
source:
  - path: my-file.zip
    sha256: ...
```
