### ISSUE TITLE
Using variant in env vars doesn't seem to work

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#562]
I thought that the following would work:

```yaml
package:
  name: bla
  version: "0.1.0"

build:
  script:
    env: 
      FOO: ${{ some_option }}
    content: |
      echo $FOO > $PREFIX/text.txt
```

With a variant config such as:

```yaml
some_option:
- "ABC"
- "DEF"
```

But turns out it fails with:

```
Error:   × Failed to parse recipe

Error:   × Parsing: expected a scalar value.
   ╭─[7:1]
 7 │     env: 
 8 │       FOO: ${{ some_option }}
   ·            ─────────┬────────
   ·                     ╰── expected a string value for `env`
 9 │     content: |
   ╰────

╭─ pixi ~/Programs/rattler-build ‹test-crazy-chars●›  
╰─$ cargo r -- build --recipe ./test-data/recipes/variant_config/recipe.yaml -m ./test-data/recipes/variant_config/variant_config.yaml                                     1 ↵
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/rattler-build build --recipe ./test-data/recipes/variant_config/recipe.yaml -m ./test-data/recipes/variant_config/variant_config.yaml`
No target platform specified, using current platform
Error:   × Failed to parse recipe

Error:   × Parsing: expected a scalar value.
   ╭─[7:1]
 7 │     env: 
 8 │       FOO: "${{ some_option }}"
   ·            ──────────┬─────────
   ·                      ╰── expected a string value for `env`
 9 │     content: |
   ╰────
```
