### ISSUE TITLE
Make `env.get...` return None?

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#575]
Currently we cannot return a Null value from the `env` object functions. It might be useful to _not_ set an env variable at all in the script env.

For example:

```
script:
  env:
    BLA: ${{ env.get("BLA") }} -> errors
    BLA: ${{ env.get_default("BLA", "") }} -> sets empy string
    BLA: ${{ eng["BLA"] }} -> not implemented, could return NULL and kick out BLA (because key/val with NULL is filtered).
```
