### ISSUE TITLE
rattler-build removes manually added rpaths on macOS

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#601]
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: mssql-tools
  version: '18.2.1.1'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - if: target_platform == 'osx-64'
    then:
      - url: https://download.microsoft.com/download/0/9/7/0976a30f-1710-4754-9445-bead058dd0c8/mssql-tools18-${{ version }}-amd64.tar.gz
        sha256: 1a2917ae45366e028eb4f5ca7d2a2396cfc06d659ae7b1ddc1d0bbee45a0d5fb
  - if: target_platform == 'osx-arm64'
    then:
      - url: https://download.microsoft.com/download/0/9/7/0976a30f-1710-4754-9445-bead058dd0c8/mssql-tools18-${{ version }}-arm64.tar.gz
        sha256: 964113d5fab28bd13bdc658be9c8a6fcbcde04882a1f09c0e8f135ec70dc8f5c

build:
  number: 0
  script:
    - install_name_tool -add_rpath "@loader_path/../lib/" bin/sqlcmd
    - mkdir -p $PREFIX/bin
    - cp bin/sqlcmd $PREFIX/bin

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - unixodbc 2.3.10

tests:
  - script:
    - otool -l `which sqlcmd` | grep -A 3 LC_RPATH | grep @loader_path/../lib
```

Running this on macOS arm or macOS intel, we will get an error. The rattler-build logs show the following:

```
2024-02-06T20:29:48.105801Z  WARN rattler_build::macos::link: Rpath not in prefix: @loader_path/../lib/ – removing it
2024-02-06T20:29:48.105826Z  WARN rattler_build::macos::link: 

builtin relink failed for /var/folders/rz/q1r4tv0n6ll38q18fbk419mc0000gn/T/mssql-toolssrYsLc/bin/sqlcmd: failed to relink dylib with builtin relink (new path is longer than old path). Please file an issue on Github!
```

The corresponding conda-build recipe works.
