### ISSUE TITLE
Unable to locate libpkgconf

### ISSUE THREAD

**Issue by brano543** [prefix-dev/rattler-build#608]
Hello guys,

I am trying to build muon library (https://github.com/annacrombie/muon), but failing with script unable to find libpkgconf. Is it a bug or am I doing something wrong?

**recipe.yaml**
```
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: "0.2.0"

package:
  name: muon
  version: ${{ version }}

source:
  git: https://github.com/annacrombie/muon
  rev: ${{ version }}

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - ninja
    - meson
    - cmake
    - libcurl
    - libarchive
    - pkg-config

about:
  homepage: https://github.com/annacrombie/muon
  license: GPL-3.0
  license_file: LICENSE
  summary: muon is an implementation of the meson build system in c99 with minimal dependencies.

```

**build.sh**
```
meson setup build
cd build
ninja build
meson test
meson install
```
**rattler-build build --recipe conda/pkg/muon --package-format conda --output-dir ./build/output**
```
+ meson setup build
The Meson build system
Version: 1.3.1
Source dir: /app/cpp_training_flakes/build/output/bld/rattler-build_muon_1707341827/work
Build dir: /app/cpp_training_flakes/build/output/bld/rattler-build_muon_1707341827/work/build
Build type: native build
Project name: muon
Project version: 0.2.0
C compiler for the host machine: $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc (gcc 13.2.0 "x86_64-conda-linux-gnu-cc (conda-forge gcc 13.2.0-5) 13.2.0")
C linker for the host machine: $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc ld.bfd 2.40
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Compiler for C supports arguments -Wno-missing-braces: YES 
Compiler for C supports arguments -Wendif-labels: YES 
Compiler for C supports arguments -Wimplicit-fallthrough=2: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wlogical-op: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Woverflow: YES 
Compiler for C supports arguments -Wstrict-aliasing=2: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -fstrict-aliasing: YES 
Configuring version.c using configuration
Found pkg-config: YES ($PREFIX/bin/pkg-config) 0.29.2
Run-time dependency libcurl found: YES 8.5.0
Run-time dependency libarchive found: YES 3.7.2
Found CMake: $PREFIX/bin/cmake (3.28.3)
Run-time dependency libpkgconf found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libpkgconf
Neither a subproject directory nor a pkgconf.wrap file was found.
Subproject  pkgconf is buildable: NO (disabling)
Dependency libpkgconf from subproject pkgconf found: NO (subproject failed to configure)
Dependency samurai skipped: feature samurai disabled
Run-time dependency bestline found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency bestline

Executing subproject bestline 

bestline| Project name: bestline
bestline| Project version: undefined
bestline| C compiler for the host machine: $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc (gcc 13.2.0 "x86_64-conda-linux-gnu-cc (conda-forge gcc 13.2.0-5) 13.2.0")
bestline| C linker for the host machine: $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc ld.bfd 2.40
bestline| Build targets in project: 3
bestline| Subproject bestline finished.

Dependency bestline found: YES undefined (overridden)
Run-time dependency tracy found: NO (tried pkgconfig and cmake)
Program python3 found: YES ($PREFIX/bin/python3)
Program test.sh found: YES (/app/cpp_training_flakes/build/output/bld/rattler-build_muon_1707341827/work/tests/fmt/test.sh)
Program afl-fuzz found: NO
Program ninja found: YES ($PREFIX/bin/ninja)
Program runner.sh found: YES (/app/cpp_training_flakes/build/output/bld/rattler-build_muon_1707341827/work/tests/project/runner.sh)
Program scdoc found: NO
Build targets in project: 4

muon 0.2.0

    libcurl   : true
    libarchive: true
    libpkgconf: false
    samurai   : false
    bestline  : true

  Subprojects
    bestline  : YES
    pkgconf   : NO
                Neither a subproject directory nor a pkgconf.wrap file was found.

Found ninja-1.11.1 at $PREFIX/bin/ninja
+ cd build
+ ninja build
ninja: error: unknown target 'build'
Error:   × Build failed
```

**Comment by eli-schwartz** [comment]
> **build.sh**
> 
> ```
> meson setup build
> cd build
> ninja build
> meson test
> meson install
> ```

The ninja program doesn't take a "build" argument.

It is just `ninja`.

It's the same as `make`. If you download a project that uses configure scripts, you just run `./configure && make`, you don't run `make build`.

**Comment by wolfv** [comment]
Hi @brano543 – exciting that you are trying out `rattler-build`!

Here is a working version of your `recipe.yaml` (tested on osx-arm64):

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: "0.2.0"

package:
  name: muon
  version: ${{ version }}

source:
  git: https://github.com/annacrombie/muon
  rev: ${{ version }}

build:
  number: 0
  script:
    # ${MESON_ARGS} expands to `--buildtype release --prefix=$PREFIX -Dlibdir=lib`
    # We need to install the files into the `prefix` directory 
    - meson ${MESON_ARGS} builddir
    - meson install -C builddir

requirements:
  build:
    - ${{ compiler('c') }}
    - ninja
    - meson
    - pkg-config
  host:
    - libcurl
    - libarchive

tests:
  - script:
      - muon -h

about:
  homepage: https://github.com/annacrombie/muon
  license: GPL-3.0
  license_file: LICENSE
  summary: muon is an implementation of the meson build system in c99 with minimal dependencies.
```

During the build process it doesn't find all the (optional) dependencies. E.g.:

```
Configuring version.c using configuration
Found pkg-config: YES ($BUILD_PREFIX/bin/pkg-config) 0.29.2
Run-time dependency libcurl found: YES 8.5.0
Found CMake: /opt/homebrew/bin/cmake (3.28.1)
Run-time dependency libarchive found: NO (tried pkgconfig, framework and cmake)
Run-time dependency libpkgconf found: NO (tried pkgconfig, framework and cmake)
Looking for a fallback subproject for the dependency libpkgconf
Neither a subproject directory nor a pkgconf.wrap file was found.
Subproject  pkgconf is buildable: NO (disabling)
Dependency libpkgconf from subproject pkgconf found: NO (subproject failed to configure)
Dependency samurai skipped: feature samurai disabled
Run-time dependency bestline found: NO (tried pkgconfig, framework and cmake)
Looking for a fallback subproject for the dependency bestline

Executing subproject bestline 

bestline| Project name: bestline
bestline| Project version: undefined
bestline| C compiler for the host machine: arm64-apple-darwin20.0.0-clang (clang 17.0.6 "clang version 17.0.6")
bestline| C linker for the host machine: arm64-apple-darwin20.0.0-clang ld64 609
bestline| Build targets in project: 3
bestline| Subproject bestline finished.

Dependency bestline found: YES undefined (overridden)
Run-time dependency tracy found: NO (tried pkgconfig, framework and cmake)
Program python3 found: YES ($BUILD_PREFIX/bin/python3)
Program test.sh found: YES (/Users/wolfv/Programs/rattler-build/output/bld/rattler-build_muon_1707379919/work/tests/fmt/test.sh)
Program afl-fuzz found: NO
Program ninja found: YES ($BUILD_PREFIX/bin/ninja)
Program runner.sh found: YES (/Users/wolfv/Programs/rattler-build/output/bld/rattler-build_muon_1707379919/work/tests/project/runner.sh)
Program scdoc found: NO
Build targets in project: 4

muon 0.2.0

    libcurl   : true
    libarchive: false
    libpkgconf: false
    samurai   : false
    bestline  : true

  Subprojects
    bestline  : YES
    pkgconf   : NO
                Neither a subproject directory nor a pkgconf.wrap file was found.

  User defined options
    buildtype : release
    libdir    : lib
    prefix    : $PREFIX

Found ninja-1.11.1 at $BUILD_PREFIX/bin/ninja
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
+ meson install -C builddir
```

**Comment by brano543** [comment]
> Hi @brano543 – exciting that you are trying out rattler-build!

Thank you for making this possible. The conda-build command takes forever to build anything. I don't know why does it take so much time to process. I hope we can all standardize the recipes and keep up the ecosystem of both mamba and rattler-build.

The above recipe was failing for me unfortunately, but I was able to figure it out in the end.
```
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: "0.2.0"

package:
  name: muon
  version: ${{ version }}

source:
  git: https://github.com/annacrombie/muon
  rev: ${{ version }}

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - ninja
    - meson

about:
  homepage: https://github.com/annacrombie/muon
  license: GPL-3.0
  license_file: LICENSE
  summary: muon is an implementation of the meson build system in c99 with minimal dependencies.
```
**build.sh**
```
./bootstrap.sh build
build/muon setup -D prefix=$PREFIX build 
build/muon -C build install
```
