### ISSUE TITLE
Wrong ordering of multiple outputs

### ISSUE THREAD

**Issue by fpaniagua** [prefix-dev/rattler-build#614]
note: using v0.9.0

I am using context variables for names of packages and outputs section to generate multiple packages.

Some of these packages depend on each other, and from reading the docs I needed to use `pin_subpackage`.

I try something like `pin_subpackage(name, ...)` where `name` is a context variable. The building order appears random and get error message like:
```shell
Error:   × Could not apply pin. The following subpackage is not available: PackageName { normalized: None, source: "some-pkg-a" }
```

Here is an example recipe that does not work:
```yaml
context:
  name: some-pkg
  name_a: ${{ name }}-a
  version: 1.0.0
  build_number: 0

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: ../

outputs:
  - package:
      name: ${{ name }}
      version: ${{ version }}
    build:
      noarch: python
      number: ${{ build_number }}
    requirements:
      host:
        - python >=3.10
        - pip
      run:
        - ${{ pin_subpackage(name_a, min_pin="x.x.x") }}
        - python >=3.10
  - package:
      name: ${{ name_a }}
      version: ${{ version }}
    build:
      noarch: python
      number: ${{ build_number }}
    requirements:
      host:
        - python >=3.10
        - pip
      run:
        - python >=3.10
```

Its a simplified version, where there's 2 packages, and 1 depends on the other.

Sometimes it builds in the right order, sometimes not. Expanding this out to more packages, it almost always fails.

However, making this small change: `${{ pin_subpackage(name_a, min_pin="x.x.x") }}` -> `${{ pin_subpackage('some-pkg-a', min_pin="x.x.x") }}` does appear to fix it.

I also had used something like `${{ pin_subpackage(name ~ "-a", ...) }}` which also does not work for build order.
