### ISSUE TITLE
Make searching for `prefix_placeholder` string and make async/parallel (and add progress bar?)

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#621]
We are currently searching for the prefix placeholder string in the files one-by-one. It does take a little while for larger files. Would be nice to 

1. make the function async
2. parallelize it and run over multiple files at once
3. Or even parallize it for single large files (chunk the file up and run multiple threads)

**Comment by wolfv** [comment]
Example of a big file package:

```yaml
package:
  name: big
  version: "0.1.0"

build:
  # prefix_detection:
  #   ignore_binary_files: true
  script:
    - dd if=/dev/urandom of=$PREFIX/bigfile bs=1M count=1000

```
