### ISSUE TITLE
Add system theme for documentation

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#638]
It would be nice to add support for the preferred system theme in the docs.

I usually did that with the following configuration:

```yml
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: black

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: black
```

This needs to be adjusted to the prefix-dev color scheme probably...
