### ISSUE TITLE
Config files: mixing top level selectors and non-selected is buggy

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#65]
```yaml
python:
- '3.9'
- '3.10'
- '3.11'

sel(linux):
  compiler:
    - 3.10
```

removes the `python: ...` variants.
