### ISSUE TITLE
Multi output builds with variants are broken when skipping some outputs

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#689]
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

recipe:
  version: '0.1.0'
build:
  number: 0

outputs:
  - package:
      name: package-base
    build:
      noarch: generic
      skip: new_pydantic

  - package:
      name: package
    build:
      noarch: python
    requirements:
      host:
        - ${{ pin_subpackage('package-base', exact=true) }}
        - if: new_pydantic
          then:
            - pydantic >=2
          else:
            - pydantic >=1,<2
```

```yml
new_pydantic:
  - true
  - false
```

```
❯ rattler-build build -r conda.recipe/recipe.yaml -m conda.recipe/variants.yaml
 Target platform: osx-arm64

 ╭─ Finding outputs from recipe
 │ Found 4 variants
 │ Build variant: package-base-0.1.0-h1a4448f_0
 │ ╭─────────────────┬─────────╮
 │ │ Variant         ┆ Version │
 │ ╞═════════════════╪═════════╡
 │ │ new_pydantic    ┆ true    │
 │ │ target_platform ┆ noarch  │
 │ ╰─────────────────┴─────────╯
 │ Build variant: package-0.1.0-pyh1a4448f_0
 │ ╭─────────────────┬─────────╮
 │ │ Variant         ┆ Version │
 │ ╞═════════════════╪═════════╡
 │ │ new_pydantic    ┆ true    │
 │ │ target_platform ┆ noarch  │
 │ ╰─────────────────┴─────────╯
 │ Build variant: package-base-0.1.0-he8c018c_0
 │ ╭─────────────────┬─────────╮
 │ │ Variant         ┆ Version │
 │ ╞═════════════════╪═════════╡
 │ │ new_pydantic    ┆ false   │
 │ │ target_platform ┆ noarch  │
 │ ╰─────────────────┴─────────╯
 │ Build variant: package-0.1.0-pyhe8c018c_0
 │ ╭─────────────────┬─────────╮
 │ │ Variant         ┆ Version │
 │ ╞═════════════════╪═════════╡
 │ │ new_pydantic    ┆ false   │
 │ │ target_platform ┆ noarch  │
 │ ╰─────────────────┴─────────╯
 │
 ╰─────────────────── (took 0 seconds)
 Skipping build for variant: {
     "new_pydantic": "true",
     "target_platform": "noarch",
 }

 ╭─ Running build for recipe: package-0.1.0-pyh1a4448f_0
 │
 │ ╭─ Fetching source code
 │ │ No sources to fetch
 │ │
 │ ╰─────────────────── (took 0 seconds)
 │
 │ ╭─ Resolving environments
 │ │
 │ ╰─────────────────── (took 0 seconds)
 │
 ╰─────────────────── (took 0 seconds)
 × error Error building package: Could not apply pin. The following subpackage is not available: PackageName { normalized: None, source: "package-base" }
Error:   × Could not apply pin. The following subpackage is not available: PackageName { normalized: None, source: "package-base" }
```

Please also add a test for this edge case 🙏🏻

**Comment by wolfv** [comment]
Hmm, I wonder what the expected output is, here. Do you expect the `exact=true` pin to point to the variant of the `new_pydantic=false` package? 

Currently we (conceptually) treat a recipe variant over the entire file. So in this case, rattler-build thinks that the `package-base` doesn't exist for `new_pydantic=false` and then fails.

However, it also fails when not "exactly" pinning. So something seems fishy nonetheless and worth looking into!

**Comment by wolfv** [comment]
Hmm, well, the other assumption for `pin_subpackage` is that the "subpackage" is available when rendering with that specific variant.

Well, something to think about.

**Comment by pavelzw** [comment]
If we decide not to support this, i'm wondering what the best alternative for this example would be... In conda-build (and older rattler-build versions) it works 🤔

**Comment by wolfv** [comment]
Hmm, I double checked this. Actually, it's not necessary to skip anything - since `new_pydantic` is not used in the `base` package, the hash is always the same and it builds only three packages in the right order.

```yaml
recipe:
  version: '0.1.0'
build:
  number: 0

outputs:
  - package:
      name: package-base
    build:
      noarch: generic

  - package:
      name: package
    build:
      noarch: python
    requirements:
      host:
        - ${{ pin_subpackage('package-base', exact=true) }}
        - if: new_pydantic
          then:
            - pydantic >=2
          else:
            - pydantic >=1,<2
```

Let me know if that works fine for your use case?
