### ISSUE TITLE
Can't force a dependency to come from a particular channel

### ISSUE THREAD

**Issue by mariusvniekerk** [prefix-dev/rattler-build#706]
In conda-build / boa you can force a dependency to come from a particular channel by specifying it with the matchspec

```
my-special-channel::packagename =1.5.4
```

I tried doing the same with rattler-build and it does not seem to work

Ideally we should be able to specify a dependency in the expanded form without needing to resort to the esoteric matchspec stuff

```yaml
 - if: unix
   then:
      name: packagename
      version: 1.5.4
      channel: my-special-channel

```

**Comment by mariusvniekerk** [comment]
According to the conda-build source it just makes use of the regular MatchSpec now

https://github.com/conda/conda-build/blob/1d390f84244f1501715d355a2bd2244bd9b9e530/conda_build/metadata.py#L1572

which is called from

https://github.com/conda/conda-build/blob/1d390f84244f1501715d355a2bd2244bd9b9e530/conda_build/build.py#L2167-L2171

**Comment by wolfv** [comment]
Good news! I just tested and this works in the latest version of `rattler-build` (probably a side effect of switching to the new repodata gateway) :)

You still have to manually add the channel(s) though. I tested with the followign:

```yaml
package:
  name: specific
  version: 1.0.0

requirements:
  host:
    - quantstack::sphinx
```

And invoked with 

```
rattler-build build --recipe ./examples/specific/ -c conda-forge -c quantstack
```
