### ISSUE TITLE
rattler-build prints wrong error messages

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#714]
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: test-package
  version: 0.1.0

tests:
  - abc:
      - echo hello
```

```bash
❯ rattler-build build -r recipe/recipe.yaml
 Target platform: osx-arm64

 ╭─ Finding outputs from recipe
 │
 ╰─────────────────── (took 0 seconds)
Error:   × Failed to parse recipe

Error:   × Parsing: invalid field `abc`.
   ╭─[8:5]
 7 │ tests:
 8 │   - abc:
   ·     ─┬─
   ·      ╰── here
 9 │       - echo hello
   ╰────
  help: expected fields for tests is one of `python`, `command`, `downstream`, `package_contents`
```

`command` should be `script`
