### ISSUE TITLE
Variant configuration displayed wrongly after successful build

### ISSUE THREAD

**Issue by RobinHolzingerQC** [prefix-dev/rattler-build#742]
# Context

I want to define 2 conda packages with different names `rattler-build-demo` and `rattler-build-demo-subpackage` in my `recipe.yaml`. The second one imports the dependencies of the first transitively.

Additionally, the subpackage needs two build runs, one for UNIX and one for Windows. In the example below I just added `pydantic` conditionally on `unix`.

When I built the package for UNIX, the output build strings and dependencies seemed fine.

## Minimum example

A minimum example can be found [here](https://github.com/RobinHolzingerQC/rattler-build-demo).

Just run `make build` to reproduce the issue.

## Issue

However, the following status log messages seem to not respect the `build_variant` variable correctly.

```bash
 ╭─ Build summary
 │
 │ ╭─ Build summary for recipe: rattler-build-demo-1-unix_4616a5c_0
 │ │ Artifact: .../noarch/rattler-build-demo-1-unix_4616a5c_0.conda (4.58 KiB)
 │ │ Variant configuration (hash: unix_4616a5c_0):
 │ │ ╭─────────────────┬────────╮
 │ │ │ target_platform ┆ noarch │
 │ │ ╰─────────────────┴────────╯
 │ │ 
 │ │ Host dependencies:
 │ │ ╭───────────────────┬────────────────┬──────────────┬────────────────────┬─────────────┬────────────╮
 │ │ │ Package           ┆ Spec           ┆ Version      ┆ Build              ┆ Channel     ┆       Size │
 │ │ ╞═══════════════════╪════════════════╪══════════════╪════════════════════╪═════════════╪════════════╡
 │ │ │ pip               ┆ pip            ┆ 24.0         ┆ pyhd8ed1ab_0       ┆ conda-forge ┆   1.33 MiB │
 │ │ │ python            ┆ python >=3.11  ┆ 3.12.2       ┆ hdf0ec26_0_cpython ┆ conda-forge ┆  12.48 MiB │
 │ │ │ setuptools-scm    ┆ setuptools-scm ┆ 8.0.4        ┆ pyhd8ed1ab_1       ┆ conda-forge ┆  35.77 KiB │
 │ │ │ bzip2             ┆                ┆ 1.0.8        ┆ h93a5062_5         ┆ conda-forge ┆ 119.46 KiB │
 │ │ │ ca-certificates   ┆                ┆ 2024.2.2     ┆ hf0a4a13_0         ┆ conda-forge ┆ 152.08 KiB │
 │ │ │ libexpat          ┆                ┆ 2.6.2        ┆ hebf3989_0         ┆ conda-forge ┆  62.16 KiB │
 │ │ │ libffi            ┆                ┆ 3.4.2        ┆ h3422bc3_5         ┆ conda-forge ┆  38.11 KiB │
 │ │ │ libsqlite         ┆                ┆ 3.45.2       ┆ h091b4b1_0         ┆ conda-forge ┆ 805.96 KiB │
 │ │ │ libzlib           ┆                ┆ 1.2.13       ┆ h53f4e23_5         ┆ conda-forge ┆  46.97 KiB │
 │ │ │ ncurses           ┆                ┆ 6.4.20240210 ┆ h078ce10_0         ┆ conda-forge ┆ 801.02 KiB │
 │ │ │ openssl           ┆                ┆ 3.2.1        ┆ h0d3ecfb_1         ┆ conda-forge ┆   2.72 MiB │
 │ │ │ packaging         ┆                ┆ 24.0         ┆ pyhd8ed1ab_0       ┆ conda-forge ┆  48.66 KiB │
 │ │ │ readline          ┆                ┆ 8.2          ┆ h92ec313_1         ┆ conda-forge ┆ 244.48 KiB │
 │ │ │ setuptools        ┆                ┆ 69.2.0       ┆ pyhd8ed1ab_0       ┆ conda-forge ┆ 460.14 KiB │
 │ │ │ tk                ┆                ┆ 8.6.13       ┆ h5083fa2_1         ┆ conda-forge ┆   3.00 MiB │
 │ │ │ tomli             ┆                ┆ 2.0.1        ┆ pyhd8ed1ab_0       ┆ conda-forge ┆  15.57 KiB │
 │ │ │ typing-extensions ┆                ┆ 4.10.0       ┆ hd8ed1ab_0         ┆ conda-forge ┆   9.94 KiB │
 │ │ │ typing_extensions ┆                ┆ 4.10.0       ┆ pyha770c72_0       ┆ conda-forge ┆  36.15 KiB │
 │ │ │ tzdata            ┆                ┆ 2024a        ┆ h0c530f3_0         ┆ conda-forge ┆ 117.01 KiB │
 │ │ │ wheel             ┆                ┆ 0.43.0       ┆ pyhd8ed1ab_1       ┆ conda-forge ┆  56.60 KiB │
 │ │ │ xz                ┆                ┆ 5.2.6        ┆ h57fd34a_0         ┆ conda-forge ┆ 230.17 KiB │
 │ │ ╰───────────────────┴────────────────┴──────────────┴────────────────────┴─────────────┴────────────╯
 │ │ 
 │ │ Run dependencies:
 │ │ ╭─────────┬────────────────────────╮
 │ │ │ Name    ┆ Spec                   │
 │ │ ╞═════════╪════════════════════════╡
 │ │ │ Depends ┆                        │
 │ │ │ __unix  ┆                        │
 │ │ │ python  ┆ >=3.11                 │
 │ │ │ python  ┆ (RE of [host: python]) │
 │ │ ╰─────────┴────────────────────────╯
 │ │ 
 │ │
 │ ╰─────────────────── (took 0 seconds)
 │
 │ ╭─ Build summary for recipe: rattler-build-demo-subpackage-1-unix_b28fc4d_0
 │ │ Artifact: /Users/robinholzinger/quantco/aramis/rattler-build-demo/output/noarch/rattler-build-demo-subpackage-1-unix_b28fc4d_0.conda (1.86 KiB)
 │ │ Variant configuration (hash: unix_b28fc4d_0):
 │ │ ╭────────────────────┬─────────────────╮
 │ │ │ rattler-build-demo ┆ 1 win_4616a5c_0 │
 │ │ │ target_platform    ┆ noarch          │
 │ │ ╰────────────────────┴─────────────────╯
 │ │ 
 │ │ Run dependencies:
 │ │ ╭────────────────────┬─────────────────────────╮
 │ │ │ Name               ┆ Spec                    │
 │ │ ╞════════════════════╪═════════════════════════╡
 │ │ │ Depends            ┆                         │
 │ │ │ rattler-build-demo ┆ ==1 unix_4616a5c_0 (PS) │
 │ │ │ pydantic           ┆ <2.3.12                 │
 │ │ ╰────────────────────┴─────────────────────────╯
 │ │ 
 │ │
 │ ╰─────────────────── (took 0 seconds)
 │
 ╰─────────────────── (took 0 seconds)
```

The issue lies within:

```python
 │ │ │ rattler-build-demo ┆ 1 win_4616a5c_0 │
```

I would expect the following though:
```
 │ │ │ rattler-build-demo ┆ 1 unix_4616a5c_0 │
```

**Comment by RobinHolzingerQC** [comment]
fyi. @pavelzw

**Comment by pavelzw** [comment]
This is a stripped down failing example that doesn't require a source:

```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  name: rattler-build-demo
  version: 1
  build_variant: ${{ 'unix' if unix else 'win' }}
  build_number: 0

outputs:
  - package:
      name: ${{ name }}
      version: ${{ version }}
    build:
      noarch: generic
      number: ${{ build_number }}
      string: ${{ build_variant }}_${{ hash }}_${{ build_number }}
    requirements:
      run:
        - ${{ "__unix" if unix }}
        - ${{ "__win" if win }}

  - package:
      name: ${{ name }}-subpackage
      version: ${{ version }}
    build:
      noarch: generic
      number: ${{ build_number }}
      string: ${{ build_variant }}_${{ hash }}_${{ build_number }}
    requirements:
      run:
        - ${{ pin_subpackage('rattler-build-demo', exact=True) }}
        - ${{ "pydantic <2.3.12" if unix }}
```

```
❯ rattler-build build -r recipe/recipe.yaml --render-only
 Target platform: osx-arm64

 ╭─ Finding outputs from recipe
 │ Found 2 variants
 │ Build variant: rattler-build-demo-1-win_4616a5c_0
 │
 │ ╭─────────────────┬─────────╮
 │ │ Variant         ┆ Version │
 │ ╞═════════════════╪═════════╡
 │ │ target_platform ┆ noarch  │
 │ ╰─────────────────┴─────────╯
 │ Build variant: rattler-build-demo-subpackage-1-win_b28fc4d_0
 │
 │ ╭────────────────────┬─────────────────╮
 │ │ Variant            ┆ Version         │
 │ ╞════════════════════╪═════════════════╡
 │ │ rattler-build-demo ┆ 1 win_4616a5c_0 │
 │ │ target_platform    ┆ noarch          │
 │ ╰────────────────────┴─────────────────╯
 │
 ╰─────────────────── (took 0 seconds)

 ╭─ Resolving environments
 │
 │ Finalized run dependencies:
 │ ╭─────────┬──────╮
 │ │ Name    ┆ Spec │
 │ ╞═════════╪══════╡
 │ │ Depends ┆      │
 │ │ __unix  ┆      │
 │ ╰─────────┴──────╯
 │
 ╰─────────────────── (took 0 seconds)

 ╭─ Resolving environments
 │
 │ Finalized run dependencies:
 │ ╭────────────────────┬─────────────────────────╮
 │ │ Name               ┆ Spec                    │
 │ ╞════════════════════╪═════════════════════════╡
 │ │ Depends            ┆                         │
 │ │ rattler-build-demo ┆ ==1 unix_4616a5c_0 (PS) │
 │ ╰────────────────────┴─────────────────────────╯
 │
 ╰─────────────────── (took 0 seconds)
# ...
```
