### ISSUE TITLE
When building `go` packages, the process fails to remove the build directory

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#776]
There is a permission error when building Go packages. 

I am not sure exactly _why_ this happens and if it could be configured in the `go` compiler, package, but it seems like Go downloads binaries and uses a differnet user or no write permissions on that cache.

The error looks something like:

```
 ╰─────────────────── (took 48 seconds)
 × error Error building package: failed to remove directory `/Users/wolfv/Programs/recipes/new/output/bld/rattler-build_temporal_1712562447`
Error:   × failed to remove directory `/Users/wolfv/Programs/recipes/new/output/bld/rattler-build_temporal_1712562447`
  ╰─▶ Permission denied (os error 13)
```

recipe:

```yaml
context:
  version: "0.11.0"

package:
  name: temporal
  version: ${{ version }}

source:
  url: https://github.com/temporalio/cli/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 9cc4e80254e95a3b456e7d605b518c1a3e4d62b92a08a05efd6cf897ce4b2f3e

build:
  script:
    env:
      EXTRA_LDFLAGS: "-s -w -X github.com/temporalio/cli/headers.Version=${{ version}}"
    content: |
      go build -o=$PREFIX/bin/temporal -ldflags="$EXTRA_LDFLAGS" ./cmd/temporal

requirements: 
  build:
    - ${{ compiler('go') }}

tests:
  - script:
      - temporal --version
```
