### ISSUE TITLE
Add `perl` test section?

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#790]
Apparently conda-build has some magic that makes the `test.import` section also work for `perl`.

For example here: 

```
{% set name = "perl-data-dumper" %}
{% set version = "2.183" %}
{% set sha256 = "e42736890b7dae1b37818d9c5efa1f1fdc52dec04f446a33a4819bf1d4ab5ad3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/N/NW/NWCLARK/Data-Dumper-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # nothing provides perl >=5.32.1,<6.0a0 *_perl5 needed by perl-extutils-makemaker-7.36-pl5321hd8ed1ab_0
  skip: true  # [win]
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - Data::Dumper

about:
  home: https://metacpan.org/pod/Data::Dumper
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: 'seeds germane, yet not germinated'
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
```

**Comment by danielnachun** [comment]
That magic lives here: https://github.com/conda/conda-build/blob/3cf75b660e73babd4772d2cf65ac0026406ca558/conda_build/create_test.py, and it actually supports R and Lua as well.

I've been mass migrating all my personal recipes and feedstocks I manage in conda-forge over to `rattler-build` (it's worth it when it's 60x faster for some builds) and the lack of this feature is a huge blocker for migrating Perl recipes.

A couple of thoughts on this:
- This should support Perl, R, Lua, Ruby, and should probably also work for NodeJS (though shipping libraries for that ecosystem through Conda is not as useful).
- Eventually it might be worth linting in conda-forge and bioconda (when they support rattler-build) for using this kind of mechanism instead of the user trying to hand code basic import tests which is prone to error
- I don't really like the auto-generated tests for Perl from `conda-build` because they use a brittle mechanism to check if the version of the Perl module matches what is declared in the recipe.  Annoyingly a surprising number of Perl modules return a different value for `Module->VERSION` than what is on CPAN, which leads to test failures for something that isn't really important.

What is needed for this to be implemented?  I'm not a rust expert but happy to help as I can!

**Comment by wolfv** [comment]
Hi @danielnachun thanks for stopping by! Yes, I sorta looked through all that magic as well back in the days, but for my taste it's too much magic :)

I would propose two things:

Like `python` as interpreter, we can make `perl` (and others) as a script interpreter work, so that the following would work:

```yaml
script:
  interpreter: perl
  contents: |
    use strict;
    use warnings;
    use Config;

    print "Hello World!\n";
    print "Perl prefix: $Config{prefix}\n";
```

That would also give an "easy" way to roll your own import tests.

When that works, we could use this to create a `perl` test section.

**Comment by wolfv** [comment]
@danielnachun I started the implementation for using `perl` as a script interpreter in #1229 

To add a perl-specific test section we should come up with a list of entries we would like, for example:

```yaml
tests:
  - perl:
      imports: [ ... ]? # is imports the right word for perl?
      check_version: true/false?
```

And that would be just a convenience wrapper around the `script` with interpreter perl, essentially. Maybe you have thoughts on what an ideal perl test section would look like.
