### ISSUE TITLE
Cannot add `$ORIGIN` to `rpath_allowlist`

### ISSUE THREAD

**Issue by chebee7i** [prefix-dev/rattler-build#816]
I have the following section in my `recipe.yaml`:
```
build:                        
  number: 0                   
  dynamic_linking:            
    rpath_allowlist:          
      - "$ORIGIN"             
      - "$ORIGIN/../.."       
```

but this doesn't seem to achieve what I want:
```
╭─ Packaging new files
│ Copying done!
│ Rpath not in prefix or allow-listed: $ORIGIN – removing it
│ Rpath not in prefix or allow-listed: $ORIGIN/../.. – removing it
│ New relative path: $ORIGIN/../..
```
```
$ rattler-build --version
rattler-build 0.14.2
```

**Comment by chebee7i** [comment]
It seems that I can do this just with `rpaths`, as in:
```
build:                                   
  number: 0                              
  dynamic_linking:                       
    rpaths:                              
      - "lib/"                           
      - "lib/python3.8/site-packages"    
 ```
