### ISSUE TITLE
cross-building for osx-arm64 from linux-64

### ISSUE THREAD

**Issue by mittagessen** [prefix-dev/rattler-build#817]
I've been porting my old conda-build/boa build system to rattler-build and it works marvelously apart from an issue I've encountered when cross-building for osx-arm64 from linux-64 (both on my personal system and from a github-action workflow). My recipe is below:

```
context:
  git_url: .
  git_tag: ${{ git.latest_tag(git_url) }}

package:
  name: kraken
  version: ${{ git_tag }}

source:
  git: ${{ git_url }}
  tag: ${{ git_tag }}

build:
  script: pip install --no-deps .

requirements:
  build:
    - python>=3.8,<3.12
    - setuptools
    - pbr
  host:
     - python>=3.8,<3.12
  run:
     - python>=3.8,<3.12
     - python-bidi
     - lxml
     - regex
     - requests
     - click>=8.1
     - numpy~=1.23.0
     - pillow>=9.2.0
     - scipy~=1.11.0
     - jinja2~=3.0
     - torchvision
     - pytorch~=2.1.0
     - cudatoolkit
     - jsonschema
     - scikit-image~=0.21.0
     - scikit-learn~=1.2.1
     - shapely~=1.8.5
     - pyvips
     - coremltools
     - pyarrow
     - lightning~=2.2
     - torchmetrics>=1.1.0
     - conda-forge::threadpoolctl~=3.4.0
     - albumentations
     - rich
```

and I'm building with:

```
$ rattler-build build --experimental -r conda/recipe.yaml --target-platform osx-arm64
```

from the base of the git repository (https://github.com/mittagessen/kraken).

The build errors out when linking dependencies:

```
....
 │ ╭─ Resolving environments
 │ │ 
 │ │ Resolving environment for:
 │ │   Platform: linux-64
 │ │   Channels: 
 │ │    - /home/mittagessen/git/kraken/output
 │ │    - conda-forge
 │ │   Specs:
 │ │    - python >=3.8,<3.12
 │ │    - setuptools
 │ │    - pbr
 │ │ ✔ /home/mittagessen/gi [00:00:00] Using cache
 │ │ 
 │ │ ╭──────────────────┬──────────────┬────────────────────┬─────────────┬────────────╮
 │ │ │ Package          ┆ Version      ┆ Build              ┆ Channel     ┆ Size       │
 │ │ ╞══════════════════╪══════════════╪════════════════════╪═════════════╪════════════╡
 │ │ │ pbr              ┆ 6.0.0        ┆ pyhd8ed1ab_0       ┆ conda-forge ┆ 71.39 KiB  │
 │ │ │ pip              ┆ 24.0         ┆ pyhd8ed1ab_0       ┆ conda-forge ┆ 1.33 MiB   │
 │ │ │ wheel            ┆ 0.43.0       ┆ pyhd8ed1ab_1       ┆ conda-forge ┆ 56.60 KiB  │
 │ │ │ python           ┆ 3.11.9       ┆ hb806964_0_cpython ┆ conda-forge ┆ 29.45 MiB  │
 │ │ │ xz               ┆ 5.2.6        ┆ h166bdaf_0         ┆ conda-forge ┆ 408.56 KiB │
 │ │ │ readline         ┆ 8.2          ┆ h8228510_1         ┆ conda-forge ┆ 274.86 KiB │
 │ │ │ ncurses          ┆ 6.4.20240210 ┆ h59595ed_0         ┆ conda-forge ┆ 874.68 KiB │
 │ │ │ libuuid          ┆ 2.38.1       ┆ h0b41bf4_0         ┆ conda-forge ┆ 32.81 KiB  │
 │ │ │ libsqlite        ┆ 3.45.3       ┆ h2797004_0         ┆ conda-forge ┆ 839.71 KiB │
 │ │ │ libnsl           ┆ 2.0.1        ┆ hd590300_0         ┆ conda-forge ┆ 32.62 KiB  │
 │ │ │ libexpat         ┆ 2.6.2        ┆ h59595ed_0         ┆ conda-forge ┆ 72.00 KiB  │
 │ │ │ libxcrypt        ┆ 4.4.36       ┆ hd590300_1         ┆ conda-forge ┆ 98.04 KiB  │
 │ │ │ libzlib          ┆ 1.2.13       ┆ hd590300_5         ┆ conda-forge ┆ 60.14 KiB  │
 │ │ │ openssl          ┆ 3.2.1        ┆ hd590300_1         ┆ conda-forge ┆ 2.73 MiB   │
 │ │ │ tk               ┆ 8.6.13       ┆ noxft_h4845f30_101 ┆ conda-forge ┆ 3.17 MiB   │
 │ │ │ bzip2            ┆ 1.0.8        ┆ hd590300_5         ┆ conda-forge ┆ 248.27 KiB │
 │ │ │ libffi           ┆ 3.4.2        ┆ h7f98852_5         ┆ conda-forge ┆ 56.93 KiB  │
 │ │ │ ld_impl_linux-64 ┆ 2.40         ┆ h55db66e_0         ┆ conda-forge ┆ 696.60 KiB │
 │ │ │ libgcc-ng        ┆ 13.2.0       ┆ h807b86a_5         ┆ conda-forge ┆ 752.45 KiB │
 │ │ │ _libgcc_mutex    ┆ 0.1          ┆ conda_forge        ┆ conda-forge ┆ 2.50 KiB   │
 │ │ │ _openmp_mutex    ┆ 4.5          ┆ 2_gnu              ┆ conda-forge ┆ 23.07 KiB  │
 │ │ │ libgomp          ┆ 13.2.0       ┆ h807b86a_5         ┆ conda-forge ┆ 409.91 KiB │
 │ │ │ tzdata           ┆ 2024a        ┆ h0c530f3_0         ┆ conda-forge ┆ 117.01 KiB │
 │ │ │ setuptools       ┆ 69.5.1       ┆ pyhd8ed1ab_0       ┆ conda-forge ┆ 490.03 KiB │
 │ │ │ ca-certificates  ┆ 2024.2.2     ┆ hbcca054_0         ┆ conda-forge ┆ 151.79 KiB │
 │ │ ╰──────────────────┴──────────────┴────────────────────┴─────────────┴────────────╯
 │ │ ✔ Successfully updated the environment
 │ │ 
 │ │ Resolving environment for:
 │ │   Platform: osx-arm64
 │ │   Channels: 
 │ │    - /home/mittagessen/git/kraken/output
 │ │    - conda-forge
 │ │   Specs:
 │ │    - python >=3.8,<3.12
 │ │ ✔ /home/mittagessen/gi [00:00:00] Using cache
 │ │ 
 │ │ ╭─────────────────┬──────────────┬────────────────────┬─────────────┬────────────╮
 │ │ │ Package         ┆ Version      ┆ Build              ┆ Channel     ┆ Size       │
 │ │ ╞═════════════════╪══════════════╪════════════════════╪═════════════╪════════════╡
 │ │ │ python          ┆ 3.11.8       ┆ hdf0ec26_0_cpython ┆ conda-forge ┆ 13.95 MiB  │
 │ │ │ xz              ┆ 5.2.6        ┆ h57fd34a_0         ┆ conda-forge ┆ 230.17 KiB │
 │ │ │ readline        ┆ 8.2          ┆ h92ec313_1         ┆ conda-forge ┆ 244.48 KiB │
 │ │ │ libzlib         ┆ 1.2.13       ┆ h53f4e23_5         ┆ conda-forge ┆ 46.97 KiB  │
 │ │ │ ncurses         ┆ 6.4.20240210 ┆ h078ce10_0         ┆ conda-forge ┆ 801.02 KiB │
 │ │ │ openssl         ┆ 3.2.1        ┆ h0d3ecfb_1         ┆ conda-forge ┆ 2.72 MiB   │
 │ │ │ tk              ┆ 8.6.13       ┆ h5083fa2_1         ┆ conda-forge ┆ 3.00 MiB   │
 │ │ │ libexpat        ┆ 2.6.2        ┆ hebf3989_0         ┆ conda-forge ┆ 62.16 KiB  │
 │ │ │ libsqlite       ┆ 3.45.3       ┆ h091b4b1_0         ┆ conda-forge ┆ 805.46 KiB │
 │ │ │ bzip2           ┆ 1.0.8        ┆ h93a5062_5         ┆ conda-forge ┆ 119.46 KiB │
 │ │ │ libffi          ┆ 3.4.2        ┆ h3422bc3_5         ┆ conda-forge ┆ 38.11 KiB  │
 │ │ │ ca-certificates ┆ 2024.2.2     ┆ hf0a4a13_0         ┆ conda-forge ┆ 152.08 KiB │
 │ │ │ tzdata          ┆ 2024a        ┆ h0c530f3_0         ┆ conda-forge ┆ 117.01 KiB │
 │ │ ╰─────────────────┴──────────────┴────────────────────┴─────────────┴────────────╯
 │ │ ⚠ warning validation for "/home/mittagessen/.cache/rattler/cache/pkgs/python-3.11.8-hdf0ec26_0_cpython" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/mittagessen/.cache/rattler/cache/pkgs/bzip2-1.0.8-h93a5062_5" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/mittagessen/.cache/rattler/cache/pkgs/openssl-3.2.1-h0d3ecfb_1" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/mittagessen/.cache/rattler/cache/pkgs/tk-8.6.13-h5083fa2_1" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/mittagessen/.cache/rattler/cache/pkgs/libexpat-2.6.2-hebf3989_0" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/mittagessen/.cache/rattler/cache/pkgs/ca-certificates-2024.2.2-hf0a4a13_0" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/mittagessen/.cache/rattler/cache/pkgs/libsqlite-3.45.3-h091b4b1_0" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/mittagessen/.cache/rattler/cache/pkgs/ncurses-6.4.20240210-h078ce10_0" failed: failed to read 'index.json'
 │ │   downloading          [00:00:00] [━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━]      13/13     
 │ │   linking              [00:00:00] [━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━]      13/13                                                                    │ │
 │ ╰─────────────────── (took 2 seconds)
 │
 × error Error building package: Failed to resolve dependencies: failed to link 'lib/libffi.8.dylib'
 │ │   linking              [00:00:00] [━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━]      13/13                                                                   Error:   × Failed to resolve dependencies: failed to link 'lib/libffi.8.dylib'
  ├─▶ failed to link 'lib/libffi.8.dylib'
  ├─▶ unexpected io operation while invoking /usr/bin/codesign
  ╰─▶ No such file or directory (os error 2)
```

From some other tickets, I got a feeling that cross platform builds are not really well supported but I'd like to make sure that there isn't either a small bug or some stupid mistake on my side going on.
