### ISSUE TITLE
Add support for `/source/fn`

### ISSUE THREAD

**Issue by schuylermartin45** [prefix-dev/rattler-build#829]
I found this while looking at the [latest integration test run](https://github.com/conda-incubator/conda-recipe-manager/actions/runs/8897277244?pr=39) with the conversion tooling. 

```

 ╭─ Finding outputs from recipe
 │
 ╰─────────────────── (took 0 seconds)
Error:   × Failed to parse recipe

Error:   × Parsing: invalid field `fn`.
    ╭─[12:3]
 11 │ source:
 12 │   fn: ${{ name }}-${{ version }}.tar.gz
    ·   ─┬
    ·    ╰── here
 13 │   url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
    ╰────
  help: valid fields for URL `source` are `url`, `sha256`, `md5`, `patches`, `file_name` and `target_directory`

```

It looks like `/source/fn` is not currently supported. The only reference I see in the current CEPs to this field is in the example for [CEP-13](https://github.com/conda-incubator/ceps/blob/3b2d90073a07cbc4640eaa3e1f39de03a16f3b4c/cep-13.md?plain=1#L273)

I _think_ this currently causes a few hundred recipes to fail the dry-run build in the integration tests.

Alternatively if this field is not supposed to be supported, this issue can be closed. But we will need to discuss how the field should be handled in the conversion process.

Thanks!

**Comment by schuylermartin45** [comment]
It took me a while to find what the hell `fn` is supposed to mean, but I just found the docs: https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#filename

It's "filename".....I guess I've been writing too much rust lately and kept thinking `function` :P

**Comment by schuylermartin45** [comment]
Here are the contents of the `recipe.yaml` that caused the above error:
```yaml
schema_version: 1

context:
  name: boto
  version: 2.49.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  fn: ${{ name }}-${{ version }}.tar.gz
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ea0d3b40a2d852767be77ca343b58a9e3a4b00d9db440efb8da74b4e58025e5a

build:
  number: 0
  script: python setup.py install

requirements:
  host:
    - python
  run:
    - python

tests:
  - python:
      imports:
        - boto
      pip_check: false
  - script:
      - if: py2k
        then: asadmin -h
      - s3put -h
      - if: py2k
        then: taskadmin -h

about:
  license: MIT
  summary: Amazon Web Services Library
  description: |
    Boto aims to support the full breadth and depth of Amazon Web Services.
    NOTE: Boto3, the next version of Boto, is stable and recommended for
    general use.
  homepage: https://github.com/boto/boto/
  repository: https://github.com/boto/boto/
  documentation: http://docs.pythonboto.org/en/latest/
```
