### ISSUE TITLE
Package tests not working for `emscripten-wasm32`

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#847]
The new "package" tests don't work for wasm-32:

```
context:
  version: "0.43.4"

package:
  name: pixman
  version: ${{ version }}

source:
  url: http://cairographics.org/releases/pixman-${{ version }}.tar.gz
  sha256: a0624db90180c7ddb79fc7a9151093dc37c646d8c38d3f232f767cf64b85a226

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - meson
    - ninja
    - pkg-config

tests:
  - package_contents:
      lib:
        - libpixman-1.a

about:
  homepage: http://www.pixman.org/
  license: MIT
  license_file: COPYING
  summary: A low-level software library for pixel manipulation.
  description: |
    Pixman is a low-level software library for pixel manipulation, providing
    features such as image compositing and trapezoid rasterization.
  repository: https://cgit.freedesktop.org/pixman/
```

Results in a panic:

```
thread 'main' panicked at src/package_test/content_test.rs:151:21:
not implemented: lib_as_globs for target platform: EmscriptenWasm32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
