### ISSUE TITLE
Make ${{ PREFIX }} and other "build-time" vars available in script section?

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#851]
I am wondering if it would be useful to add some variables _only_ in the script section. 

Because it would make it less annoying to deal with Windows vs. Unix env vars.

E.g. this:

```yaml
    - if: unix
      then:
        - cargo install --locked --root $PREFIX --path . --no-track
      else:
        - cargo install --locked --root %PREFIX% --path .  --no-track
```

Could be written as:

```
script: cargo install --locked --root ${{ PREFIX }} --path . --no-track
```

However, some variables introduce a "dependency" on the parsing (for example, PREFIX usually needs the package name to be available, because the directory looks something like `/bld/<package-name>-<timestamp>/placeholder`).
