### ISSUE TITLE
`script.content` not working in `tests` section

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#852]
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: my-package
  version: '0.1.0'

build:
  noarch: python

requirements:
  run:
    - python

tests:
  - script:
      content: |
        import polars
      interpreter: python
    requirements:
      run:
        - polars
```

```bash
❯ rattler-build build -r recipe/recipe.yaml

 ╭─ Finding outputs from recipe
 │
 ╰─────────────────── (took 0 seconds)
Error:   × Failed to parse recipe

Error:   × Parsing: an unspecified error occurred.
    ╭─[16:14]
 15 │       - script:
 16 │ ╭─▶       content: |
 17 │ │           import polars
 18 │ ├─▶       interpreter: python
    · ╰──── expected scalar or sequence for script
 19 │         requirements:
    ╰────
Error:   × Parsing: an unspecified error occurred.
    ╭─[16:14]
 15 │       - script:
 16 │ ╭─▶       content: |
 17 │ │           import polars
 18 │ ├─▶       interpreter: python
    · ╰──── expected scalar or sequence for script
 19 │         requirements:
    ╰────
```

It's also weird that the error is displayed twice.
