### ISSUE TITLE
Package content tests - add `exists / not_exists`

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#915]
Sometimes you want to check that a file is there and sometimes the inverse.

We had ideas to use `~ foo.txt` to say 'not exists' but people were against it. 

Instead, let's use a dictionary like so:

```yaml
package_content:
  include:
    exists: 
      - foo.hpp
    not_exists:
      - baz.hpp
```
