### ISSUE TITLE
BUG: test:build constraints not respected when using selectors

### ISSUE THREAD

**Issue by h-vetinari** [prefix-dev/rattler-build#939]
Hi! 👋 

I'm starting to work on emscripten-forge a bit these days, and ran into the following problem, where @DerThorsten asked me to raise an issue.

In our pyjs [recipe](https://github.com/emscripten-forge/recipes/blob/main/recipes/recipes_emscripten/pyjs/recipe.yaml), there's the following:
```
tests:
  - script: |
       [...]
    requirements:
      build:      
          - pytester
          - if: linux
            then:
              - pyjs_code_runner >=3.0.0
              - microsoft::playwright <1.42
            else:
              - pyjs_code_runner >=3.0.0
              - microsoft::playwright
```
however, despite being on linux, my test environment mis-detects the condition:
```
 │ │ Resolving environment for:
 │ │   Platform: linux-64
 │ │   Channels:
 │ │    - file:///tmp/.tmp4JVVSW
 │ │    - file:///home/axel/emf/output
 │ │    - https://repo.mamba.pm/emscripten-forge
 │ │    - microsoft
 │ │    - conda-forge
 │ │   Specs:
 │ │    - pytester
 │ │    - pyjs_code_runner >=3.0.0
 │ │    - microsoft::playwright                 # <-- no constraint!
```
which unsurprisingly installs:
```
 │ │ │ playwright          ┆ 1.44.0   ┆ py312_0            ┆ microsoft   ┆ 32.58 MiB  │
```

removing the `if: linux` portion makes the constraints work again.
