### ISSUE TITLE
Test scripts expressions are wrong evaluated

### ISSUE THREAD

**Issue by nichmor** [prefix-dev/rattler-build#960]
Having following in recipe.yaml:

```
tests:
  - requirements:
      run:
        - bzip2
    script:
      - if: unix
        then: 
          - test -f ${PREFIX}/fonts/Inconsolata-Regular.ttf
          - test -f ${PREFIX}/fonts/Inconsolata-Bold.ttf
```

will throw an error on windows: `help: expected field `script` to be a list of commands`
until you add` - echo 'hello'`.

I think we need treat if:then as a list in this case or treat it as an empty list
