### ISSUE TITLE
variant is undefined when trying to evaluate it even though it's set in variant config

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/rattler-build#985]
```yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: my-package

recipe:
  name: ${{ name }}
  version: '1.0.0'

outputs:
  - package:
      name: ${{ name + '-' + variant }}
```

```yml
variant:
  - a
  - b
```

```bash
❯ rattler-build build -r recipe/recipe.yaml -m recipe/variants.yaml

 ╭─ Finding outputs from recipe
 │
 ╰─────────────────── (took 0 seconds)
Error:   × Failed to parse recipe

Error:   × Parsing: failed to render Jinja expression: invalid operation: tried to use + operator on unsupported types string and undefined (in <string>:1)
    ╭─[12:13]
 11 │   - package:
 12 │       name: ${{ name + '-' + variant }}
    ·             ─────────────┬─────────────
    ·                          ╰── invalid operation: tried to use + operator on unsupported types string and undefined
    ╰────
```
